### ISSUE TITLE
Behaviour Change: GET Playlist - artwork_url is blank/empty instead of null

### ISSUE THREAD

**Issue by mgoodfellow** [soundcloud/api#10]
## Title: Behaviour Change - GET Playlist - artwork_url is blank/empty instead of null
Issue found of: Oct, 2020

### Endpoint(s):
* `GET /playlists/{id}`

### Scope(s):
* None

### Steps to reproduce:
```bash
curl --request GET \
  --url 'https://api.soundcloud.com/playlists/1144732777?client_id=DONT_SHARE_CLIENT_ID'
```

### Expected behaviour:
Documentation is slightly unspecified if there is no artwork: https://developers.soundcloud.com/docs/api/reference#playlists

### Actual behaviour:
Recently we have started receiving an empty string if there is no artwork, however, I would expect a `null` value if there was no artwork (like for other string fields that have no value)

**Comment by rahul-sc** [comment]
Thanks for reporting. This was not intended. Please let us know if you see other issues similar to this.

**Comment by rahul-sc** [comment]
@mgoodfellow please check. It should be resolved now. Can you confirm?

**Comment by mgoodfellow** [comment]
Hi @rahul-sc - yes, from the examples I have seen over the last 24 hours, this is now correctly returning as `null`. Thanks!
