### ISSUE TITLE
SoundCloud login on Android web opens SoundCloud app on redirect

### ISSUE THREAD

**Issue by jasongrishkoff** [soundcloud/api#101]
Per the title, when a user who has the SoundCloud Android app installed tries to log into my website via `soundcloud.com/connect`, it seems like the callback forces the SoundCloud app to open, rather than proper resolving within my app. I assume this is because the app default attempts to open urls with `soundcloud.com`.

Is this a behavior that should be fixed? Or is there something I need to change to prevent the SoundCloud app from opening my `connect` attempt.

**Comment by rahul-sc** [comment]
Hey @jasongrishkoff can you share your sc account your app is associated with, please? We need to reproduce this in order to better understand what's happening here.

**Comment by jasongrishkoff** [comment]
The API key is associated with my account https://soundcloud.com/indieshuffle -- though note that contradictory to the account name, it's the SubmitHub API key in action here.  You can try testing by connecting to www.submithub.com using SoundCloud, from an Android device that has the SoundCloud app installed.   Hope that helps replicate!

**Comment by dasha-kobzeva** [comment]
Hi @jasongrishkoff,
what if you try calling `api.soundcloud.com/connect` instead of `soundcloud.com/connect`? 

As Soundcloud owns the `Soundcloud domain the app is a first responder by default. It's a feature and I doubt we can change it.

**Comment by jasongrishkoff** [comment]
That did the trick, thanks! And just to confirm, this endpoint will keep working with `client_id` in the URL string, yes? Doesn't need authorization headers?

**Comment by dasha-kobzeva** [comment]
Glad to hear it worked!
Yes, this endpoint is a part of authorization, and `client_id` is a required parameter to provide you with an `authorization_code`. At this point header does not exist as you don't have a token :)

**Comment by dasha-kobzeva** [comment]
I'm closing this issue, let us know if there are any other questions!
