### ISSUE TITLE
Authentication error in NW.js application

### ISSUE THREAD

**Issue by crunkzilla** [soundcloud/api#102]
My desktop application is made with NW.js (it's a software platform based on Chromium and Node.js). So it's a web application working in the built-in browser. When I open `https://api.soundcloud.com/connect?client_id={CLIENT_ID}&redirect_uri={REDIRECT_URI}&response_type=code` and try to sign in I got `signin_denied`. But everything is fine when I do the same in an ordinary web application.

**Comment by dasha-kobzeva** [comment]
Hi @crunkzilla,
Unfortunately, we are not familiar with NW.js and cannot advise on how it differs from any other application.
Could you provide us some logs or any other information so we can try to assist you?

Thank you

**Comment by rahul-sc** [comment]
I've received from our internal teams that our systems flagged this as a bot and is denied entry. 
Are you using API keys from NW.js or your own? Can you share your soundcloud account to which you have an API key with?

**Comment by dasha-kobzeva** [comment]
as no further feedback was provided, we are closing this issue for now
