### ISSUE TITLE
Multiple callback urls for apps

### ISSUE THREAD

**Issue by ponny** [soundcloud/api#103]
## Title: Allow multiple callbacks for OAuth apps

We're having an issue at the moment where our staging servers don't have a SoundCloud app that works.  We've currently only got a development app (i.e. local with overridden hostname) and the prod app.  Since creating new apps is disabled, it'd be great if we could update the development app to include the staging URLs too.  Most other OAuth providers provide this capability.

### Workaround

If this isn't possible/not going to happen in the near future, could we get a couple of copies of our dev app with new redirect_uris?

**Comment by rahul-sc** [comment]
We can create you a new credential set under your existing account with new redirect_uris - please see readme FAQ on how to request for this

**Comment by rahul-sc** [comment]
Closing this for now.
