### ISSUE TITLE
soundcloud API keys/Apps removed from dev profile

### ISSUE THREAD

**Issue by gbruzzo** [soundcloud/api#108]
Dear Sirs, 

Hello there! 

I am reaching out because recently our registered apps were removed from our profile  [https://soundcloud.com/you/apps](https://soundcloud.com/you/apps)
We had 3 apps registered e.g. **3** API keys we could use for production and for testing. 

We were using one of these keys to enable a Wordpress/HTML5 Audio plugin to connect and stream music from our profile to our website. 

our profile URL: [soundcloud.com/rarenoiserecords ](https://soundcloud.com/rarenoiserecords)
our website : [rarenoiserecords.com](https://rarenoiserecords.com)
the audio plugin : [https://codecanyon.net/item/modern-audio-player-wordpress-plugin/19925056](https://codecanyon.net/item/modern-audio-player-wordpress-plugin/19925056)

We became aware of the issue about ten days ago, when our player ceased to be able to stream our Soundcloud playlists and started instead returning the following errors 

```
Access to XMLHttpRequest at 'https://api.soundcloud.com/playlists/398498096' (redirected from 'https://api.soundcloud.com/resolve.json?url=https%3A%2F%2Fsoundcloud.com%2Frarenoiserecords%2Fsets%2Frecentnoiz&client_id=htuiRd1JP11Ww0X72T1C3g&limit=999999999&linked_partitioning=1&format=json&_status_code_map[302]=200') from origin 'https://www.rarenoiserecords.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```
followed by 

`sdk.js:1 GET https://api.soundcloud.com/playlists/398498096 net::ERR_FAILED`

We are aware API security is being upgraded. Since our apps and keys were deleted, we are now unable to test / upgrade our app and/or suggest upgrades to the plugin developer

Please advise urgently

Giacomo Bruzzo

**Comment by dasha-kobzeva** [comment]
Hi @gbruzzo,
please refer to our README section https://github.com/soundcloud/api/blob/master/README.md#my-app-disappeared-from-httpssoundcloudcomyouapps-what-should-i-do with steps on how to proceed.
 
Please be aware, that JS SDK support was terminated, and the resolve() method would not work through it from now on.

**Comment by gbruzzo** [comment]
Hi there @dasha-kobzeva 
thank you for your response. I had originally written to support on 

[https://help.soundcloud.com/hc/en-us/requests/new?ticket_form_id=581048](https://help.soundcloud.com/hc/en-us/requests/new?ticket_form_id=581048
) 

as suggested on the README section on [https://github.com/soundcloud/api/blob/master/README.md#my-app-disappeared-from-httpssoundcloudcomyouapps-what-should-i-do ](https://github.com/soundcloud/api/blob/master/README.md#my-app-disappeared-from-httpssoundcloudcomyouapps-what-should-i-do )

as you just suggested I should. 

They are the ones who told me to write on Github. 

I will include a link on this page in my original ticket now and see what happens. 

Thank you

Giacomo Bruzzo

**Comment by gbruzzo** [comment]
@dasha-kobzeva 

Hello! 

According to https://github.com/soundcloud/api/issues/84#issuecomment-898296076 : 
`
For JS SDK, it is still not decided if we will continue maintaining it or deprecate. In both cases, we will let the community know. That said, JS SDK is not compliant with the recent changes at the moment. We understand this is not ideal and disruptive and working on a possible solution.`

Do you have a timeframe for a decision? There are tons of Audio players for Wordpress and similar platforms which will lose access to Soundcloud if the JS SDK is deprecated.

Thanks in advance for any comments

Giacomo Bruzzo

**Comment by rahul-sc** [comment]
Hey @gbruzzo - we will be deprecating th JS SDK too. But we will continue to the host the .js for the old version.
We are essentially opening up the SDK maintenance to the community, as we're squarely focused on the API only for now. 

Closing this ticket as your original request was resolved
