### ISSUE TITLE
Access token ok, authorization fail

### ISSUE THREAD

**Issue by SorenHindy** [soundcloud/api#109]
Hi

I cannot get authorized accessing the API. Auth process runs and I can refresh the access token. But every request gets a 401.

Further, the documentation is ambiguous for the Authorization header formatting. See images.

I tried both "OAuth", "Bearer" and clean.

And no error message for troubleshooting.

Please help, thanks.

![billede](https://user-images.githubusercontent.com/88378249/130582195-af59e195-5cb9-4128-b3cd-e82b9ce01ded.png)

![billede](https://user-images.githubusercontent.com/88378249/130582247-421e825d-79fd-40fd-b89a-ce9a9b413817.png)

![billede](https://user-images.githubusercontent.com/88378249/130582271-9093edcd-7e89-4291-b837-ae2a63a18cc8.png)

**Comment by rahul-sc** [comment]
This is a token generated using client_credentials and not authorization_code grant. The former doesn't have user context and it meant for server-side integrations.

**Comment by SorenHindy** [comment]
Ahh. I was going that route as an authorization_code request to returned 401 with error "invalid_grant".

I now realise, that was because the redirect_url param needs to be very literal. With https://.

Now it works.

BTW. I works with the more standard Bearer prefix for the auth header. I hope you will keeps this on, depite documentation says OAuth prefix.

Thanks.

**Comment by rahul-sc** [comment]
Great catch! We just added this :) Will update the release notes soon. 
https://github.com/soundcloud/api/releases
