### ISSUE TITLE
400 errors "invalid request"

### ISSUE THREAD

**Issue by pierrocknroll** [soundcloud/api#11]
## Title: Cannot upload tracks
Issue found of: Novembrer 9th, 2020

### Endpoint(s):
* `POST tracks`

### Expected behaviour:
A downloaded track as expected here : `https://developers.soundcloud.com/docs/api/reference#tracks`.

### Actual behaviour:
400 Bad Request
Message : invalid request

Hello,
since a few days, I can't upload tracks anymore.

This appeared suddenly and for no reason, I have not changed anything in the code and my API Key is still valid.

What does the 400 "invalid request" error mean? 

Has anything changed in the way of sending a track?
Thanks a lot

**Comment by rahul-sc** [comment]
Hello @pierrocknroll Can you please share a few more details i.e., your full request payload and the API response, please? Note - please ensure to obfuscate your keys/tokens from the data you share here)

**Comment by pierrocknroll** [comment]
Hi @rahul-sc 
It's a bit difficult to send you an example, it's very random, it depends on the client token we use, but a simple curl request such as :
```
curl --request POST \
  --url 'https://api.soundcloud.com/tracks' \
  --header 'Authorization: OAuth XXX' \
  --header 'Content-Type: multipart/form-data' \
  --form "track[title]=Test" \
  --form "track[asset_data]=@test2.mp3"
```

Can work or not depending on the OAuth token used.

A few months ago, we sometimes had errors about upload quotas for some customers such as : 
error_message: Sorry, you've exceeded your upload limit.

Now, we receive an HTTP 400 error with :
{"error": "invalid request"}

Have you changed the way you report errors? Or is this another problem?
Our account is hello@ausha.co, please note that we use your API to upload to other accounts via oAuth, not ours.
I insist on the fact that it depends on the token we use since we have many customers. 

Can you take a look at why our account generates so many 400 errors?

Thanks a lot

**Comment by pierrocknroll** [comment]
Hello @rahul-sc , any update about this issue ? Thanks

**Comment by rahul-sc** [comment]
Hey @pierrocknroll we're looking into this. The fix would include outlining why exactly the request is failing

**Comment by rahul-sc** [comment]
Hey @pierrocknroll we pushed out an update to show the specific error messages fo 4xx now. Can you check, please?

**Comment by pierrocknroll** [comment]
Hello @rahul-sc 
I have strange error messages now :

{\"code\":400,\"message\":\"Invalid request: List((/title,List(JsonValidationError(List(error.path.missing),List()))))\",\"link\":\"https://developers.soundcloud.com/docs/api/explorer/open-api\",\"status\":\"400 - Bad Request\",\"errors\":[{\"error_message\":\"Invalid request: List((/title,List(JsonValidationError(List(error.path.missing),List()))))\"}],\"error\":null}"}

**Comment by rahul-sc** [comment]
Tnx. We're continuing to look into this. Seems like an edge case that our team didn't consider. Will keep you posted

**Comment by pierrocknroll** [comment]
Hello @rahul-sc 
I'm sorry but do you have any news?

**Comment by rahul-sc** [comment]
Hello @pierrocknroll we pushed out a change just yesterday. Could you please check again? You should be seeing meaningful errors now. 

If the problem still persists, please share with a full requests/response (without the keys) to reproduce this.

**Comment by pierrocknroll** [comment]
I have the exact same response than my previous message : https://github.com/soundcloud/api/issues/11#issuecomment-758565717

And the request is like my example :  https://github.com/soundcloud/api/issues/11#issuecomment-747554303

Nothing change for me

**Comment by rahul-sc** [comment]
Sorry, I spoke too soon. The last bit of the fix is still WIP. We're making active progress on this. Thanks for your patience

**Comment by rahul-sc** [comment]
Heya. May require a bit more of troubleshooting with you. You should see a bit more verbose error messages. 
Do share what you find now, please

**Comment by pierrocknroll** [comment]
I have now an HTTP error 422 with message :
"Require uid, original_filename, and title parameters"

Is this normal?
What should the values of these parameters be?
They are not given in the documentation

**Comment by rahul-sc** [comment]
Heya. We were able to make some more changes to clarify error messaging. Could you try again and share what your response is?

Also, if you're still seeing issues, could you share with us the actual log or a curl that you yourself can also reproduce it, please?

**Comment by pierrocknroll** [comment]
Hello @rahul-sc 

The error messages seems to be correct now.

It seems that the accepted values for boolean parameters like "downloadable" have been revised, I now have to send 1 or 0 whereas before I used to send I think "True" or "False".

And now I have "quota Sorry, you've exceeded your upload limit" back for clients in over-quota.

Thanks a lot !
