### ISSUE TITLE
JS SDK get method returning 302 response

### ISSUE THREAD

**Issue by aayler** [soundcloud/api#111]
Title: JS SDK get method returning 302 response
Issue found of: August 27th, 2021

Endpoint(s):
* SoundCloud JS SDK get method; following directions under = https://developers.soundcloud.com/docs/api/guide#playing > "Streaming Tracks"

Scope(s):
* JS SDK initialized with client id

Steps to reproduce:
```
        SC.get(`/tracks/${id}/stream`, { allow_redirects: 'False' }).then(result => {
          console.log(result); // undefined
        });
```

Expected behavior:
Returns: A promise that will resolve with the requested resource

Actual behaviour:
302 Moved Temporarily; unable to get redirected resource URL to populate <audio> element's source attribute.

**Comment by dasha-kobzeva** [comment]
Hi @aayler,

We have stopped the JS SDK maintenance and it's not compliant with the recent security updates. We suggest either migrating to using REST API directly or if you are interested we are looking for JS SDK maintainers.

**Comment by aayler** [comment]
greetings @dasha-kobzeva , thanks so much for the confirmation re: JS SDK.
would you have a link for documentation available on how to implement client side REST API calls for track URLs to stream via an HTML audio element (as the docs we’ve seen still reference JS SDK methods)?

**Comment by dasha-kobzeva** [comment]
@aayler,
I'm afraid we do not have documentation for an HTML audio element. With a current change, you cannot have a fully client side implementation, as the auth must happen from a server.

**Comment by aayler** [comment]
thanks again @dasha-kobzeva, i appreciate your prompt response!

**Comment by dasha-kobzeva** [comment]
not sure but maybe this thread can be of use: https://github.com/soundcloud/api/issues/93#issuecomment-896193290
