### ISSUE TITLE
How can I use the new API with AUTH in a userscript?

### ISSUE THREAD

**Issue by Subfader** [soundcloud/api#112]
My userscript broke because I cannot access the tracks API anymore.

`$.getJSON( 'https://api.soundcloud.com/resolve.json?url=https%3A%2F%2Fsoundcloud.com%2Fiamhearteyes%2Ftwo-years-under-dirt&client_id=MY_ID', function(t) {
    console.log( t.title );
});`

gives

Access to XMLHttpRequest at 'https://api.soundcloud.com/tracks/941806849' (redirected from 'https://api.soundcloud.com/resolve.json?url=https%3A%2F%2Fsoundcloud.com%2Fiamhearteyes%2Ftwo-years-under-dirt&client_id=MY_ID') from origin 'https://soundcloud.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
49-c663d9d8.js:70 GET https://api.soundcloud.com/tracks/941806849 net::ERR_FAILED

**Comment by hasnain143** [comment]
i am facing the same issue bro but i didnt find any solution on google.

**Comment by dasha-kobzeva** [comment]
Hello @Subfader,

your request to `/resolve` is still using the `client_id` query parameter which is deprecated. PLease provide an authorization header in your requests. You can find more info in our guide: https://developers.soundcloud.com/docs/api/guide#access-resources

**Comment by Subfader** [comment]
Thanks. "Authenticating without the SoundCloud Connect Screen" > "this example is not applicable to the JavaScript SDK"

We cannot access the API in userscripts? I only need basic track info...

**Comment by dasha-kobzeva** [comment]
with new security changes, you cannot have a pure client-side integration, unfortunately. We have also stopped supporting the JS SDK. To be able to pull in the track info you have to authenticate your app on the server and store the token.

**Comment by hasnain143** [comment]
how @dasha-kobzeva please send us sample code if posible.

**Comment by dasha-kobzeva** [comment]
@hasnain143 what sample code do you mean?
Our documentation provides curl examples for authentication and other requests. You are always welcome to look at those. 
With REST API you can implement it the way you want, but you cannot do it just in the browser as before, because we do not have client-side authentication.

**Comment by hasnain143** [comment]
@dasha-kobzeva i mean this how to authenticate your app on the server and store the token

**Comment by dasha-kobzeva** [comment]
> @dasha-kobzeva i mean this how to authenticate your app on the server and store the token

@hasnain143, 
Unfortunately, I cannot provide you a sample code as there is no one right way to do it and it is not in the scope of the issue tracker. 

Here are some resources you can check on writing your own server and dealing with tokens.

https://www.digitalocean.com/community/tutorials/how-to-create-a-web-server-in-node-js-with-the-http-module
https://blog.ropnop.com/storing-tokens-in-browser/
https://javascript.plainenglish.io/server-side-user-authentication-and-authorization-in-node-apps-733c387c7103
https://auth0.com/blog/complete-guide-to-nodejs-express-user-authentication/

Hope it helps and good luck! :)

I will close this ticket for now.

**Comment by Subfader** [comment]
** kills open SoundCloud API, whiches everyone good luck **
