### ISSUE TITLE
Soundcloud Authorization header when using resolve end point 

### ISSUE THREAD

**Issue by hasnain143** [soundcloud/api#115]
Soundcloud Authorization header issue all good when use me/tracks end response coming but when using resolve end point its shows cors policy issue on console

im just using this code
how to send authorization token when using resolve end point.
   SC.initialize({
        client_id: 'my client id',
        redirect_uri: 'my redirect url',
        response_type:'code'
      });

      var audioFile = 'https://soundcloud.com/volcanicvo/matt-fogarty-promo-demo-volcanic-agency';

      SC.get('/resolve?url=' + audioFile ).then(function(track){
        console.log('resolve:', track);
      });

## Title: Cannot retrieve all tracks for a user
Issue found of: September 20th, 2020

### Endpoint(s):
* `GET /users/{id}/tracks`

### Scope(s):
* None (application is not using authentication i.e., implicit flow)

### Steps to reproduce:
```bash
curl --request GET \
  --url 'https://api.soundcloud.com/users/12345/tracks?limit=1&linked_partitioning=true&client_id=DONT_SHARE_CLIENT_ID'
```

### Expected behaviour:
A list of tracks as described at `https://developers.soundcloud.com/docs/api/reference#users`.

### Actual behaviour:
500 Server Error (consistently)

**Comment by rahul-sc** [comment]
Hello. SoundCloud JS SDK is deprecated an no longer maintained.
https://github.com/soundcloud/soundcloud-javascript

Would suggest using the api directly via your own client
