### ISSUE TITLE
How to access track API with only the page URL?

### ISSUE THREAD

**Issue by Subfader** [soundcloud/api#117]
Since your resolver is broken / undocumented (#116) for javascript I wonder how we are supposed to access the track API when all we have is the page URL.

**Comment by Subfader** [comment]
And thanks for killing all my scripts btw.

**Comment by Subfader** [comment]
Even in ugly curl it gives a 401

`curl -X POST "https://api.soundcloud.com/resolve?url=https%3A%2F%2Fsoundcloud.com%2Fresident-advisor%2Fra795-moopie" \
     -H  "Authorization: MY_FRESH_TOKEN"`

**Comment by rahulrumalla** [comment]
/resolve is a GET request. Can u try with that?

**Comment by Subfader** [comment]
Same:
`curl -X GET "https://api.soundcloud.com/resolve?url=https%3A%2F%2Fsoundcloud.com%2Fresident-advisor%2Fra795-moopie" \
     -H  "Authorization: MY_FRESH_TOKEN"

`{"code":401,"message":"","link":"https://developers.soundcloud.com/docs/api/explorer/open-api","status":"401 - Unauthorized","errors":[],"error":null}% `

**Comment by Subfader** [comment]
Got it. I missed the OAuth:
`-H  "Authorization: OAuth MY_FRESH_TOKEN`

**Comment by rahulrumalla** [comment]
Glad you got this resolved. For the next time, I request you to be more aware of your comments here. We're here to help, but we will not tolerate derogatory remarks. 

Also, it always helps for us to diagnose when you provide us with reproducible scenarios for bug reports.
