### ISSUE TITLE
`download_url` property of tracks endpoint response returning 404

### ISSUE THREAD

**Issue by aayler** [soundcloud/api#118]
Title: `download_url` property of tracks endpoint response returning 404
Issue found of: September 3rd, 2021

Endpoint(s):
* `GET /tracks/1234/download`

Scope(s):
* OAuth token provided in header

Steps to reproduce:
```bash
curl --request GET \
  --url 'https://api.soundcloud.com/tracks/12345/download' --header 'Authorization: OAuth ACCESS_TOKEN'
```

Expected behaviour:
MP3 asset (track).

Actual behaviour:
404 Server Error (consistently)

**Comment by dasha-kobzeva** [comment]
HI @aayler,
Could you please provide us with an actual API call so we can reproduce it? Which track are you trying to download?

Thank you

**Comment by aayler** [comment]
hi @dasha-kobzeva, here are the requests:
```curl --request POST --url 'https://api.soundcloud.com/oauth2/token?grant_type=client_credentials&client_id=XXX&client_secret=XXX' --header 'accept: application/json; charset=utf-8\r\nContent-Type: application/x-www-form-urlencoded'```

then, using `access_token` that was included in the response to ^
```curl --request GET --url 'https://api.soundcloud.com/tracks/1091160055/download' --header 'Authorization: OAuth XXX'```

which results in: 
```{"code":404,"message":"","link":"https://developers.soundcloud.com/docs/api/explorer/open-api","status":"404 - Not Found","errors":[],"error":null}```

hope this is enough information, thanks again!

**Comment by dasha-kobzeva** [comment]
Hi @aayler,
 
The track you are trying to download is not downloadable.
If you call `/tracks/1091160055` you will see the response contains the field `"downloadable": false`.

There is a bug on our side that we still provide the link for download, we will fix that.
But you get 404 as the resource was not found for download.


Hope that answers your question.

**Comment by dasha-kobzeva** [comment]
we have released a fix to not show the download_url in the track response in case its not downloadable
