### ISSUE TITLE
Pagination API returned the same next_href field thus failed to retrieve all track records

### ISSUE THREAD

**Issue by cindychaopeng** [soundcloud/api#12]
## Title: Pagination API returned the same next_href field thus failed to retrieve all track records
Issue found of: Nov 30th, 2020

### Endpoint(s):
* `GET /users/{id}/tracks`

### Scope(s):
* None (application is not using authentication i.e., implicit flow)

### Steps to reproduce:
```bash 
###first call with  linked_partitioning=true to start the paginated retrieval
curl --request GET \
  --url 'https://api.soundcloud.com/users/12345/tracks?linked_partitioning=true&page_size=200&cursor=2018-02-27T14:37:10.000Z,tracks,00405959469'
```
###SoudCloud response contains next_href 
"next_href": "https://api.soundcloud.com/users/123/tracks?linked_partitioning=true&page_size=10&cursor=2018-02-27T14:37:10.000Z,tracks,00405959469"

###then make the subsequent calls with cursor=<next_href content>

### expected behaviour:
receive a different next_href so we can retrieve a different set of records

### Actual behaviour:
receive the same "next_href" content again and again

**Comment by rahul-sc** [comment]
Closing this as it was resolved and confirmed.
