### ISSUE TITLE
Search Endpoint Results Not as Same As Live App

### ISSUE THREAD

**Issue by JGSolutions** [soundcloud/api#120]
## Title: Cannot retrieve all tracks for a user
Search Endpoint Results

### Endpoint(s):
* `GET /tracks`

### Scope(s):
* OAuth token provided in header

### Steps to reproduce:
```bash
curl --request GET \
curl -X GET "https://api.soundcloud.com/tracks?q=Global%20DJ%20Broadcast%20World%20Tour%3A%20Luminosity%202021" -H  "accept: application/json; charset=utf-8" -H  "Authorization: OAuth"
```

### Expected behaviour:
A list of results of searched tracks.

### Actual behaviour:
i get empty results from api but on the actual soundcloud web app if i perform the same query search term i get results and displays some tracks. use this search term: Global DJ Broadcast World Tour: Luminosity 2021

**Comment by dasha-kobzeva** [comment]
Hi @JGSolutions,
we are sorry to hear you are experiencing this issue.

We will try to reproduce and see what's going on and come back to you ASAP.

Thank you

**Comment by JGSolutions** [comment]
@dasha-kobzeva Perfect thanks :)

if you need more info let me know

**Comment by dasha-kobzeva** [comment]
Hi @JGSolutions,

The difference between your request to API and the request on the platform is that there is a set of additional parameters that you are not using.

As you can see here (https://developers.soundcloud.com/docs/api/explorer/open-api#/search/get_tracks) we have a parameter called `access` that allows you to search for all the types of resources. On the platform everything is available, but as API provides external access by default you only get the playable resources. In your case for that query, there is none so the response is empty. 

You can read more about the `access` here: https://developers.soundcloud.com/blog/high-tier-content-in-the-soundcloud-api

if you adjust your request, you will get the same results:

```
curl -X GET "https://api.soundcloud.com/tracks?q=Global%20DJ%20Broadcast%20World%20Tour%3A%20Luminosity%202021&access=playable,preview,blocked" \
-H  "accept: application/json; charset=utf-8" -H  "Authorization: OAuth"
```

Let me know if you have further questions

**Comment by JGSolutions** [comment]
Ohh thank you soo much...Yes now it works!. My fault and totally missed this :(

**Comment by JGSolutions** [comment]
Just one more question.

Some of the response I get stream_url: null. is that normal?

**Comment by dasha-kobzeva** [comment]
Yes, it is. tracks with `access=blocked` are restricted for off-platform streaming. You can see the metadata, but playback is not allowed.
For the reference: 

access equals:
playable — The user can listen to a full track.
preview — The user gets a snippet of a track (Go+ content for free users).
blocked — The user isn’t allowed to play the track but can see the metadata.

**Comment by JGSolutions** [comment]
@dasha-kobzeva Ok thanks

So there is no way to get the stream Url?

**Comment by dasha-kobzeva** [comment]
no

**Comment by JGSolutions** [comment]
ok thanks so what do other devs or apps do with just metadata? if i can't play it it's useless :(

**Comment by dasha-kobzeva** [comment]
@JGSolutions,
You could go to Soundcloud and listen there :)

There are restrictions by our rightsholders, defining which content is allowed off-platform. Plus Your user might not have GO+ subscription, which also defines what you can stream or not. I'd suggest not to show the tracks that are not streamable and only use a flag `access=playable`
