### ISSUE TITLE
What is the rate limit for POST /oauth2/token

### ISSUE THREAD

**Issue by wickeym** [soundcloud/api#123]
## What is the rate limit for POST /oauth2/token

Also does this same rate limit apply to refresh tokens?
Is this rate limit a rolling 24 hours or does it reset at midnight?

### Endpoint(s):
* `POST /oauth2/token`

### Scope(s):
* global

### Steps to reproduce:
```bash
curl --request POST \
--url https://api.soundcloud.com/oauth2/token \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data client_id=CLIENT_ID \
--data client_secret=CLIENT_SECRET \
--data grant_type=client_credentials
```

### Expected behaviour:
https://developers.soundcloud.com/docs/api/rate-limits#errors

### Actual behaviour:
429 without any other info.

**Comment by dasha-kobzeva** [comment]
Hello @wickeym,

The rate-limiting applies only to client_credentials flow at the moment. 

When you hit the limit, the countdown starts until you reach the end of it, so it doesn't reset at midnight but is related to your specific requests. 

You can find more information about it in our release notes: https://github.com/soundcloud/api/releases/tag/2021-09-07

Let me know if you have more questions.

**Comment by wickeym** [comment]
Thank you for your quick response!
I have one more question, how long does the refresh_token stay valid.
Is it invalidated as soon as a new access_token is obtained (either through client_credentials or refresh_token), or does it expire after a certain time period?

Cheers,
Michael

**Comment by dasha-kobzeva** [comment]
@wickeym,
In the response you have a field `expires_in` which tells you in millis when the token expires (currently it's always 1h).

If you obtain a new token through refresh_token flow, the previous one is invalidated.
With client_credentials flow you might hit the rate-limit, so we recommend using the refresh_token flow
