### ISSUE TITLE
Client credentials access token valid for 1 hour

### ISSUE THREAD

**Issue by mgoodfellow** [soundcloud/api#125]
Hi,

The release notes here: https://github.com/soundcloud/api/releases/tag/2021-09-07 state:

> The client credential grant exchange serves server-side client applications, and currently the tokens are valid for
24 hours. We expect reasonable usage for the client credential exchange per client application per 24 hours.

However, it appears tokens are still being generated with 1 hour validity:

![image](https://user-images.githubusercontent.com/6501186/132642140-2fd0acb1-7b65-43b1-a120-5096bba60de3.png)

**Comment by dasha-kobzeva** [comment]
Confirming: tokens last 1 hour.
We have updated the release notes.

Sorry for the confusion.

**Comment by pluc** [comment]
this is utterly unbelievable.
