### ISSUE TITLE
Cannot obtain an access token

### ISSUE THREAD

**Issue by benchmarkrules** [soundcloud/api#126]
Hi,
Despite reading many articles and issues  on authorization in SoundCloud, I cannot still get this right.

I basically followed the process in 
https://stackoverflow.com/questions/68459401/soundcloud-api-authentication-always-throws-401-unauthorized

 as follows:

1.  After I managed to get SoundCloud Support to change my setting to include a redirect_uri, I was able to get the code via this:

https://api.soundcloud.com/connect?client_id=MY_CLIENT_ID&redirect_uri=MY_REDIRECT_URI&response_type=code&state=Getcode

I note that I did not have the &scope= as in the above article. Not sure if that makes a difference.

I did get a code back and have saved that in a file. Question at this point: Does this code expire?

2.  Then I attempted to obtain an access token by using the command as below:

curl -X POST "https://api.soundcloud.com/oauth2/token" -H "accept: application/json; charset=utf-8" -H "Content-Type: application/x-www-form-urlencoded" 
-d "grant_type=authorization_code&client_id=MY_CLIENT_ID&client_secret=MY_CLIENT_SECRET&code=MY_CODE&redirect_uri=MY_REDIRECT_URI&refresh_token="

I expected an access token and a refresh token. However I got the following error:

{"code":401,"message":"invalid_grant","link":"https://developers.soundcloud.com/docs/api/explorer/open-api","status":"401 - Unauthorized","errors":[{"error_message":"invalid_grant"}],"error":null,"error_code":"invalid_grant"}

I checked the above curl statement with the "Try it out" on
https://developers.soundcloud.com/docs/api/explorer/open-api#/oauth/post_oauth2_token

Here, you can actually put in your own details , click a button and it tells you what curl command to use. This also gave me the same error.

 I am at a loss. What have I missed or done wrong?

Ultimately, I want to upload mp3 files with our app using PHP. To do that I need an access token.

Appreciate any help
Thanks

**Comment by dasha-kobzeva** [comment]
Hello @benchmarkrules,

I'm sorry to hear you are struggling with the authentication. I will try to help you. 

> I did get a code back and have saved that in a file. Question at this point: Does this code expire?
As far as I remember it does not, but you can only use it once. So if you fired a request, the second one with the same code might return 401.

> curl -X POST "https://api.soundcloud.com/oauth2/token" -H "accept: application/json; charset=utf-8" -H "Content-Type: application/x-www-form-urlencoded"
> -d "grant_type=authorization_code&client_id=MY_CLIENT_ID&client_secret=MY_CLIENT_SECRET&code=MY_CODE&redirect_uri=MY_REDIRECT_URI&refresh_token="

Looking at your request I see that you are sending quite a lot of parameters and some of them are only required for specific auth flows.
In our API when you `Try it out` it shows you which parameter applies to which flow, like this:

<img width="590" alt="Screenshot 2021-09-09 at 11 01 03" src="https://user-images.githubusercontent.com/56645782/132656330-33bf4d9c-c1ed-41c7-bbb8-58214f1cde9c.png">

You can see it states `Required on ...`. For your use case you should provide the following params:
* grant_type=authorization_code
* client_id
* client_secret
* code
* redirect_uri

Notice that refresh_token is omitted, and in API Spec you would leave it completely empty.

<img width="577" alt="Screenshot 2021-09-09 at 11 03 24" src="https://user-images.githubusercontent.com/56645782/132656669-5cf52a34-f525-4b20-bf75-0072ba456f5e.png">

Here is also a valid example of how your request should look like:

```
curl -X POST "https://api.soundcloud.com/oauth2/token" \
     -H 'Content-Type: application/x-www-form-urlencoded' \
     -H 'Accept: application/json’ \
     -H 'X-Real-Ip: IP_ADDRESS' \
     --data-urlencode "grant_type=authorization_code" \
     --data-urlencode "client_id=XXX" \
     --data-urlencode "client_secret=XXX" \
     --data-urlencode "redirect_uri=XXX" \
     --data-urlencode "code=XXX"
```
Let me know if it works for you.

**Comment by benchmarkrules** [comment]
Hi dasha-kobzeva ,

Thank you so much for your help.
I have some success!!
I didn't try exactly what you suggested but you mentioned that the code can only be used once. That gave me a clue

So, I got another code with (as before):
https://api.soundcloud.com/connect?client_id=MY_CLIENT_ID&redirect_uri=MY_REDIRECT_URI&response_type=code&state=Getcode

This gave me a new code. You mentioned also that "In our API when you **Try it out** it shows you which parameter applies to which flow. That gave me confidence to know that what parameters I put in was required. This is such a good site as it allows developers to test curl with their details and then code with the knowledge that their curl command is correct. 

So, when I put in my details (Client id,  code etc) into the "Try it out" site with the old code I got earlier, I got that error message "Invalid grant".
When I then did the same with the new code that I just obtained, I got an access token which I used to upload a mp3 file with a curl command. The result from that upload looks successful. It looks like that mp3 file is still being processed. It has been doing this for 19 minutes. Not sure what to expect here but this is progress.

I am left with a question then to do with the usage of the code. Is a new one needed every time an access token is required?
Or maybe the way to work is to use refresh token every time an operation like uploading a file is invoked? 

Your advice would be valuable.

Thanks so much again
Regards

**Comment by dasha-kobzeva** [comment]
Hi @benchmarkrules,

I'm happy to hear about your success.

> I am left with a question then to do with the usage of the code. Is a new one needed every time an access token is required?
> Or maybe the way to work is to use refresh token every time an operation like uploading a file is invoked?

To avoid asking users to connect each time the token expired, I would suggest implementing the refresh_token flow. When the token hits the expiration time, just request a new one. In that case, you do not need to have an auth code.

I would also not recommend asking for a new token each time you are calling `/upload` method or anything else, as this is a misusage.

The token response contains `expires_in` parameter. Depending on that value you can set the automatic token refresh.

let me know if you have more questions.

**Comment by benchmarkrules** [comment]
Hi dasha-kobzeva ,
Thanks for that advice. Sorry for the delay in replying.
I will test what you suggest and try get the hang of it. Please don't go away, I might still need help as I progress through this.
Thanks again
Regards

**Comment by benchmarkrules** [comment]
Hi dasha-kobzeva ,
I can now report a bit of success after testing. Here is what I did:

First I refreshed my access token using an old refresh token that I got about a week ago as in:
curl -X POST "https://api.soundcloud.com/oauth2/token" -H  "accept: application/json; charset=utf-8" -H  "Content-Type: application/x-www-form-urlencoded" -d "grant_type=refresh_token&client_id=CLIENT_ID&client_secret=CLIENT_SECRET&code=&redirect_uri=https%3A%2F%2Fbenchmarkinc.com.au%2Fbenchmark%2Fsoundcloudgetcode.php&refresh_token=OLD_REFRESH_TOKEN"

This was done on the "Try it" site.

Then, I tried an upload of an mp3 file from my PC using:
curl -X POST "https://api.soundcloud.com/tracks" -H  "accept: application/json; charset=utf-8" -H "Authorization: OAuth NEW ACCESSTOKEN" -H  "Content-Type: multipart/form-data"  -F "track[release]=" -F "track[release_date]=" -F "track[tag_list]=case" -F "track[genre]=" -F "track[downloadable]=true" -F "track[license]=" -F "track[description]=PG we are trying the Trying it out" -F "track[sharing]=public" -F "track[isrc]=" -F "track[streamable]=true" -F "track[asset_data]=@15325.mp3;type=audio/mpeg" -F "track[commentable]=true" -F "track[title]=PG From Try Out" -F "track[label_name]=" -F "track[embeddable_by]=" -F "track[purchase_url]="

This was done in a command line on my PC.

This gave me a successful upload. The file was uploaded successfully to SoundCloud under my Stream. 

So, this tells me that:
If the Access Token is expired, I can just get another one using the refresh token and the refresh_token grant_type. This is what I assume you were suggesting.

This was all tested from a command prompt. Now I have to code this in PHP. Rather I have to modify my exiting code. I also to have to code to take an mp3 file from a website rather than my PC, which is what that test above did. We are getting somewhere.

The only thing I could not get working was a:

curl --request GET \
--url 'https://api.soundcloud.com/me/tracks?limit=1' \
--header 'Authorization: OAuth NEW ACCSSTOKEN'

I got an status":"401 - Unauthorized" message. I didn't concentrate on this too much as my main goal is to upload MP3 files.

Thank you so much for your help and guidance.

**Comment by dasha-kobzeva** [comment]
HI @benchmarkrules,
I'm glad to hear it's working for you now. Good job!

> curl --request GET
> --url 'https://api.soundcloud.com/me/tracks?limit=1'
> --header 'Authorization: OAuth NEW ACCSSTOKEN'
> 
> I got an status":"401 - Unauthorized" message. I didn't concentrate on this too much as my main goal is to upload MP3 files. 

Hm, not sure why you are getting 401 as your token is associated with a user and its same logic as for `/upload` endpoint.

**Comment by benchmarkrules** [comment]
Hi dasha-kobzeva ,
A question.
When I do a "refresh token", I get an access token with an expiry of "expires_in": 3599,
Is that 1 hour? (a bit less).
The api updates site (https://developers.soundcloud.com/blog/security-updates-api) says all TTLs are 6 hours. Did I miscalculate?
Thanks

**Comment by dasha-kobzeva** [comment]
yes, it is 1 hour, there is a mistake in the blog post.

**Comment by raduandw** [comment]
Hello ,
We have two registered apps
The one with "-Dev" suffix works, we get access-tokens for it, but the other one returns "401 - Unauthorized" when attempting to get access-token.
Can you please help us solve this problem?
User is https://soundcloud.com/radio-trinitas
Thank you very much.

**Comment by dasha-kobzeva** [comment]
Hello @raduandw,

Could you please provide more details of what requests are failing, so we can try to reproduce them?

Thank you

**Comment by raduandw** [comment]
@dasha-kobzeva 
It's about the request to obtain an access token with "client credentials" flow using the url https://api.soundcloud.com/oauth2/token

The request works for the app with suffix "-Dev" in the name,
but for the other one does not, we are receiving the following message:
`{
    "code": 401,
    "message": "",
    "link": "https://developers.soundcloud.com/docs/api/explorer/open-api",
    "status": "401 - Unauthorized",
    "errors": [],
    "error": null
}`

Thank you for your response

**Comment by dasha-kobzeva** [comment]
> @dasha-kobzeva It's about the request to obtain an access token with "client credentials" flow using the url https://api.soundcloud.com/oauth2/token
> 
> The request works for the app with suffix "-Dev" in the name, but for the other one does not, we are receiving the following message: `{ "code": 401, "message": "", "link": "https://developers.soundcloud.com/docs/api/explorer/open-api", "status": "401 - Unauthorized", "errors": [], "error": null }`
> 
> Thank you for your response

I ran a request with your credentials, and it works, I got the token for the Radio Trinitas app. Maybe you have a typo in your client_id or client_secret?

**Comment by raduandw** [comment]
I checked for typo but it's not.

Our "-Dev" Client ID starts with "Lbs...." and it works.
The other one's Client ID starts with "sCD..." and it doesn't.

I'm sorry to bother you so much, but can you tell me which one you tested?
Thank you very much

**Comment by dasha-kobzeva** [comment]
@raduandw, I have tested Client ID that starts with "sCD..." and it works fine.

**Comment by raduandw** [comment]
@dasha-kobzeva 
You were right in the first place - it was a typo ( I was using number 0 instead of letter O ).
It's working.
I'm sorry to have wasted your time.
Thank you
