### ISSUE TITLE
About creating a new SoundCloud API App

### ISSUE THREAD

**Issue by grarich** [soundcloud/api#128]
I tried to create a new SoundCloud API application, but the GoogleForm said "SoundCloud Application Registration
Due to the high amount of requests recently received, we will no longer be processing API application requests at this time. We are working to re-evaluate our process to make it more efficient. We are working to re-evaluate our process to make it more efficient." I was not able to create an App.
When will I be able to create a new App?

**Comment by dasha-kobzeva** [comment]
> I tried to create a new SoundCloud API application, but the GoogleForm said "SoundCloud Application Registration
> Due to the high amount of requests recently received, we will no longer be processing API application requests at this time. We are working to re-evaluate our process to make it more efficient. We are working to re-evaluate our process to make it more efficient." I was not able to create an App.
> When will I be able to create a new App?

Hi @grarich,

Unfortunately, at this time I cannot give you any estimate on when the registration will be open again.
we are working hard to open it up as soon as possible.

Thank you
