### ISSUE TITLE
Incomplete responses being received from API - Content Length matches what is returned, but content is truncated at this length

### ISSUE THREAD

**Issue by mgoodfellow** [soundcloud/api#13]
## Title: Cannot deserialise some user data
Issue found of: January 13th, 2021

### Endpoint(s):
* `GET /me`

### Scope(s):
* Logged in

### Expected behaviour:
A valid user object

### Actual behaviour:
It seems the contract for a user has changed (addition of "locale" and "primary_email_confirmed")

I also notice "primary_email_confirmed" is exposed on the normal users endpoint and not just /me ? Is that intended?

Anyway, we are having issues deserialising responses from your API as of about 15 mins ago:

```
Newtonsoft.Json.JsonSerializationException: Unexpected end when deserializing object. Path 'locale', line 1, position 878.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ThrowUnexpectedEndException(JsonReader reader, JsonContract contract, Object currentObject, String message)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
```

```
Newtonsoft.Json.JsonReaderException: Invalid character after parsing property name. Expected ':' but got: . Path 'primary_email_confirmed', line 1, position 1010.
   at Newtonsoft.Json.JsonTextReader.ParseProperty()
   at Newtonsoft.Json.JsonTextReader.ParseObject()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
```

We are still investigating the issue from our side, but we have never had any issues with SC API responses before. Are the responses being chunked? It feels like we are fetching incomplete data on /me as of a few mins ago, but the request is completed without all content?

**Comment by mgoodfellow** [comment]
Hi.

As expected:

```{"id":1669979,"kind":"user","permalink":"tanookijames","username":"tanooki james","last_modified":"2020-12-13T04:40:27Z","uri":"https://api.soundcloud.com/users/1669979","permalink_url":"https://soundcloud.com/tanookijames","avatar_url":"https://i1.sndcdn.com/avatars-000654612704-y0g45z-large.jpg","country":"United States","first_name":"tanooki","last_name":"james","full_name":"tanooki james","description":"","city":"Lil Switzerland","discogs_name":null,"myspace_name":null,"website":null,"website_title":null,"track_count":65,"playlist_count":8,"online":false,"plan":"Pro","public_favorites_count":1284,"followers_count":122,"followings_count":97,"subscriptions":[{"product":{"id":"creator-pro","name":"Pro"},"recurring":false}],"quota":{"unlimited_upload_quota":true,"upload_seconds_used":7415},"private_tracks_count":2,"private_playlists_count":0,"primary_email_confirmed":true,"locale"
```

As of about 30 mins ago now, your API endpoints are returning incomplete data and signing off the response as 200 OK.

This data length is 893, and the API has told us that was the expected response length:

Content-Type: application/json; 
charset=utf-8
Content-Length: 893

{Connection: keep-alive
Date: Wed, 13 Jan 2021 12:05:47 GMT
ETag: "31ad9bb7b81f3667e9977cfd04ea586e"
Status: 200 OK
X-Robots-Tag: noindex
Cache-Control: must-revalidate, max-age=0, private
Referrer-Policy: no-referrer
X-Frame-Options: DENY
X-UA-Compatible: IE=Edge,chrome=1
X-Content-Type-Options: nosniff
Server: am/2
Vary: Origin
X-Cache: Miss from cloudfront
Via: 1.1 337b3ec803634031823bd56035e09183.cloudfront.net (CloudFront)
X-Amz-Cf-Pop: LHR62-C2
X-Amz-Cf-Id: k6FbVyTctn1x2COjk52CDfVaGN_jVJHioEqIsYdWSjtgzCEJ807v9A==
}

**Comment by mgoodfellow** [comment]
Investigating further, it seems this issue is sporadic on endpoints.

Refetching data a number of times will eventually cause full API responses to be returned, but this process can take many retries. 

As it stands I'm unsure if there is a broken API server in your cluster, or whether there is some aggressive caching on the edge which isn't caching full responses?

@rahul-sc  

This issue started at 11:15 UTC, and is currently ongoing.

**Comment by mgoodfellow** [comment]
Last observation is that from all the information I currently have, this only affects `/me` and `/users/{id}` endpoints

I'm not seeing truncated data elsewhere

**Comment by mgoodfellow** [comment]
Another example of a failed response - maybe these ray IDs will help you find the cause?

I notice this broken response has been cached in CloudFront, and now gets repeatedly returned from it.

`/users/875341459`

Connection: keep-alive
Date: Wed, 13 Jan 2021 12:37:13 GMT
Status: 200 OK
X-Robots-Tag: noindex
Cache-Control: public, max-age=600
Referrer-Policy: no-referrer
X-Frame-Options: DENY
X-UA-Compatible: IE=Edge,chrome=1
X-Content-Type-Options: nosniff
Server: am/2
Vary: Origin
X-Cache: Hit from cloudfront
Via: 1.1 a1a4fa2aa1a6ec4964511a9d2ab566d4.cloudfront.net (CloudFront)
X-Amz-Cf-Pop: LHR62-C2
X-Amz-Cf-Id: fKZkiRkLLWDm0mjCrzRZLM_JQKBXhAWsFFL3QqAPuk8nMwYs4GOM-w==
Age: 167

Content-Type: application/json; charset=utf-8
Content-Length: 1002

{"id":875341459,"kind":"user","permalink":"user-988815906","username":"Cheesy_Beats","last_modified":"2021-01-02T21:28:39Z","uri":"https://api.soundcloud.com/users/875341459","permalink_url":"https://soundcloud.com/user-988815906","avatar_url":"https://i1.sndcdn.com/avatars-NppMKiKgE7vIMPgQ-coDl1A-large.jpg","country":"United States","first_name":"","last_name":"","full_name":"","description":"My new song 'Photos' is now up, I hope you like it, I also have posted my album to my SoundCloud!\nAlso, go follow my friend Jessica she is also a Pop artist and needs more follows!\nhttps://soundcloud.com/jessiecmusic\n\nThanks For All the support, and remember to follow me on Spotify!","city":"Toledo","discogs_name":null,"myspace_name":null,"website":"https://grivashamp23.wixsite.com/cheesybeats","website_title":"Check out Cheesy_Beats' website!","track_count":12,"playlist_count":9,"online":false,"plan":"Free","public_favorites_count":212,"followers_count":65,"followings_count":111,"subscriptions

**Comment by mgoodfellow** [comment]
Here's a broken response (the original one which has built the cache):

Date: Wed, 13 Jan 2021 12:48:17 GMT
Status: 200 OK
X-Robots-Tag: noindex
Cache-Control: max-age=600, public
Referrer-Policy: no-referrer
X-Frame-Options: DENY
X-UA-Compatible: IE=Edge,chrome=1
X-Content-Type-Options: nosniff
Server: am/2
Vary: Origin
X-Cache: Miss from cloudfront
Via: 1.1 cd9356e27582317dbf5532faf4a88586.cloudfront.net (CloudFront)
X-Amz-Cf-Pop: LHR62-C2
X-Amz-Cf-Id: KXAQdw-txlThLmrWTpLMhHGTmfLE03_fMefp6dRZH2e8JfxOy4kaBw==

Content-Type: application/json; charset=utf-8
Content-Length: 1959

{"id":1365320,"kind":"user","permalink":"esotera","username":"Esotera","last_modified":"2020-11-17T16:37:37Z","uri":"https://api.soundcloud.com/users/1365320","permalink_url":"https://soundcloud.com/esotera","avatar_url":"https://i1.sndcdn.com/avatars-000324926371-kvhrgd-large.jpg","country":"Britain (UK)","first_name":"","last_name":"","full_name":"","description":"Born and bred Londoner  Esotera picked up his first record in the early 2000s and soon became hooked to the underground sounds of jungle, drum n bass, hardcore and acid house. Fast forward to 2019 and his sound is firmly in the house and techno camp, blending the deep with the slamming, the euphoric with the dark. \n\nEsotera released his first track after winning grand prize in a Beatport Remix contest, putting out a track on Rob Garza's (Thievery Corporation) label Magnetic Moon Records. The tumbling deep house remix beat hundreds of entries and received critical acclaim from a panel of judges at a live event in San Francisco. Since then he's released tracks on London label Flemcy Music, Berlin's Lost Crate and Serbian imprint Debuger among many others.\n\nHis productions have got a distinctive sound, often incorporating dreamy harmonies, driving basslines and intricate use of soundscapes and vocals. However his DJ sets are often harder and faster, with regular slots at London's infamous Jaded parties.\n\nAs a DJ, Esotera's extensive experience ensures he is in his element playing music from across the spectrum, from quality deep house at Ministry of Sound to fast, purist techno at Corsica  Studios.","city":"London","discogs_name":null,"myspace_name":null,"website":"https://audiu.net/users/esotera","website_title":"Audiu (Pro Feedback)","track_count":65,"playlist_count":7,"online":false,"plan":"Pro Plus","public_favorites_count":434,"followers_count":11630,"followings_count":740,"subscriptions":[{"product":{"id":"creator-pro-unlimited","name":"Pro Unlimi


This will now be cached for however long your cache is and make all calls to `/users/1365320` break

**Comment by mgoodfellow** [comment]
Here is another request using our primary client id from our live site, rather than our test site, and it seems that your cache is per-client id - which means you won't be able to reproduce from these reports:

Connection: keep-alive
Date: Wed, 13 Jan 2021 12:49:44 GMT
ETag: "4b1e5c68ea92945c03345f1bd199e798"
Status: 200 OK
X-Robots-Tag: noindex
Cache-Control: max-age=600, public
Referrer-Policy: no-referrer
X-Frame-Options: DENY
X-Content-Type-Options: nosniff
Server: am/2
Vary: Origin
X-Cache: Miss from cloudfront
Via: 1.1 c8af64e6cd4225d75ce8f5c40c654b89.cloudfront.net (CloudFront)
X-Amz-Cf-Pop: LHR62-C2
X-Amz-Cf-Id: 6YCAc_0WypFRv_rdzCPWsCL0wGvhv17vfLYUM_RAPJgotfHG146J9w==

Content-Type: application/json; charset=utf-8
Content-Length: 1992

{"id":1365320,"kind":"user","permalink":"esotera","username":"Esotera","last_modified":"2020/11/17 16:37:37 +0000","uri":"https://api.soundcloud.com/users/1365320","permalink_url":"https://soundcloud.com/esotera","avatar_url":"https://i1.sndcdn.com/avatars-000324926371-kvhrgd-large.jpg","country":"Britain (UK)","first_name":"","last_name":"","full_name":"","description":"Born and bred Londoner  Esotera picked up his first record in the early 2000s and soon became hooked to the underground sounds of jungle, drum n bass, hardcore and acid house. Fast forward to 2019 and his sound is firmly in the house and techno camp, blending the deep with the slamming, the euphoric with the dark. \n\nEsotera released his first track after winning grand prize in a Beatport Remix contest, putting out a track on Rob Garza's (Thievery Corporation) label Magnetic Moon Records. The tumbling deep house remix beat hundreds of entries and received critical acclaim from a panel of judges at a live event in San Francisco. Since then he's released tracks on London label Flemcy Music, Berlin's Lost Crate and Serbian imprint Debuger among many others.\n\nHis productions have got a distinctive sound, often incorporating dreamy harmonies, driving basslines and intricate use of soundscapes and vocals. However his DJ sets are often harder and faster, with regular slots at London's infamous Jaded parties.\n\nAs a DJ, Esotera's extensive experience ensures he is in his element playing music from across the spectrum, from quality deep house at Ministry of Sound to fast, purist techno at Corsica  Studios.","city":"London","discogs_name":null,"myspace_name":null,"website":"https://audiu.net/users/esotera","website_title":"Audiu (Pro Feedback)","track_count":65,"playlist_count":7,"online":false,"plan":"Pro Plus","public_favorites_count":434,"followers_count":11630,"followings_count":740,"subscriptions":[{"product":{"id":"creator-pro-unlimited","name":"Pro Unlimited"}}],"reposts_count":269}

**Comment by mgoodfellow** [comment]
So to summarize:

* We are getting truncated responses from the SoundCloud API as of 11:15 UTC - this is affecting a large number of calls
* When a request is truncated, it is aggressively cached, meaning that subsequent calls will also fail. I'm unsure of the expiry of this cache
* If you get a proper response, then that in turn is cached, and subsequent calls will succeed.

A best guess from an outside perspective is that there is a misbehaving API server - if you are unlucky enough to hit it, it's truncated response is cached for that call.

Hopefully these Cf-Ids will point towards a specific instance.

**Comment by mgoodfellow** [comment]
These truncation errors have only occurred as of today:

![image](https://user-images.githubusercontent.com/6501186/104464343-b9816b80-55aa-11eb-9de6-e48693d07816.png)

We just checked back on the log clusters and there are no occurances of data trunction in the last 30 days, until about 11:15 UTC today.

**Comment by mgoodfellow** [comment]
This issue is still ongoing - it only seems to affect calls where there is user data returned? If cached responses are ignored, then about 30% of all calls which contain user data fail with a truncated response.

**Comment by rahul-sc** [comment]
Hey, Mike. We're looking into this.

**Comment by mgoodfellow** [comment]
Hi @rahul-sc 

It appears to be fixed now - many thanks - we have not seen any more occurrences of these issues since ~10:50 UTC.

Thank you!

**Comment by rahul-sc** [comment]
Hey, Mike. We rolled back some internal changes. We will re-introduce the reverted changes but it is not intended to have any impact. If you see any issues, do continue to use this pass and tag me :)

Cheers
