### ISSUE TITLE
User playlist not returned

### ISSUE THREAD

**Issue by madalingavril** [soundcloud/api#130]
## Title: Cannot retrieve playlists for a user
Issue found of: September 1st, 2021

### Endpoint(s):
* `GET /users/{id}/playlists`

### Scope(s):
* None (application is not using authentication i.e., implicit flow)

### Steps to reproduce:
```bash
curl --request GET \
  --url 'https://api.soundcloud.com/users/189264588/playlists?client_id=123456'
```

### Expected behaviour:
A list of playlists as described at `https://developers.soundcloud.com/docs/api/reference#users`.

### Actual behaviour:
An empty json is returned even if the user has playlists available:
"{
collection: [ ],
next_href: null
}"
User has playlists:
https://api.soundcloud.com/users/55360164?client_id=123456
"playlist_count: 3,"

**Comment by dasha-kobzeva** [comment]
Hello @madalingavril,

please check our blog regarding the security changes: https://developers.soundcloud.com/blog/security-updates-api

You are trying to access the user's resources that require authentication. For this endpoint please follow the Authorisation code flow: https://developers.soundcloud.com/docs/api/guide#authentication

You can try it out in our Spec as well: https://developers.soundcloud.com/docs/api/explorer/open-api#/oauth/post_oauth2_token

**Comment by madalingavril** [comment]
Hello @dasha-kobzeva 

Thanks for watching on this.
![image](https://user-images.githubusercontent.com/16319194/133558216-2e9313b1-fd68-4453-adef-050537d6c36f.png)

I see there is no longer available to register an app.
How can we obtain the oauth2 token  in this circumstances?

**Comment by dasha-kobzeva** [comment]
You obtain a token for your existing app using the client_id and client_secret associated with it.
Do you have an existing app?

**Comment by madalingavril** [comment]
> You obtain a token for your existing app using the client_id and client_secret associated with it.
> Do you have an existing app?

No, I don't have an existing app. What can I do then to use Soundcloud API?

**Comment by dasha-kobzeva** [comment]
Unfortunately without the app you cannot use our API. I'm very sorry.

We will make an announcement whenever the registration is open.
