### ISSUE TITLE
Soundcloud Ruby client updated version not released?

### ISSUE THREAD

**Issue by gaelant** [soundcloud/api#135]
Hey Soundcloud!

I completely understand that you have decided to not maintain the Ruby library anymore.
I had just one question though. It seems someone from SC did the work of updating the gem with the recent security updates (gem version 0.3.5)[ commit found here](https://github.com/soundcloud/soundcloud-ruby/commit/b7e56c781da1be7d70ab32d1d9e073f4219f2b04).

The title of the commit is: Release v0.3.5

However, the gem version is still listed at v0.3.4. I just thought i'd point it out as if you install the gem, you will not get the v0.3.5 but the older version which has issues fixed by v0.3.5. Someone put the effort in so 🤷 

If you know this and still don't have the time to release it for whatever reason, all good. I come in peace, I just wanted to clarify this in the event that this wasn't known.

Thanks and have a great weekend!

**Comment by dasha-kobzeva** [comment]
hey @gaelant,
thank you for pointing it out. 

We have released a new version!
