### ISSUE TITLE
How to register for a new API key?

### ISSUE THREAD

**Issue by Subfader** [soundcloud/api#138]
I cannot find any info on how to register for a new API key (client_id and client_secret).

Am I dumb or have you really killed the API?

**Comment by dannyhpy** [comment]
Actually, https://docs.google.com/forms/d/e/1FAIpQLSfNxc82RJuzC0DnISat7n4H-G7IsPQIdaMpe202iiHZEoso9w/closedform

See https://github.com/soundcloud/api/issues/134

**Comment by dasha-kobzeva** [comment]
Please read our README: 
https://github.com/soundcloud/api#can-i-request-an-api-key-for-a-new-app
