### ISSUE TITLE
The /users/{userId}/tracks endpoint returns only single value

### ISSUE THREAD

**Issue by knyttl** [soundcloud/api#139]
## Title: Cannot retrieve all tracks for a user
Issue found of: September 20th, 2021

### Endpoint(s):
* `GET /users/{id}/tracks`

### Scope(s):
OAuth auth

### Steps to reproduce:
Calling following
```bash
curl -i -H "Authorization:OAuth {auth}" https://api.soundcloud.com/users/61815378/tracks
```
will return only list of a single track (id=1110843220). When you add `?limit=10`, it will return an empty list.

### Expected behaviour:
It should list tracks by given limit.

### Actual behaviour:
Only single track (or no track is returned). It worked until recently.

**Comment by dasha-kobzeva** [comment]
HI @knyttl,

thank you for reporting the issue. 
We are onto it and will try to resolve it ASAP. I will keep you posted

**Comment by knyttl** [comment]
Thanks for a quick response, appreciate it!

**Comment by dasha-kobzeva** [comment]
Hi, after some investigation I see that it is an issue with the pagination. 
We are aware of it, but with this particular user, it's extremely complex.

So what happens is that the limit and pagination works across all tracks, public and private. As you are not providing secret_token, you can only see public ones. The first 32 tracks of this user are private, so any limit until 33 won't return any return. As you can see requesting 33, 34, or 50 tracks will also give you only 1 track, because again in between public tracks there are many private ones. 

As a workaround I'd suggest using the next_href link for fetching the results further away or putting a bigger limit.

We will try to fix it ASAP, but it's a much bigger effort and might take some time. 
We are sorry you encountered it.

**Comment by knyttl** [comment]
>  As you are not providing secret_token

This is not enought for auth? `curl -i -H "Authorization:OAuth {auth}"`

> As you can see requesting 33, 34, or 50 tracks will also give you only 1 track

When I use the ?limit= parameter, I get EMPTY result, not 1 track.

**Comment by dasha-kobzeva** [comment]
what parameter do you provide for a limit value?

And access_token and secret_token are not the same. Access_token is for auth, secret_token is a specific token to access private tracks.

**Comment by knyttl** [comment]
> what parameter do you provide for a limit value?

`?limit={}`

> secret_token is a specific token to access private tracks.

Meaning I will never be able to access these as I am regular user?

Thanks!

**Comment by dasha-kobzeva** [comment]
Calling 
```
curl -X GET "https://api.soundcloud.com/users/61815378/tracks?limit=50"  \ 
-H  "accept: application/json; charset=utf-8"  \ 
-H  "Authorization: OAuth {TOKEN}
```

gives me 1 result. Could you try again, please?

**Comment by knyttl** [comment]
Okay, now it seems to work. When I request 100 results, I will truly get more results then 1. Thanks.

**Comment by dasha-kobzeva** [comment]
👍

**Comment by rahul-sc** [comment]
> is this closed because it is resolved?

it seemed like you confirmed that it works - is it not the case?

**Comment by knyttl** [comment]
I believe this should not be closed. It doesn't make sense to use `?limit=200` to fetch 12 tracks.

**Comment by a-straus** [comment]
Hi this seems to still be an issue:
(https://soundcloud.com/chloerobinsondj/tracks) has multiple public tracks

```
curl -X 'GET' \
  'https://api.soundcloud.com/users/2147061/tracks?access=playable&limit=2&linked_partitioning=true' \
  -H 'accept: application/json; charset=utf-8' \
  -H 'Authorization: **MY TOKEN'
```

Returns no tracks in the response.  Note the `&limit=2` in the query string
```
curl -X 'GET' \
  'https://api.soundcloud.com/users/2147061/tracks?access=playable&limit=3&linked_partitioning=true' \
  -H 'accept: application/json; charset=utf-8' \
  -H 'Authorization: OAuth **MY TOKEN**'
  ```

This does return _one_ song.  Note that there's `&limit=3` in the query string
It is not until i set the limit to 10 that I get another track

@rahul-sc 
@bbeesley
