### ISSUE TITLE
Auryo - 403 Forbidden

### ISSUE THREAD

**Issue by Superjo149** [soundcloud/api#14]
## Title: 403 Forbidden
Issue found on: September 11th, 2020

### Endpoint(s):
* All Soundcloud api-v2 private endpoints

### Scope(s):
* None (application is not using authentication i.e., implicit flow)

### Steps to reproduce:
```bash
curl --request GET \
  --url 'https://api-v2.soundcloud.com/users/1489799?oauth_token=OAUTH_TOKEN'
```

### Expected behaviour:
Should fetch the data correctly.

### Actual behaviour:
First of all, I am really glad this exists now, and that more resources are being invested in enhancing the API, I have been working and figuring out your guys's API for a while now, and it was really time it got some love.

With that said, this is more so a request than a bug, request, or issue. I am the creator of https://github.com/Superjo149/auryo. I have been working on Auryo off and on for several years now. At some point I decided to jump on your private APIs considering not much was provided on the public ones. I knew this could happen, but I noticed as of recently, it isn't possible anymore to access the private APIs using oauth tokens generated from Auryo's App Id. This is to be expected, but this breaks the whole application. I was just working on a complete overhaul of the codebase which has been growing with me since starting the project without much experience in Electron or React. As of late, I have spent countless hours on this to make it more future-proof and prepare it for cool features, so it would be a shame if Auryo stops working now. Is there a possibility for me to continue using this API or work together so that Auryo can continue to exist?

**Comment by rahul-sc** [comment]
Hello. Thanks for reaching out here. 

api-v2 is not authorized for 3rd party apps, as you already have mentioned. 

You should be using api.soundcloud.com like the following 

```bash
curl --request GET \
  --url 'https://api.soundcloud.com/users/1489799?client_id=CLIENT_ID'
  ```

The updated reference on the endpoint can be found here
https://developers.soundcloud.com/docs/api/explorer/open-api

**Comment by Superjo149** [comment]
Hi @rahul-sc,

Yes, I am aware. But I really would like to continue working on Auryo, so my question was if it is possible to arrange something. Otherwise I know I don't have to put any more effort into it.

**Comment by rahul-sc** [comment]
Closing this since we've connected on this already.
