### ISSUE TITLE
Error message : Failed to load resource: the server responded with a status of 401 (Unauthorized)

### ISSUE THREAD

**Issue by mike-po** [soundcloud/api#143]
we have an Issue with API from ios APP and website
I guess it's due to Soundcloud last update. Our user getting a bad experience cz all request are down. Need help please

**Comment by dasha-kobzeva** [comment]
@mike-po,
in order for us to help you, we need to have more information regarding the issue. Would you please fill in the request template with all the relevant information?

From the 401 error I  can assume you have not implemented the new security changes:
https://developers.soundcloud.com/blog/security-updates-api

Some details on auth: 
https://developers.soundcloud.com/docs/api/guide#authentication

**Comment by mike-po** [comment]
Hi @dasha-kobzeva, Thank you for replying.

I do not have dev skills so I was trying to find out where my Wordpress theme is doing the request to Soundcloud API. Then I found this :

` window.SC = SC.Helper.merge(SC || {}, {
        _version: "1.1.5",
        _baseUrl: "//connect.soundcloud.com",
        options: {
            site: "soundcloud.com",
            baseUrl: "//connect.soundcloud.com"
        },
        connectCallbacks: {},
        _popupWindow: void 0,
        initialize: function(options) {
            var key, value, _base;
            if (options == null) {
                options = {}
            }
            this.accessToken(options["access_token"]);
            for (key in options) {
                if (!__hasProp.call(options, key))
                    continue;
                value = options[key];
                this.options[key] = value
            }
            (_base = this.options).flashXHR || (_base.flashXHR = (new XMLHttpRequest).withCredentials === void 0);
            return this
        },
        hostname: function(subdomain) {
            var str;
            str = "";
            if (subdomain != null) {
                str += subdomain + "."
            }
            str += this.options.site;
            return str
        }
    });
    window.SC = SC.Helper.merge(SC || {}, {
        _apiRequest: function(method, path, query, callback) {
            var data, uri;
            if (callback == null) {
                callback = query;
                query = void 0
            }
            query || (query = {});
            uri = SC.prepareRequestURI(path, query);
            uri.query.format = "json";
            if (SC.options.flashXHR) {
                SC.Helper.setFlashStatusCodeMaps(uri.query)
            } else {
                uri.query["_status_code_map[302]"] = 200
            }
            if (method === "PUT" || method === "DELETE") {
                uri.query._method = method;
                method = "POST"
            }
            if (method !== "GET") {
                data = uri.encodeParams(uri.query);
                uri.query = {}
            }
            return this._request(method, uri, "application/x-www-form-urlencoded", data, function(responseText, xhr) {
                var response;
                response = SC.Helper.responseHandler(responseText, xhr);
                if (response.json && response.json.status === "302 - Found") {
                    return SC._apiRequest("GET", response.json.location, callback)
                } else {
                    return callback(response.json, response.error)
                }
            })
        },
        _request: function(method, uri, contentType, data, callback) {
            if (SC.options.flashXHR) {
                return this._flashRequest(method, uri, contentType, data, callback)
            } else {
                return this._xhrRequest(method, uri, contentType, data, callback)
            }
        },
        _xhrRequest: function(method, uri, contentType, data, callback) {
            var request;
            request = new XMLHttpRequest;
            request.open(method, uri.toString(), true);
            request.setRequestHeader("Content-Type", contentType);
            request.onreadystatechange = function(e) {
                if (e.target.readyState === 4) {
                    return callback(e.target.responseText, e.target)
                }
            }
            ;
            return request.send(data)`

This is from here I got the message 'Failed to load resource: the server responded with a status of 401 (Unauthorized)'

**Comment by mike-po** [comment]
I caught the code with 

`# authenticate your app through SC Connect

$ curl "https://api.soundcloud.com/connect?client_id=YOUR_CLIENT_ID&redirect_uri=YOUR_REDIRECT_URI&response_type=code"`

Then I tried to get access token

`# obtain the access token

$ curl -X POST "https://api.soundcloud.com/oauth2/token" \
     -H  "accept: application/json; charset=utf-8" \
     -H  "Content-Type: application/x-www-form-urlencoded" \
     --data-urlencode "grant_type=authorization_code" \
     --data-urlencode "client_id=YOUR_CLIENT_ID" \
     --data-urlencode "client_secret=YOUR_CLIENT_SECRET" \
     --data-urlencode "redirect_uri=YOUR_REDIRECT_URI" \
     --data-urlencode "code=YOUR_CODE"` 

But now I got error message back 

`{"code":400,"message":"invalid_grant","link":"https://developers.soundcloud.com/docs/api/explorer/open-api","status":"400 - Bad Request","errors":[{"error_message":"invalid_grant"}],"error":null,"error_code":"invalid_grant"}`

Also my REDIRECT_URI is emptying for my application registered and cannot be modified. Reading this : If the user approves your authorization request, they will be sent to the redirect_uri you specified when registering your app. Can it be an issue ?

**Comment by mike-po** [comment]
Finally got access token with this code

`curl --request POST \
--url https://api.soundcloud.com/oauth2/token \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data client_id=CLIENT_ID \
--data client_secret=CLIENT_SECRET \
--data grant_type=client_credentials`

**Comment by dasha-kobzeva** [comment]
> Also my REDIRECT_URI is emptying for my application registered and cannot be modified. Reading this : If the user approves your authorization request, they will be sent to the redirect_uri you specified when registering your app. Can it be an issue ?

yes, for authorization_code flow the redirect has to be set up and match, that's what causing the error.
You can update it by sending a request to our support team. Details are mentioned in README.

**Comment by mike-po** [comment]
Hello @dasha-kobzeva, we tried again and it's not better even with redirect_uri set up.  

when we go with this 

`curl --request POST \ --url https://api.soundcloud.com/oauth2/token \ --header 'Content-Type: application/x-www-form-urlencoded' \ --data client_id=CLIENT_ID \ --data client_secret=CLIENT_SECRET \ --data grant_type=client_credentials `

we obtain code 

then we got a 401 right after this  

```
curl "https://api.soundcloud.com/me" \
       -H "accept: application/json; charset=utf-8" \
       -H "Authorization: OAuth 3-134099-45856931-iM1hnfmhaH7tePw"

```
same with code getting from web http application.

We tried also with this code

`$ curl -X POST "https://api.soundcloud.com/oauth2/token" \
     -H  "accept: application/json; charset=utf-8" \
     -H  "Content-Type: application/x-www-form-urlencoded" \
     --data-urlencode "grant_type=authorization_code" \
     --data-urlencode "client_id=YOUR_CLIENT_ID" \
     --data-urlencode "client_secret=YOUR_CLIENT_SECRET" \
     --data-urlencode "redirect_uri=YOUR_REDIRECT_URI" \
     --data-urlencode "code=YOUR_CODE"`

But getting no response. So where is the issue ?
