### ISSUE TITLE
Get public resources with not registered app

### ISSUE THREAD

**Issue by Iknel** [soundcloud/api#144]
Hi, 

I need to get public resources for my app, it used to work fine but after the the security update, I understand that the Authorization header is required, but i need to get my app registered to use the client credentials flow, and my app isn't registered. Is there some way I could get my app registerred or get my client credential to keep my app going?

Thanks!

**Comment by rahulrumalla** [comment]
How were you using the api before without your own app? 🤔

**Comment by Iknel** [comment]
The client_id used to be enough to get public resources. I got it from one of the requests while loading a track from SoundCloud and it worked, it was the only way I knew to get a client_id.

**Comment by rahulrumalla** [comment]
Can you share the following please?

- what client_id you used before
- where is your app hosted
- your SoundCloud profile

**Comment by Iknel** [comment]
web: https://www.b4bookings.com/
SoundCloud profile: https://soundcloud.com/b4bookings
I thought I wasn't suposed to share any client_id

**Comment by dasha-kobzeva** [comment]
@Iknel,

is it correct to assume client_id: 389eb47493cb67a44c652689af9494fe doesn't belong to you?

**Comment by Iknel** [comment]
Yes it may not belong to that account, that specific client_id it was added before I got into the project
