### ISSUE TITLE
Receiving 422 - Unprocessable Entity error since yesterday

### ISSUE THREAD

**Issue by neil-amp** [soundcloud/api#154]
Hi, has something changed with the API as of yesterday? We started getting "422 - Unprocessable Entity" errors for all requests.

When creating a playlist we get:

`{"code":422,"message":"Could not parse JSON request body.","link":"https://developers.soundcloud.com/docs/api/explorer/open-api","status":"422 - Unprocessable Entity","errors":[{"error_message":"Could not parse JSON request body."}],"error":null}`

I have fixed this by sending a JSON request in the post instead, but then I can't seem to find a way to upload the artwork to use with the playlist.

So I guess two questions:

1. Is it no longer possible to use multipart/form-data requests?
2. If not, how can we add the artwork_data when creating a playlist (I tried adding artwork_url to the JSON request but that didn't seem to work - and it's not listed in the API docs as an option)

Also similar problem when uploading tracks now:

` {"code":422,"message":"unable to process provided asset_data","link":"https://developers.soundcloud.com/docs/api/explorer/open-api","status":"422 - Unprocessable Entity","errors":[{"error_message":"unable to process provided asset_data"}],"error":null}`

Was all working find until some time yesterday afternoon.

Thanks in advance!

**Comment by gouthampradhan** [comment]
Hi @neil-amp do you have a sample request to which you get this error?

**Comment by gouthampradhan** [comment]
> Uploading a new playlist with artwork works fine using multipart/form-data like it used to now. I'm afraid we don't have the option to update the artwork on an existing playlist in the code to test that.

Yes, I meant upload. Thanks for letting me know. Will close this issue for now. If you face this problem again then please feel free to open this
