### ISSUE TITLE
All requests 401

### ISSUE THREAD

**Issue by Winspear** [soundcloud/api#156]
Hi there,
I previously had api code (post security update) that worked to retrieve all tracks associated with our user. I was using a forked python connector, which I understand is now no longer supported. After obtaining an authorisation code, I cannot perform any request without receiving a 401.

In order to attempt to debug the problem, I have defaulted to your documentation and curl requests in order to try to make a succesful request.

I am following the steps to generate an access token as follows:
```
curl "https://api.soundcloud.com/connect?client_id=YOUR_CLIENT_ID&redirect_uri=YOUR_REDIRECT_URI&response_type=code"
```

I can then extract the code after approving the authorisation request.

I then call:
```
curl -X POST "https://api.soundcloud.com/oauth2/token" \
     -H  "accept: application/json; charset=utf-8" \
     -H  "Content-Type: application/x-www-form-urlencoded" \
     --data-urlencode "grant_type=authorization_code" \
     --data-urlencode "client_id=YOUR_CLIENT_ID" \
     --data-urlencode "client_secret=YOUR_CLIENT_SECRET" \
     --data-urlencode "redirect_uri=YOUR_REDIRECT_URI" \
     --data-urlencode "code=YOUR_CODE"
```

but am receving the following response:
{"code":401,"message":"invalid_grant","link":"https://developers.soundcloud.com/docs/api/explorer/open-api","status":"401 - Unauthorized","errors":[{"error_message":"invalid_grant"}],"error":null,"error_code":"invalid_grant"}

I can actually get a bit further in python and am able to call client.exchange_token to get a token object (with a refresh token value, etc). However, when I try to use this token object in any call, eg:

```
curl -X GET "https://api.soundcloud.com/me" -H  "accept: application/json; charset=utf-8" -H  "Authorization: Oauth <code>"
```
I obtain 
```
{"code":401,"message":"","link":"https://developers.soundcloud.com/docs/api/explorer/open-api","status":"401 - Unauthorized","errors":[],"error":null}
```

Is it possible to clarify what is happening for me please?

**Comment by dasha-kobzeva** [comment]
Hello @Winspear,
could you please share your SC user, so we can try to reproduce the issue?

Also, do you have a redirect uri setup from your application? The lack of it might be causing an issue.

**Comment by dasha-kobzeva** [comment]
@Winspear,

this doesn't look like an access_token. not the right format.

> The token I have provided here is that I have most recently obtained by exchanging a code. 
Have you obtained it by calling `/oauth2/token` ?

The response should look smth like:
```
{
  "access_token": "2-273545-721957945-XXX...",
  "expires_in": 3599,
  "refresh_token": "WppoXXXXX",
  "scope": "",
  "token_type": "bearer"
}
```

Is there a chance you extracted `refresh_token` from the response and not `access_token`?
