### ISSUE TITLE
401 error for stream_url links

### ISSUE THREAD

**Issue by mayallst** [soundcloud/api#157]
Using the stream_url for public tracks returned in a search, attempting to play the link in my own player in the last couple of days now returns a 401 error:
"A request must contain the Authorization header. For details please refer to https://developers.soundcloud.com/blog/security-updates-api"

Even if I apply the Oauth access token in the authorisation header (same as used for track search which still works) I still get the same error. And the Streaming Tracks documentation doesn't make any mention of needing to use an authorisation header. So what is the correct way to stream a link now?

**Comment by dasha-kobzeva** [comment]
Hello @mayallst, @annamalaicoderays,

To access `/stream` endpoint you must use the logged-in user token as it is not a public resource. It is acquired through Soundcloud connect + authorization_code flow.

In your case, I would suggest calling this endpoint: https://developers.soundcloud.com/docs/api/explorer/open-api#/tracks/get_tracks__track_id__streams.
That way providing the same means of auth as you do for `/search` should be sufficient.
