### ISSUE TITLE
Feature Request: Liked Playlists

### ISSUE THREAD

**Issue by obrhoff** [soundcloud/api#16]
## Feature Request: Add ID's Endpoint

The Endpoint `/users/{user_id}/likes/tracks` seems to be available but `/users/{user_id}/likes/playlists` not. 

### Endpoint(s):
* `GET /users/{user_id}/likes/playlists`

**Comment by rahul-sc** [comment]
Thanks for filing this. We're aware of this and this is a good enhancement for us to add.

**Comment by obrhoff** [comment]
Any update regarding this feature? Right now you can like/dislike playlists not not access them at all.

**Comment by dasha-kobzeva** [comment]
Hi @obrhoff,
the feature was added to API.
You can find the details in our [API Explorer](https://developers.soundcloud.com/docs/api/explorer/open-api#/me/get_me_likes_playlists).

We also have a new section [API Releases](https://github.com/soundcloud/api/releases) where you can track all recent changes.
Best,
