### ISSUE TITLE
401 /resolve public resource id

### ISSUE THREAD

**Issue by ginoemiliozzi** [soundcloud/api#161]
## Title: Cannot resolve public resource id - Unauthorized
Issue found of: October 26th, 2021

### Endpoint(s):
* `GET /resolve`

### Scope(s):
* None (application is not using authentication i.e., implicit flow)

### Steps to reproduce:
```bash
curl -X GET "https://api.soundcloud.com/resolve?url=https%3A%2F%2Fsoundcloud.com%2Fnbgmusicyt%2Fedm-meme-machine" -H  "accept: */*"
```

### Expected behaviour:
Status code 200 and I get back the resource id to use in consecutive request

### Actual behaviour:
401 Unauthorized

### More info:
I tried authenticating before doing this request but in that case the API ask me for a redirect_uri when the documentation says it's optional. Why is it necessary to get a user permission via redirect to login when I just want to get the resource id of a public song?

**Comment by ginoemiliozzi** [comment]
Thanks @dasha-kobzeva, I was able to have it working using the client_credentials auth flow.

**Comment by jakebonin** [comment]
API ceased to work here too. No changes to our code. Any ideas?

**Comment by rahul-sc** [comment]
Hey @ginoemiliozzi we'll close this issue per your resolution confirmation. 

@jakebonin please see readme, blog and other closed issues. If it doesn't point you to a solution, feel free to open a new ticket with detailed information
