### ISSUE TITLE
Download url response empty

### ISSUE THREAD

**Issue by aproni34f** [soundcloud/api#163]
I am trying to retrieve download url for tracks that are downloadable and do contain download url. And the response is empty. This track id ( 488143566 ) has download url. When I request a stream url (instead of download url) it works fine.

Example:

     `$url = "https://api.soundcloud.com/tracks/".$track_id."/download";

        $curl = curl_init($url);
        curl_setopt($curl, CURLOPT_URL, $url);
        curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);

        $headers = array(
            "accept: application/json; charset=utf-8",
            "Authorization: OAuth ".$access_token,
        );

        curl_setopt($curl, CURLOPT_HTTPHEADER, $headers);

        $response = curl_exec($curl);
        $err = curl_error($curl);

        curl_close($curl);

        if ($err) {
          echo "cURL Error #:" . $err;
        } else {
            echo json_encode($response);
        }`

**Comment by dasha-kobzeva** [comment]
Hi, thank you for filing the issue.
We will look into it and try to get back to you ASAP.

**Comment by dasha-kobzeva** [comment]
Hey @aproni34f,

The response for `/download` is actually a redirect, so you don't see anything because the URL for download is in the header 'Location'. Please treat the call as a redirect and it should work.

**Comment by aproni34f** [comment]
I have a button where user can initiate download on click so I need to get download url so I can place it in the href attribute: https://www.w3schools.com/tags/att_a_download.asp  . Its not possible to get actual download url like its possible to get stream url?    If getting download url gives redirect does this mean its not possible to use it as such and I need some kind of php solution for download?

**Comment by dasha-kobzeva** [comment]
For `/stream` you get a JSON response back with a `url`. For `/download` you do not get JSON response, but rather redirect. You need to catch it and call that location header to actually retrieve the file. Im sure there is PHP solution for such calls.

**Comment by dasha-kobzeva** [comment]
You can set this option to allow following the redirect:

```
//Tell cURL that it should follow any redirects.
curl_setopt($ch, CURLOPT_FOLLOWLOCATION, true);
```

Doc: https://www.php.net/manual/en/function.curl-setopt.php

**Comment by aproni34f** [comment]
I have added this to my code but now nothing happens, no response when I run the code above. I can only run this code after user clicks a button. And I dont want to redirect to another page, I just want to download a file. Using previous api this was easy because you could retrieve a download url.

**Comment by dasha-kobzeva** [comment]
the API spec didn't change, you are just required to authenticate differently.

Redirecting to a new page is also not required, you can follow the URL on a server-side and return a file to a user.

I would advise checking the examples for PHP as this is a common type of response.
