### ISSUE TITLE
Cursor and limit is broken on /me/activities

### ISSUE THREAD

**Issue by obrhoff** [soundcloud/api#165]
## Cursor and limit is broken on /me/activities
Issue found of: November 17, 2021

### Endpoint(s):
* `GET /me/activities`

### Steps to reproduce:
```bash
curl --request GET \
  --url 'https://api.soundcloud.com/me/activities?limit=10'
```

### Expected behaviour:
The href value should have a valid cursor parameter. Also the limit is ignored on this request and the endpoint only returns 1 item, instead of 10.

### Actual behaviour:
the next href parameter is `https://api.soundcloud.com/me/activities?limit=10&cursor=10` Calling this url will lead to a `Cursor is not a valid UUID`.

**Comment by knyttl** [comment]
This is the same issue as here: https://github.com/soundcloud/api/issues/139

**Comment by obrhoff** [comment]
Not entirely. In this case the whole linking partition feature is broken.

**Comment by thesubdelta** [comment]
@obrhoff Seems like the bug here is the api is returning the `offset` as `cursor` instead.

did you try `https://api.soundcloud.com/me/activities?limit=10&offset=10` to get the next page? 

A proper cursor would be something like this: `1637775162857218`
See `GET /tracks/{trackId}/favoriters` for a proper `cursor` response

**Comment by obrhoff** [comment]
It's true. If I replace the `cursor` with `offset` it generated a valid URL. I'm not sure what happened here but 10 days ago it worked without a problem.

**Comment by 0xf4b1** [comment]
Replacing `cursor` with `offset` does not work for me, the query succeeds but the `offset` has no effect and the first results are returned again.

**Comment by dasha-kobzeva** [comment]
Hello, 
thank you for reporting the issue. We will try to look into it ASAP and get back to you.

**Comment by obrhoff** [comment]
Issue seems to be resolved. Thanks! :)
