### ISSUE TITLE
Can't use the API without authentication

### ISSUE THREAD

**Issue by dima-malkov** [soundcloud/api#168]
Hello. Sorry if this is the wrong place for my question.

Is it now possible to use the API without registering the application? There is no way to register an app right now, and it is unknown when it will appear. When trying to access public tracks, I always get a 401/403 response. I need access via JavaScript.

**Comment by dasha-kobzeva** [comment]
Hi @dima-malkov,

Unfortunately, without an app, there is no way to use the API at the moment. 
Registration is closed for the time being, and we can only ask you to wait until it is open again.

We apologise for the inconvenience
