### ISSUE TITLE
API Terms - Displaying multiple users’ content on a single account

### ISSUE THREAD

**Issue by alexweinstein** [soundcloud/api#17]
Not a bug, but a clarification on API Terms.

[Composerly](https://composerly.com) wraps SoundCloud accounts in a searchable UI, turning them into production music libraries. Users have been asking if they can combine accounts with other SC users. I’ve always said no, and decided not to develop this feature since your API terms specifically say:
> _Apps are not permitted to store Personal Data or User Content from **multiple users** in a single account. Each user must be able to authenticate and upload User Content from his/her own account._

But I thought I would ask. Our use case for us would be something like this:

1. User _Adam_ has a SoundCloud/Composerly account - displays his playlists: _Rock, Punk, Heavy Metal._
2. User _Jennifer_ has a SoundCloud/Composerly account - displays her playlists: _Classical, Folk, Cinematic_
3. _Adam_ invites _Jennifer_ to join his Composerly page.
4. _Jennifer_ authorizes with SC and accepts his invitation. Now _Adam’s_ Composerly account can display playlists: _Rock, Punk, Heavy Metal, Classical, Folk, Cinematic_

Music libraries with multiple composers is really common. And this would save a huge amount of time by not having to re-upload and re-tag all the tracks to a single account. Also, in the above example, this would keep 2 active SoundCloud customers as opposed to just one.

**Comment by rahul-sc** [comment]
Hi, @alexweinstein I've done some research to be sure, but this is not a use case that we're currently supporting, unfortunately.

**Comment by alexweinstein** [comment]
Got it. Thank you for looking into it. On Mon, Jan 25, 2021 at 5:07 AM,             Rahul <notifications@github.com> wrote:
Hi, @alexweinstein I've done some research to be sure, but this is not a use case that we're currently supporting, unfortunately.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://tr.cloudmagic.com/h/v6/link-track/1.0/1611577958612988-081df514-dd64-1586-fd9c-fa6bd3b458ae/1611577922/3e554880044c67a4f5f4420e219ee4d4/7ae4dec1f54bbf4c9be93a5c466401c8/ae18e60bdab461cc0886c5cc3f563e55?redirect_uri=https://github.com/soundcloud/api/issues/17#issuecomment-766703691",
"url": "https://tr.cloudmagic.com/h/v6/link-track/1.0/1611577958612988-081df514-dd64-1586-fd9c-fa6bd3b458ae/1611577922/3e554880044c67a4f5f4420e219ee4d4/7ae4dec1f54bbf4c9be93a5c466401c8/ae18e60bdab461cc0886c5cc3f563e55?redirect_uri=https://github.com/soundcloud/api/issues/17#issuecomment-766703691",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
