### ISSUE TITLE
Redirect_URI https redirection

### ISSUE THREAD

**Issue by LouisBelpalme** [soundcloud/api#171]
Hi, 

I contact you for a trouble with the redirection automatic on the redirect_uri field, indeed i want that my redirect_uri will be contributed with the "https", but the customer service don't contributed the redirect_uri with the https since the redirect_uri has a redirect with https.

Is it possible to contribute the redirect_uri with the https ? like this : https://www.mywebsite.com/callback ? 

Thank you,

Louis

**Comment by dasha-kobzeva** [comment]
Hello @LouisBelpalme,

I could not fully understand your question, but if you want to update the redirect_uri, our customer service should do it. Have you provided them with a full path and it was not updated correctly?

**Comment by LouisBelpalme** [comment]
Hello @dasha-kobzeva Yes sure, i have send to the customer service an url with the "https" but on the settings, i have only the domain without the https.

But i need to have the https on the redirect uri.

**Comment by dasha-kobzeva** [comment]
Do you still have the ticket number by any chance of your inquiry ?

**Comment by dasha-kobzeva** [comment]
And if you could also send me your SC user, please

**Comment by LouisBelpalme** [comment]
Sure my ticket number is : 455, and my account name is operadeparis

**Comment by dasha-kobzeva** [comment]
I can see that the redirect_uri for your app opera-de-paris is set up with the HTTPS part.

**Comment by LouisBelpalme** [comment]
Not in my side : 

![Screenshot 2021-12-07 at 17 02 25](https://user-images.githubusercontent.com/17848718/145063615-17832fd5-ff50-40bd-80f0-458237ea3a56.jpg)

**Comment by dasha-kobzeva** [comment]
maybe it's just the rendering of the page. Was the authorization process unsuccessful?

**Comment by LouisBelpalme** [comment]
here the error : 

![Screenshot 2021-12-07 at 17 19 05](https://user-images.githubusercontent.com/17848718/145066368-f57b8f92-acf4-482b-be1a-d221e484b4fa.jpg)

**Comment by dasha-kobzeva** [comment]
I deleted your comment as you should not share redirect. 
But you are not providing the full path to redirect_uri, HTTPS part has to be present as well. That's why the mismatch, the strings have to be 100% equal.

**Comment by LouisBelpalme** [comment]
Great it's work ! Sorry 👍

**Comment by dasha-kobzeva** [comment]
👍  Glad we could resolve it. I will close the issue.
