### ISSUE TITLE
How long is a refresh_token good for?

### ISSUE THREAD

**Issue by endquote** [soundcloud/api#173]
I've updated my auth flow to use the new token APIs, including refreshing tokens. For debugging, I can simulate that tokens expire after 60s, and refreshing them works fine.

My logic is that whenever I make an API call, I check if the token is expired. If it is I refresh it and them make the API call.

However I'm finding that if I make API calls less frequently than every hour, I'm not able to refresh the token. I get a 401 error when I try.

Do I have to renew the token every hour, even if I don't intend to call the API that often?

**Comment by dasha-kobzeva** [comment]
Hello @endquote,

When you request the token, the response contains the expiration time which is 1 hour.  After 1 hour the token expires and has to be refreshed. You should be able to refresh the token even after 2 hours have passed, as the refresh token does not expire. Yet it can only be used one time, so if you try to refresh a token multiple times you get 401.

Is there way your logic for refresh is reusing old tokens?

**Comment by endquote** [comment]
I'm pretty sure my logic was not reusing refresh tokens, but was just using them after some time had passed. I can check again. In the meantime I've changed my app to just refresh before an hour has passed even if it doesn't really need to, and that's worked ok.

Looking at my previous code it seems like I was trying to send an `Authorization: Oauth [token]` header in the `refresh_token` call. The token in that header would have been expired, but I think I was getting errors if I didn't include it.

In my new code I am also including it, but it's not expired, and it works ok.

Should any additional headers be included in a `refresh_token` call?

**Comment by dasha-kobzeva** [comment]
When requesting a token `Authorization: Oauth [token]` header should not be provided, as if a token is expired the request will fail even before the refresh

**Comment by endquote** [comment]
I believe the issue was that my request didn’t include a redirect_uri. This is not included in the example [in the API guide](https://developers.soundcloud.com/docs/api/guide#refreshing-tokens) but it does appear when testing in [the API explorer](https://developers.soundcloud.com/docs/api/explorer/open-api#/oauth/post_oauth2_token).

I was also sending data as json rather than form-urlencoded, so I changed that too.

It seems to work now, however it’s strange that it worked before those changes, just inconsistently.

**Comment by dasha-kobzeva** [comment]
@endquote glad to hear it's resolved. 

The redirect_uri is not required for refresh_token flow, there is a mistake in the reference.
The JSON format might have caused the issue.

As we were not provided with an example of a request you are making it's hard to say what went wrong.
