### ISSUE TITLE
Promise finally gets overwritten

### ISSUE THREAD

**Issue by nextendwebgabor** [soundcloud/api#177]
## Title: Promise finally gets overwritten
Issue found of: January 24th, 2022

### Steps to reproduce:
Run this JavaScript code on a simple website:
`Promise.all([console.log('test')]).finally();`
It has a correct result. Now insert your JavaScript file into that website:
`<script src="https://connect.soundcloud.com/sdk/sdk-3.3.2.js"></script>`
and run the code again.

### Expected behaviour:
The code should still run correctly.

### Actual behaviour:
Javascript error happens:
Uncaught TypeError: Promise.all(...).finally is not a function

**Comment by dasha-kobzeva** [comment]
Hello @nextendwebgabor,

We have deprecated the JS SDK and are not maintaining it any longer. Unfortunately, we won't be able to look into this issue. 

We highly recommend you to use the API directly. If it is not an option the JS SDK is a public repo (https://github.com/soundcloud/soundcloud-javascript), and we are more than happy if you want to contribute to it, or even maintain it.

Best,
