### ISSUE TITLE
Cannot post track using documented CURL method

### ISSUE THREAD

**Issue by Winspear** [soundcloud/api#178]
Issue found of: january 25th, 2022

### Endpoint(s):
* POST 'https://api.soundcloud.com/tracks'

I am using the curl request documented here: https://developers.soundcloud.com/docs#uploading

```
curl -X POST "https://api.soundcloud.com/tracks" \
       -H  "accept: application/json; charset=utf-8" \
       -H "Authorization: OAuth ACCESS_TOKEN" \
       -H  "Content-Type: multipart/form-data" \
       -F "track[title]=YOUR_TITLE" \
       -F "track[asset_data]=PATH_TO_A_FILE"
```

The file I am attempting to upload is a 435mb wav file - I understand from your documentation that only files under 500mb are allowed, and thus my understanding is this should be a valid upload
### Expected behaviour:
The track is uploaded succesfully

### Actual behaviour:
I receive a 200 response, and a track is created on my soundcloud profile. However, the length is 0:00 and greyed out text showing that the track is processing is visible. The track processing never completes, I have waited 12 hours.

Do you have any idea why this might be happening? Are there perhaps undocumented stipulations on what can and cannot be uploaded?

**Comment by dasha-kobzeva** [comment]
Hello,
could you please share you SoundCloud user name so we can check what happened?

**Comment by Winspear** [comment]
sc user name is "platform" - I have since deleted the track; if you need to see the processing track, I am happy to re-upload, just let me know!

**Comment by dasha-kobzeva** [comment]
Do you mean this profile? https://soundcloud.com/platform
Would be great if you can upload it again, otherwise I cannot see much about it

**Comment by Winspear** [comment]
Yes Dasha that is correct.
I have reuploaded the file. You can see it here 

https://soundcloud.com/platform/test

I have made it private for now - if you require it to be public please let me know

**Comment by dasha-kobzeva** [comment]
Thank you!
I can see that the upload of the audio file failed, need some time to dig in. Usually, it happens if your request is not attaching the file properly.
Have you had similar issues with upload before? With WAV files?

**Comment by Winspear** [comment]
This is the first time I am attempting to use the tracks endpoint - on the offchance my path was incorrect, I have tried a second test at https://soundcloud.com/platform/test2 from the directory where the file can be found. At present it looks like this too is failing, but it was worth a try!

**Comment by dasha-kobzeva** [comment]
Could you share an exact request you are trying? (excluding any auth details)

**Comment by Winspear** [comment]
```
curl -X POST "https://api.soundcloud.com/tracks" \
       -H  "accept: application/json; charset=utf-8" \
       -H "Authorization: OAuth 2-273545-752705-XXXXXXXXXX" \
       -H  "Content-Type: multipart/form-data" \
       -F "track[title]=TEST2" \
       -F "track[asset_data]=roskas-45-min-mix_audio.wav"
```

This is being called directly from the directory where the file in question resides

**Comment by Winspear** [comment]
response is:
```
{"kind":"track","id":1203977743,"created_at":"2022/01/26 11:54:39 +0000","duration":0,"commentable":true,"comment_count":0,"sharing":"public","tag_list":"","streamable":true,"embeddable_by":"all","purchase_url":null,"purchase_title":null,"genre":null,"title":"TEST2","description":null,"label_name":null,"release":null,"key_signature":null,"isrc":null,"bpm":null,"release_year":null,"release_month":null,"release_day":null,"license":"all-rights-reserved","uri":"https://api.soundcloud.com/tracks/1203977743","user":{"avatar_url":"https://i1.sndcdn.com/avatars-dg8DTxkybhLjzjo7-yyV0Og-large.jpg","id":752705,"kind":"user","permalink_url":"https://soundcloud.com/platform","uri":"https://api.soundcloud.com/users/752705","username":"Boiler Room","permalink":"platform","created_at":"2010/03/19 14:19:30 +0000","last_modified":"2022/01/13 18:11:24 +0000","first_name":"www.boilerroom.tv","last_name":"","full_name":"www.boilerroom.tv","city":"London","description":"Connecting club culture to the wider world, on screen and irl through parties, film and video.","country":null,"track_count":6708,"public_favorites_count":0,"reposts_count":0,"followers_count":0,"followings_count":0,"plan":"Pro Unlimited","myspace_name":null,"discogs_name":null,"website_title":"","website":"http://boilerroom.tv","comments_count":45,"online":false,"likes_count":0,"playlist_count":364,"subscriptions":[{"product":{"id":"creator-pro-unlimited","name":"Pro Unlimited"}}]},"permalink_url":"https://soundcloud.com/platform/test2","artwork_url":null,"stream_url":"https://api.soundcloud.com/tracks/1203977743/stream","download_url":"https://api.soundcloud.com/tracks/1203977743/download","waveform_url":"https://wis.sndcdn.com/images/player-waveform-medium.png","available_country_codes":null,"secret_uri":"https://api.soundcloud.com/tracks/1203977743","user_favorite":false,"user_playback_count":0,"playback_count":0,"download_count":0,"favoritings_count":0,"reposts_count":null,"downloadable":false,"access":null,"policy":null,"monetization_model":null}
```

**Comment by dasha-kobzeva** [comment]
Cool thank you, let me see what is going on there

**Comment by dasha-kobzeva** [comment]
Could you try the following:
```
curl -X POST "https://api.soundcloud.com/tracks" \
       -H  "accept: application/json; charset=utf-8" \
       -H "Authorization: OAuth 2-273545-752705-XXXXXXXXXX" \
       -H  "Content-Type: multipart/form-data" \
       -F "track[title]=TEST2" \
       -F "track[asset_data]=@roskas-45-min-mix_audio.wav"
```
I have added @ next to asset name

**Comment by dasha-kobzeva** [comment]
Looks like TEST3 was a success

**Comment by Winspear** [comment]
Looks good to me dasha, thank you. I will close this issue
