### ISSUE TITLE
First respond of /me/activities is always empty

### ISSUE THREAD

**Issue by obrhoff** [soundcloud/api#179]
### Endpoint(s):
* `GET /me/activities`

### Steps to reproduce:
```bash
curl --request GET \
  --url 'https://api.soundcloud.com/me/activities?limit=1&linked_partitioning=true&client_id=DONT_SHARE_CLIENT_ID'
```

**Note that the count of items in the first reponse is empty.** 

Only by fetching the `next_href` results with in a list of items. This seems to be obviosly wrong. This also breaks the behavior of `future_href`, since its now just defaulting to a cursor `0` (which is always empty again).

**Comment by dasha-kobzeva** [comment]
Hello @obrhoff,

We will try to look into the issue shortly and get back to you.

**Comment by obrhoff** [comment]
Issue seems to be fixed now.
