### ISSUE TITLE
[Question] Rate limit clarification

### ISSUE THREAD

**Issue by swamp-agr** [soundcloud/api#182]
## [Question] Rate limit clarification
Question found of: February 10th, 2022

### Endpoint(s):
* `GET /oauth/token`
* `GET /tracks`
* `GET /tracks/{track_id}/streams`

### Scope(s):
* Quota and/or rate limit

### Questions:

* Is our understanding correct that `/tracks` requests do not affect the quota (In result there might be tracks with `stream_url` properties that indirectly pointed out to `/tracks/:id/stream`)?
* Is our understanding correct that `/tracks/:id/streams` requests (with `s` at the end) do affect the quota?
* Or does refreshing `access_token` for the subsequent API requests affect quota?

### History

- We tried to contact Soundcloud support via email. 
- Automatic reply suggested to contact Support via chat-bot.
- No 1879895 assigned to the request via Support system.
- According to No 1879895, there is no dedicated API Support team. Therefore, we were advised to look at StackOverflow, otherwise to create issue here.
- The only [one related topic on StackOverflow](https://stackoverflow.com/questions/20781388/is-there-a-quota-limit-for-soundcloud-api) does not contain any specific details that could answer our questions. 
- Since there were no specific information about endpoints on StackOverflow I am asking here.
- If it is not an appropriate place to ask please let us know where we can get that information.

**Comment by rahul-sc** [comment]
Heya. There are 3 rate-limits in effect at the moment on the API. 

1. Rate-Limit for generating tokens using client_credentials grant
2. Rate-Limit when using search endpoints i.e., /tracks /users /playlists
3. Rate-Limit when using playback i.e., /streams or /stream

Related Resources
https://developers.soundcloud.com/docs/api/rate-limits#global-limit
https://github.com/soundcloud/api/releases/tag/2021-09-07
https://developers.soundcloud.com/docs/api/explorer/open-api#/search

**Comment by swamp-agr** [comment]
Hi @rahul-sc,

I read the content of these three links you provided. Right now it's clear that:
1. there're three different limits.
2. `/oauth/token` request is limited to `50` requests per `12h` window.
3. `/streams` or `/stream` are limited with 15K requests per `24h` window.

And it's not clear what is the amount of requests for `/tracks`, `/users` and `/playlists` requests. 

Is it also 15K or something else?

**Comment by swamp-agr** [comment]
Thanks for providing that information. 👍 I am closing the issue since all questions have been solved.
Thank you and a have nice rest of the day! 😃
