### ISSUE TITLE
artwork_data on playlists not working

### ISSUE THREAD

**Issue by alexweinstein** [soundcloud/api#184]
I don't think artwork_data is working when updating existing playlists (/playlists PUT). Can someone check for me?

I'm doing this in the [API Explorer](https://developers.soundcloud.com/docs/api/explorer/open-api). 

### API Explorer
1. Authorize with "OAuth [user-token]"
2. Choose **Playlists PUT**
3. Enter playlist ID
4. Edit payload with the following:
```
{
  "playlist": {
    "title": "TEST TITLE",
    "artwork_data": "https://res.cloudinary.com/composerly/image/upload/w_250/v1644605230/je4neuvxyoiwgkvrstzn.png"
  }
}
```
5. Execute

Expected behavior:
The playlist _title_ and _artwork_ will be updated.

Actual behavior:
200 success, but only the playlist _title_ is updated. I believe because this is going through application/json, the artwork_data is ignored. And only the _title_ gets through.

I see in the API Guide, that artwork_data should be `Content-Type: mmultipart/form-data` (note the typo). But that's not an option in the API Explorer under `playlists PUT`. 

-------------

### CURL

Also, this is not working in cURL:
```
curl -X PUT "https://api.soundcloud.com/playlists/[playlist-id]" 
-H "accept: application/json; charset=utf-8" 
-H "Authorization: OAuth [user-token]"
-H "Content-Type: multipart/form-data" 
-d "{\"playlist\":{\"title\":\"TEST TITLE\",\"artwork_data\":\"https://res.cloudinary.com/composerly/image/upload/w_250/v1644605230/je4neuvxyoiwgkvrstzn.png\"}}"
```
Expected CURL behavior:
The playlist _title_ and _artwork_ will be updated.

Actual CURL behavior:
Nothing happens. No return. Nothing updated.

**Comment by dasha-kobzeva** [comment]
Hello @alexweinstein,

in your cURL request, you are setting the type to multiform, but sending the data as a JSON. A request should look similar to this: https://developers.soundcloud.com/docs/api/guide#updating-metadata

**Comment by alexweinstein** [comment]
Thank you so much @dasha-kobzeva. That is getting me much closer. 

But can you explain why the following is not updating the playlist artwork?
```
curl -X PUT "https://api.soundcloud.com/playlists/[playlist-id]" \
       -H "Accept: application/json; charset=utf-8" \
       -H "Content-Type: multipart/form-data" \
       -H "Authorization: OAuth[user-token]" \
       -F "playlist[title]=newtitle3" \
       -F "playlist[artwork_data]=https://res.cloudinary.com/composerly/image/upload/w_250/v1644605230/je4neuvxyoiwgkvrstzn.png"
```

**Comment by dasha-kobzeva** [comment]
Could you try uploading the file from your local storage using @?
So it would be like:
```
-F "playlist[artwork_data]=@/path/to/local/file"
```
