### ISSUE TITLE
/playlist always returns 401 - Unauthorized

### ISSUE THREAD

**Issue by Diablew** [soundcloud/api#186]
## Title: /playlist returns 401- Unauthorized
Issue found of: February 27th, 2022

### Endpoint(s):
* POST /playlists
* https://api.soundcloud.com/playlists

### Scope(s):
* Client Credentials python script and api guide site https://developers.soundcloud.com/docs/api/explorer/open-api#/playlists/post_playlists

### Steps to reproduce:
python script 
1. authenticate with client creds
2. access token is set to "OAuth {access_token}"
3. title, descr are strings, ids is a list of ids built like [{'id':1}, {'id':2}]
4. POST to /playlist
headers = {
    'accept': 'application/json; charset=utf-8',
    'Authorization': access_token,
    'User-Agent' : 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36'
  }

json_data = {
	    'playlist': {
	        'title': title,
	        'description': descr,
	        'sharing': 'public',
	        'tracks': ids
	    },
	}
requests.post('https://api.soundcloud.com/playlists', headers=headers, json=json_data)

### Expected behaviour:
A playlist created as described at `https://developers.soundcloud.com/docs/api/explorer/open-api#/playlists/post_playlists`.

### Actual behaviour:
{'code': 401, 'message': '', 'link': 'https://developers.soundcloud.com/docs/api/explorer/open-api', 'status': '401 - Unauthorized', 'errors': [], 'error': None}

**Comment by dasha-kobzeva** [comment]
Hello @Diablew,

Every resource on the SC platform has to have an owner. When you authorize with client credentials you have an anonymous session, so we cannot identify which user creates a playlist.

To fix the issue please use the Authorization Code flow to retrieve a token. YOu can find more details on it in our API guide on developers.soundcloud.com
