### ISSUE TITLE
Usage of Soundcloud API

### ISSUE THREAD

**Issue by apidev234** [soundcloud/api#187]
Hey, 
I had some issues regarding the soundcloud api.

Discord is a chat application which allows users to connect each other. It has a WebRTC support with api supporting websocket connection and so bots. What we wanted to know is, As stated in the Api documentation(File attached), We should be crediting the author and providing the source as soundcloud. Do we need to do anything else that can be a legal issue? If i credit the author and soundcloud and make my own player stream music to a different platform it wont be a problem right?

**Comment by dasha-kobzeva** [comment]
Hi @apidev234,
Are you building the discord bot that would play music from SC?

In general, if you are integrating with SC API and streaming music somewhere else, the following is required:

- credits the Uploader as the creator of that User Content;
- credits SoundCloud as the source of that User Content; and
- includes (in the case of web pages and mobile web pages) clearly visible backlinks from the relevant sounds within your app to the URL for the relevant sound on soundcloud.com (permalink_url).

**Comment by apidev234** [comment]
Hi, 

Yes i am building a discord bot that is going to stream music from sc to discord, if i credit sc and uploader there wont be any legal issues on me right?

**Comment by apidev234** [comment]
Also, could you elaborate a bit on "includes (in the case of web pages and mobile web pages) clearly visible backlinks from the relevant sounds within your app to the URL for the relevant sound on soundcloud.com (permalink_url)."

**Comment by apidev234** [comment]
Alright, Thanks a lot.
