### ISSUE TITLE
Seems to be a new undocumented rate limit?

### ISSUE THREAD

**Issue by mgoodfellow** [soundcloud/api#189]
## Title: Seems to be a new undocumented rate limit?
Issue found of: February 25th, 2022

### Endpoint(s):
*  Any

### Scope(s):
* Any

We have been receiving random failures on API calls since 25th February with raw content "Please slow down."

It seems you are returning a HTTP 429 status code, which is great, but this is entirely new and undocumented behaviour.

It is not made clear what the limit is, whether it is user/API key/IP based limiting - and it is also an unusual response as it doesn't follow the normal practice of letting the caller of the API know when the rate limit is resetting. From a developer perspective we don't know how to handle this error.

This has been causing a particular headache for us as historically you used to return a 429 response when a user has been rate limited for user-centric actions, and we act on this 429 to lock them out of our system until they have had a chance to review what caused the issue on SoundCloud directly (this behaviour is still missing from the new v1 repost endpoint - see: https://github.com/soundcloud/api/issues/74)

Anyway, could you offer up some more information about this rate limit please?

Thanks!

**Comment by mgoodfellow** [comment]
Interesting, it can happen when accessing the site directly and cause the whole site to not load - reproduce by clicking around a bit, then hard refresh the page

![image](https://user-images.githubusercontent.com/6501186/157430673-2ceb5af2-16da-43ba-ae43-a175aed86131.png)

**Comment by dasha-kobzeva** [comment]
Hello @mgoodfellow,

thank you for reporting the issue. 
We have not done any changes to API in a while, so I don't think it's related to API specifically. Let me figure out if this is a platform-wide change and what we can do.

**Comment by mgoodfellow** [comment]
Thanks @dasha-kobzeva !

I actually bounce off this rate limit as a normal user of SoundCloud while browsing around - some embedded elements might not load with the following error:

![image](https://user-images.githubusercontent.com/6501186/157647419-436fc06d-af2d-40f2-b86a-0ad33ffa9cb4.png)

Or (less commonly) the entire page is blocked from loading as my report in the previous picture. It seems there is a pretty aggressive site-wide rate limit in place. Restoring a browser session with a number of SoundCloud tabs can cause the issue as well (after reboot or browser update for example)

Here is an example with 4 tabs, if I kill the browser window, then restore with Ctrl-Shift-T causing that window with 4 tabs to reload at the same time:

Tab 1 - fine

![image](https://user-images.githubusercontent.com/6501186/157648118-0be0d0f3-4b9a-4067-90d5-32e8281a1031.png)

Tab 2 - fine

![image](https://user-images.githubusercontent.com/6501186/157648144-bfd79dbf-b1b7-49dd-808a-aedbeb7c1715.png)

Tab 3 - page doesn't load

![image](https://user-images.githubusercontent.com/6501186/157648179-041b7949-66a2-43ce-ac5c-8171b7967b0b.png)

Tab 4 - page doesn't load

![image](https://user-images.githubusercontent.com/6501186/157648208-ee1527e3-50da-44a8-a297-c455eb5df6ee.png)


As I say it doesn't happen every time, but I'm a surprised at the frequency with which I see this.

**Comment by dasha-kobzeva** [comment]
@mgoodfellow I have gathered some information for you.

There have been changes across all traffic with more aggressive rate limits implemented. At the moment the rate is the following: 100 req in a rolling window of 10 secs

We have not seen any issues so far apart from your request, maybe just specific IPs, but our systraf team might discuss the numbers again in case it becomes widespread.

I hope it answers your question and gives some clarity.

**Comment by mgoodfellow** [comment]
Hi @dasha-kobzeva 

Cheers for the info! That would explain the issues.

Take this for example:

![image](https://user-images.githubusercontent.com/6501186/157654077-15beb455-ba97-4961-a032-aa17b1e40789.png)


Loading https://soundcloud.com/discover makes 50 XHR requests to the api-v2 endpoint in ~2s

That would explain why restoring a browser with a couple of tabs causes some to fail to load.

Interestingly, once the app has booted, swapping between pages make significantly less requests - that initial boot makes a surprisingly large number of requests!

Thanks for the info nonetheless, appreciate the input and insights.

**Comment by dasha-kobzeva** [comment]
Hey @mgoodfellow,
thank you for the insights! I will propagate them to a dedicated team
