### ISSUE TITLE
All requests results in error "401 - Unauthorized"

### ISSUE THREAD

**Issue by mnajafzadeh** [soundcloud/api#191]
## Title: All requests results in 401 - Unauthorized
Issue found of: March 18th, 2022

### Endpoint(s):
* `GET /me`

### Scope(s):
* Authentication is not defining scope!

### Steps to reproduce:
```bash
curl --request GET \
  --url 'https://api.soundcloud.com/me'
  -H  "accept: application/json; charset=utf-8"
  -H  "Authorization: OAuth USER_ACCESS_TOKEN"
```

### Expected behaviour:
Returns the authenticated user’s information.

### Actual behaviour:
401 - Unauthorized

I also tried SoundCloud Public API Specification here: https://developers.soundcloud.com/docs/api/explorer/open-api
But the same result.

Thank you for your help

**Comment by dpreussler** [comment]
Hi there, are you sure you are using the correct authentication token?
I'm suspecting you are using a token obtained via client-id and secret instead of using a user specific one? 
You have to to through our OAuth flow. This explains this:
https://developers.soundcloud.com/docs/api/guide#authentication

**Comment by mnajafzadeh** [comment]
Hi,

Yes, I followed this guide https://developers.soundcloud.com/docs/api/guide#authentication
I am receiving the final response from the endpoint: https://api.soundcloud.com/oauth2/token

I first send the user to "https://api.soundcloud.com/connect?client_id=YOUR_CLIENT_ID&redirect_uri=YOUR_REDIRECT_URI&response_type=code"

and in redirect I use the Client Credentials Token Exchange Flow to obtain the access token.

$ curl -X POST "https://api.soundcloud.com/oauth2/token" \
     -H  "accept: application/json; charset=utf-8" \
     -H  "Content-Type: application/x-www-form-urlencoded" \
     --data-urlencode "grant_type=client_credentials" \
     --data-urlencode "client_id=YOUR_CLIENT_ID" \
     --data-urlencode "client_secret=YOUR_CLIENT_SECRET"

This is the example response I get:
    [access_token] => 2-120612--{string}
    [expires_in] => 3599
    [refresh_token] => i3Ov5apjQBuIMi8jXqJEckls3WnNY058
    [scope] => 
    [token_type] => bearer

**Comment by dpreussler** [comment]
Can you send me the SoundCloud user that owns the app?

**Comment by mgoodfellow** [comment]
He's using `grant_type=client_credentials` which won't allow access to a user specific API resource

**Comment by mnajafzadeh** [comment]
How should I use the redirect_uri? I used the one set in my App and also the URL encoded one with or without HTTP and receive "invalid_grant"

**Comment by mnajafzadeh** [comment]
Guys! I found the problem.
The https://api.soundcloud.com/oauth2/token endpoint could be called only one time with the same Authorization code.

Thank you for your help

**Comment by dpreussler** [comment]
glad you found it! :)
