### ISSUE TITLE
How to reset my compromised Client ID and Secret

### ISSUE THREAD

**Issue by LuigiPulcini** [soundcloud/api#192]
Hi, there.

If there is an explanation online about how to request the reset of my registered app's Client ID and Client Secret, I could not find it anywhere. [This section](https://developers.soundcloud.com/docs/api/terms-of-use#:~:text=Security%20of%20Your%20Client%20Secret) of the Terms of Use urges developers to:

> _if you believe that your client secret has been used without your permission, you'll need to tell us immediately_

yet it doesn't explain how, nor does it provide a direct means of contact to do so.

Any further information on the matter would be much appreciated.

**Comment by dpreussler** [comment]
Hi you can use the same process as when updating your redirect url:
https://github.com/soundcloud/api#how-can-i-update-my-apps-redirect_uri
