### ISSUE TITLE
Cannot search for a track via it's ISRC

### ISSUE THREAD

**Issue by BolajiOlajide** [soundcloud/api#202]
## Title: Cannot search for a track via it's ISRC
Issue found of: April 6th, 2022

### Endpoint(s):
* `GET /tracks`

### Scope(s):
* None (application is not using authentication i.e., implicit flow)

Currently the SoundCloud API is returning ISRCs when fetching an individual track object, but it is unfortunately not possible to search by ISRC. The ability to search via ISRC is needed for a tool I'm building.
I'm aware there's a duplicate issue created some years back [here](https://github.com/soundcloud/api/issues/53), however I'd love to know if anything as changed regarding searching for a track via it's ISRC using the public API or if you could give me more details about your partner API via email `hello[at]logicalley[dot]africa`.

Thanks a lot for the consideration!

All the best,
Bolaji

**Comment by dasha-kobzeva** [comment]
Hello @BolajiOlajide,

the search by ISRC exists, but it is only available to official partnerships, which we have business agreements with. Unfortunately, we cannot share access to it with the community at the moment.  


Regards,
SoundCloud Team
