### ISSUE TITLE
Limit Parmeter is broken on /me/activities

### ISSUE THREAD

**Issue by obrhoff** [soundcloud/api#203]
### Endpoint(s):
* `GET /me/activities`

### Scope(s):
* None (application is not using authentication i.e., implicit flow)

### Steps to reproduce:
```bash
curl --request GET \
  --url 'curl "https://api.soundcloud.com/me/activities?limit=10" \
     -H 'Authorization: Bearer xxx''
```

I receive following response:

```
{
  "collection": [],
  "next_href": "https://api.soundcloud.com/me/activities?limit=10&cursor=10",
  "future_href": "https://api.soundcloud.com/me/activities?limit=10&cursor=0"
}
```

Omitting the limit paramter like this results a not empty array.

```
curl "https://api.soundcloud.com/me/activities" \
     -H 'Authorization: Bearer xxx'
```

```
{
  "collection": [
    {
      "type": "track:repost",
      "created_at": "2022/04/07 18:43:31 +0000",
      ...
      }
    },
    ...
  ],
  "next_href": "https://api.soundcloud.com/me/activities?limit=50&cursor=50",
  "future_href": "https://api.soundcloud.com/me/activities?limit=50&cursor=0"
}
```

Keep in mind that I'm aware of the `playable` flag. I just tested it with a test user to see if a just reposted Item would appear in the other stream. A fresh fetch with a limit of 10 was not showing the new item.

**Comment by dasha-kobzeva** [comment]
Hello @obrhoff,

thank you for your ticket. The logic for `/activities` is not that straightforward. 
1. When you put no limit - we default to 50, so you get more results apriori. 
The endpoint returns the results from the latest event in time going backward. It is possible that there are events for your user that will happen in the future (like a track release in a week or so); We can not show those events, but the service counts them in, that is why you see the empty result. 
Unless you offset far enough from the latest event, you won't get results.

I'm working on a way how we can do it so you only get events up to the exact time of the request. For now, I'd suggest paginating over until you get the events back.

**Comment by obrhoff** [comment]
Ahh okay makes sense. Thanks for the clarification.
