### ISSUE TITLE
Please, update my Reditect_URL

### ISSUE THREAD

**Issue by MashaDo** [soundcloud/api#204]
## Been waiting for a month to hear back from support
Issue found of: April 13th, 2022

I registered my app like 10 years ago when redirect_URL was not a must. 

i contacted support mid March, but haven't heard back yet. 

please, who can i contact or how can i get this done?

**Comment by SalimehHabibi** [comment]
Hi @MashaDo 
Sorry for this delay. Could you please send the support ticket number?

**Comment by MashaDo** [comment]
Hi

sent March 19, 2022: For your reference, your ticket number is *1923945*.

thanks!
bye

**Comment by MashaDo** [comment]
resolved not, thanks!
