### ISSUE TITLE
Make track API accessible without access key

### ISSUE THREAD

**Issue by Subfader** [soundcloud/api#206]
You changed the API access key workflow again and my script broke for the 20th time in 10 years.

You guys are so annoying with your wannabe security.

Make the track API accessible without any key once and for all. No sensibale data there!

Mixcloud has it and I don't think it's a security flaw... https://api.mixcloud.com/xlr8r/xlr8r-podcast-736-francis-harris/

**Comment by dasha-kobzeva** [comment]
Dear @Subfader,

There were no recent changes to API security policy, I'm not sure what you are referring to by `changed the API access key workflow again`.

I would also like to kindly ask you to follow the Community Guidelines and refrain from being disrespectful.
