### ISSUE TITLE
401 Unauthorized error on previously working /me requests (contains Authentication header)

### ISSUE THREAD

**Issue by deanpress** [soundcloud/api#207]
### Endpoint(s):
* `GET /me`

### Scope(s):
* `non_expiring`
 
### Steps to reproduce:

Using https://github.com/njasm/soundcloud library (tried manual curl requests too).

```php
// callback.php

// Exchanges "code" param for auth token and stores it to the $soundcloud object
// Token object: {"access_token":"2-111-222-xxx","scope":"non-expiring","token_type":"bearer"}
$soundcloud->codeForToken($_GET['code']);

// Retrieves the correct auth token
// Example: 2-111-222-xxx
$token = $soundcloud->getAuthToken();

// Next part is done with curl to show that the headers are correct

$curl_h = curl_init('https://api.soundcloud.com/me');

curl_setopt($curl_h, CURLOPT_HTTPHEADER,
    array(
        "accept: application/json; charset=utf-8",
        "Authentication: OAuth " . $token,
    )
);

curl_setopt($curl_h, CURLOPT_RETURNTRANSFER, true);

// Response returns 401
$response = curl_exec($curl_h);

```

### Expected behaviour:
Retrieve the API data from `/me` as the user the authentication token is for. This flow used to work consistently until recently.

### Actual behaviour:
401 Authentication Error (consistently):

When using the library:
` A request must contain the Authorization header. For details please refer to https://developers.soundcloud.com/blog/security-updates-api.`

When using curl:
`{"code":401,"message":"","link":"https://developers.soundcloud.com/docs/api/explorer/open-api","status":"401 - Unauthorized","errors":[],"error":null}`

**Comment by mgoodfellow** [comment]
Yeah, SoundCloud made all the authentication changes about a year ago (July 2021) - so if you come across 3rd party libs which were updated before that time then they probably won't support the new authentication flows and you are better off rolling your own (or forking and PR'ing!)

Glad it's sorted :)

**Comment by dpreussler** [comment]
thanks @mgoodfellow for jumping in here
