### ISSUE TITLE
Feature request: endpoint to retrieve liked playlists/sets

### ISSUE THREAD

**Issue by Superjo149** [soundcloud/api#21]
In the api-v2 endpoints, there was a `me/library/albums_playlists_and_system_playlists` endpoint to fetch liked playlists. Using the public API, it would be nice to also be able to do this. Maybe an endpoint `/me/likes/playlists` similar to tracks can be introduced for this.

**Comment by obrhoff** [comment]
There is a similar open ticket. https://github.com/soundcloud/api/issues/16

**Comment by dasha-kobzeva** [comment]
Hi @Superjo149,

The requested feature was added to our API. 
You can find the details on usage here:  https://developers.soundcloud.com/docs/api/explorer/open-api#/me/get_me_likes_playlists
