### ISSUE TITLE
tracks api returning http status 500

### ISSUE THREAD

**Issue by wickeym** [soundcloud/api#215]
## Title: Cannot retrieve tracks of a user, status code is always 500
Issue found of: June 13th, 2022

The template for this issue tracker pretty much is exactly what is happening: It should return a list of tracks, but instead returns a 500 server error.
This has been working for multiple years for me, and just stopped this morning.

### Endpoint(s):
* `GET /users/{id}/tracks`

### Scope(s):
* Application OAuth.

### Steps to reproduce:
I send it an OAuth token in the Authorization header.
This is one of the users: `https://api.soundcloud.com/users/1446690/tracks?limit=30`

### Expected behaviour:
A list of tracks as described at `https://developers.soundcloud.com/docs/api/reference#users`.

### Actual behaviour:
500 Server Error (consistently)

Sincerely,
Michael Wickey

**Comment by obrhoff** [comment]
Seeing it here on other endpoints as well. Just getting code 500 back.
