### ISSUE TITLE
Trying to connect to public api

### ISSUE THREAD

**Issue by unrealtone** [soundcloud/api#216]
## Title: Unable to connect and get access_token
Issue found of: September 20th, 2020

### Endpoint(s):
* GET /oauth2/token

### Scope(s):
* I have read through the blogs and it seem grat_type = client_credentials is deprecated however Authorization requires redirect_uri and an auth code aswell. So do i need to register a new app to use even the public apis? But since we cant make any new apps does that mean that a new developer cannot use any of the apis?

### Steps to reproduce:
```bash
curl --request GET \
  --url 'https://api.soundcloud.com/users/12345/tracks?limit=1&linked_partitioning=true&client_id=DONT_SHARE_CLIENT_ID'
```

### Expected behaviour:
Get access_token

### Actual behaviour:
401 Unauthorized access

**Comment by wickeym** [comment]
Hi unrealtone,

I believe that you are correct that new users cannot use the api. The api requires registering an app, and that process is currently closed. 
https://github.com/soundcloud/api#can-i-request-an-api-key-for-a-new-app

With that said, I have seen people at Soundcloud receptive to new app registrations on a case by case basis, but you will need to contact them directly.

Michael

**Comment by oscargws** [comment]
Why have applications been closed for 4 years? Is there anyone I can contact about this? I'm keen to register an app for a not-for-profit I run that could greatly benefit from being able to use the API

**Comment by emmatebibyte** [comment]
> Hi unrealtone,
> 
> I believe that you are correct that new users cannot use the api. The api requires registering an app, and that process is currently closed. https://github.com/soundcloud/api#can-i-request-an-api-key-for-a-new-app
> 
> With that said, I have seen people at Soundcloud receptive to new app registrations on a case by case basis, but you will need to contact them directly.
> 
> Michael

How do I contact them directly? I've been looking for an email.

**Comment by jakesanghavi** [comment]
Does anybody have an update on this? This is causing me trouble as well. I want to make a custom player and am unsatisfied with their current method of just using an iframe.
