### ISSUE TITLE
Feature request: Add ability to fetch multiple tracks by adding an array of ids

### ISSUE THREAD

**Issue by Superjo149** [soundcloud/api#22]
In some instances fetching a bunch of tracks is required. For this, being able to do this in a performant way would be nice. On the api-v2 you were able to pass an array of ids to `tracks` to do this.

**Comment by docterd** [comment]
This functionality is already provided by the search api.

`GET https://api.soundcloud.com/tracks?ids=969190882,968460031,968490736,967923826`

**Comment by Superjo149** [comment]
Aha, allright. That was confusing, thanks.
