### ISSUE TITLE
I want you to fathom how dumb you are. 

### ISSUE THREAD

**Issue by ErraticFox** [soundcloud/api#222]
Imagine working for SoundCloud and having your API application down for over 4+ years and then you open it up for a little more than month and then close it back down from ineptitude. Quit hiring (yes I'm talking to you reading this if you work for SoundCloud, honestly what ARE you doing w your life? Way dead company have fun being a failure) your cereal box certification.

**Comment by vincerubinetti** [comment]
It's fine to criticize the company as a whole for doing a very poor job of staying afloat and relevant, but lower-level individual employees, especially software devs, don't deserve this kind of treatment. This frustration could be better aimed at the CEO and management. I hope those people are taking note.
