### ISSUE TITLE
RSS Feed Rate Limits

### ISSUE THREAD

**Issue by zachary-mixon-audacy** [soundcloud/api#224]
### Endpoint(s):
* GET `http://feeds.soundcloud.com/users/soundcloud:users:{USERID}/sounds.rss`

### Expected behaviour:
When receiving 429 responses I expect to see information about the rate limit in the response, per documentation available here: https://developers.soundcloud.com/docs/api/rate-limits

### Actual behaviour:
We instead receive `{"body":"Please slow down.\n","statusText":"Rate limit exceeded"}` with no information about what the rate limit is nor when this limit will be refreshed.

The documentation doesn't appear to state a rate limit for RSS feeds, only a 15k/day limit specifically for play requests.

I would like to know what the limit is and if it refreshes on the same 24 hour schedule described in the docs. I also think it would be helpful for other developers if the RSS feeds behaved in the same manner described in the API docs, or if the documentation made mention of their differences.

**Comment by mgoodfellow** [comment]
This sounds like one of SoundCloud's global rate limits applied at the edge: https://github.com/soundcloud/api/issues/189

There might be some useful information in there for you, but specifically I only used to hit this when multiple tabs were restoring - however the specific limit was discussed here: https://github.com/soundcloud/api/issues/189#issuecomment-1063957741 - I have no idea if that is still the case, I personally haven't seen that particular rate limit response in a long time.
