### ISSUE TITLE
Question: Possible types of Soundcloud activities

### ISSUE THREAD

**Issue by yatskivkath** [soundcloud/api#231]
### Endpoint(s):
* `GET ​/me​/activities`
* `GET ​/me​/activities/all/own`
* `GET ​/me​/activities/tracks`

### Question:
What are the possible values of the type field in the output of these requests? I've seen `track:repost`, `track` and `playlist`. Is there anything else?

**Comment by fabianbernhart** [comment]
I dont think so.
![grafik](https://github.com/soundcloud/api/assets/135550293/ae9f25f2-fdfa-466c-812a-dd3c3c715814)

Source: https://developers.soundcloud.com/docs/api/explorer/open-api#/me
