### ISSUE TITLE
Active app being disabled?

### ISSUE THREAD

**Issue by ponny** [soundcloud/api#242]
## Title: Active a
Issue found of: 2nd June, 2023

### Endpoint(s):
All

### Scope(s):
All API functionality, perhaps login too

### Expected behaviour:
App and API function as normal

### Actual behaviour:

We got this email (see below) about our app being disabled.  We have two apps - one for production and one for testing.  It's unclear if it's both or a single app is being disabled.  Both apps have also been active in the last 3 months so there seems to be some mistake with this process/email too. 

Here are our two app IDs:
* Dev/test: 9c46bcbbca1ce6bd738d9f83c99acc1a
* Production: 0122ebd7b7e215be8b2983016bb06341

Can the SoundCloud team please provide some clarity and ideally stop our app from being disabled?  If it's just one app, it shouldn't be a problem for the changes/support since we want both apps to be the same anyway.

> Hello,
> 
> We are reaching out today as you are the registered owner of a SoundCloud application that has been inactive for over 3 months. We’re writing to inform you that as of June 8, 2023, we are revoking access to your application in order to make necessary changes to our platform. As a result you will be unable to access SoundCloud’s API and any apps that use our APIs will no longer work.
> 
> We understand that this may be disappointing; however, we need to do this for two reasons:
> •	Recently, we haven’t been able to provide developers with the level of support that you deserve. That includes being able to help you when things go wrong and supporting you when you build amazing things.
> •	More pressingly, we haven’t been able to sustain the level of oversight needed to make sure bad actors aren’t abusing our API. As such, change is necessary in order to protect the artists and fans that use SoundCloud’s services.
> Rest assured, this is not the final state of our API program - just a temporary reset. We’re working hard to reopen the doors as soon as possible so that you can use our API in the future.

**Comment by obrhoff** [comment]
It would have been great if you could have been more specific about which key got disabled. Additionally, a notice before disabling it would have been greatly appreciated.

**Comment by ponny** [comment]
@obrhoff You're having the same issue?

**Comment by wickeym** [comment]
Hi, I received that same email and I only have one app and it is also active.

Michael

**Comment by wuq0** [comment]
Hi, I received the same email, and only have one active app id as well: 13eb52c2b118e05cd8313a16d5a592d3

SoundCloud team, can you please revisit how you determined which apps are inactive before terminating access? Our app is consistently active.

**Comment by ponny** [comment]
I was able to get this resolved by going through their usual support.  I linked them this issue but you might want to reach out yourself.

**Comment by thegyppo** [comment]
Even though we had assurances from Soundcloud about not being deleted this app was deleted today.

**Comment by ponny** [comment]
We're back finally! 🎉 

FYI I bugged them here, [Twitter](https://twitter.com/SoundCloudDev), and email.  Not sure which one got it over the line.
