### ISSUE TITLE
API Acecess

### ISSUE THREAD

**Issue by modernlabrat** [soundcloud/api#243]
I literally just want to use the search feature for tracks and playlists. I don't need any user's information or to manipulate any data for a user. At the very least, you all could allow this feature to be available?? When will users be able to create an app? It has been years. Artists are using this platform and there are songs by those artists that are not on Apple Music, Spotify, or YouTube. Don't you think it would be nice to provide the simple feature of searching for tracks which is a public feature anyways??

**Comment by dev-syn** [comment]
Quite crazy it's been this long I'm looking for the same thing.

**Comment by MariaVWSoundCloud** [comment]
https://github.com/soundcloud/api/issues/246#issuecomment-1649629657

**Comment by MariaVWSoundCloud** [comment]
I know it has been quite some time, but we are happy to connect with you and grant you access if we see fit to our terms of use - just drop us a message to get the convo started
