### ISSUE TITLE
Incorrect API access revocation 

### ISSUE THREAD

**Issue by swamp-agr** [soundcloud/api#244]
## Access revocation 

We received an email that access to your API will be revoked soon.

At the same, we are using your API. So there is something wrong. Could you please help us understand what is happening?

### Endpoints we are currently using:

- `POST /oauth2/token`
- `GET /tracks/<trackId>/stream`
- `GET /resolve.json`.

**Comment by syndicast** [comment]
We received the same email despite we have been using the API for so many years. Of course, there is nobody to contact….

**Comment by wickeym** [comment]
Hi, I received that same email and I only have one app and it is also active.

Michael

**Comment by thesubdelta** [comment]
+1, also received the email even though my app is active & I still currently have access

![image](https://github.com/soundcloud/api/assets/61033725/ea068983-602a-4097-af1b-26e3f949d187)

**Comment by wickeym** [comment]
My api access just ended on Saturday 6/24/23. :-(

**Comment by MariaVWSoundCloud** [comment]
Hey all, in the email you should have received prior to the deactivation there are instructions what to do if you still need your credentials. Even though they might have been deactivated now, we can revoke them. Just follow the instructions in the email :)

**Comment by swamp-agr** [comment]
@MariaVWSoundCloud, thank you so much for reaching us back! 

I can confirm, we've received an email. 
So I am closing this issue for now.

Have a good day!

Kind Regards,
Andrey

**Comment by mediaexplorer74** [comment]
> m closing this i

Hi, Maria. Are you from Russia too? Tell me please why https://soundcloud.com/ broken? It don't want to open normally about one year.

Best,
Andrey aka MediaExplorer
