### ISSUE TITLE
Oembed Gone? 404 status - looks like it's back (for good?)

### ISSUE THREAD

**Issue by tristan-misinc** [soundcloud/api#247]
Client reported issue with embeds not working on their site today. Was working until recently.
https://developers.soundcloud.com/docs/oembed - states oembed endpoint is https://soundcloud.com/oembed
The endpoint returns 404 now, with or without query parameters. No updates to documentation or announcements of retirement.

Was this silently retired or is this a problem on soundcloud's end? 

Very urgent - I'm sure my client isn't the only user for the oembed endpoint. We need to fix this ASAP, so if this endpoint is not coming back, we need to find another solution.

Thanks

**Comment by GabrielMartinsCarossi** [comment]
Same issue here. I'm getting 403 in production, but it works fine on my local environment. 

SoundCloud published this vague update: https://developers.soundcloud.com/blog/an-empty-blogpost

**Comment by mediaexplorer74** [comment]
> SoundCloud published this vague update: https://developers.soundcloud.com/blog/an-empty-blogpost

Wow, fresh post by Jordan Pettinato, after 2 years of total silence :) Thank you, it's some hope for best SoundCloud API future ;))

**Comment by tristan-misinc** [comment]
Appears I'm receiving the 403 as well when accessing via cURL on my production server - the 404 is when pulling the endpoint up from a browser. No response body at all with the 403. Should have verified it was returning the same as what I had on a browser.

If the oEmbed endpoint is being moved non-public or something, that'd be totally fine - we just need the ability to ask for credentials for this endpoint. We have a client relying on this endpoint to serve their content to their paying subscribers. It's not a good look at all for soundcloud or us as developers.

The lack of response from support on this is chilling :(

**Comment by tristan-misinc** [comment]
We're back up today - still receiving a 404 via browser for the endpoint without parameters, but with parameters and via cURL requests from our production server, we're getting 200 with good response data. A big thank you to whoever behind the scenes has opened the endpoint up :)

Any official or unofficial updates from the soundcloud API team would be greatly appreciated, either here or through the support tickets filed. Our client is overjoyed to see their streaming audio files working again, but I can't tell them why nor assure them things will continue working.

**Comment by tristan-misinc** [comment]
The oEmbed endpoint seems to be working fine still after a little more than a week, so I'm going to close this issue - just wish we had some sort of verification that this will continue working going forward.
