### ISSUE TITLE
API Access revoked

### ISSUE THREAD

**Issue by obrhoff** [soundcloud/api#248]
## Access revoked

My App just got deleted without a warning from SoundCloud Dev. Can you please help me out what happened there?

**Comment by tristan-misinc** [comment]
They're closing down what they considered inactive apps - see the blog post from the 2nd: https://developers.soundcloud.com/blog/

Might be they thought your app was inactive? That or you were making so many requests they thought it was abuse? Been waiting a week for response from a dev on the github already, so I wouldn't expect much here. I'd say to reach out to support / file a ticket, but still no response to my ticket filed last week either. If you file a ticket and update it a few times, they might give your app privileges back without saying a word, like they did with bringing back the oEmbed endpoint, but no guarantees. 

Very discouraged by the lack of engagement from soundcloud - we have some very concerned and pretty angry customers that I'll likely have to move to another service.

Good luck.

**Comment by thegyppo** [comment]
Same issue here, we had assurances from their Support that it wouldn't be deleted too.

**Comment by obrhoff** [comment]
I contacted the Support through the Ticket System and I got a reply. They can whitelist the API Keys but at least mine has not been fixed yet.
