### ISSUE TITLE
Feature Request - POST/PUT/DELETE for Playlists

### ISSUE THREAD

**Issue by docterd** [soundcloud/api#25]
## Feature Request - POST/PUT/DELETE for Playlists

Currently the `/tracks` endpoint allows it to create, update and delete tracks. This should be added as well for playlists.

### Endpoint(s):
* `POST /playlists`
* `PUT /playlists/{playlist_id}`
* `DELTE /playlists/{playlist_id}`

**Comment by rahul-sc** [comment]
Should be possible now.
https://developers.soundcloud.com/docs/api/explorer/open-api#/playlists

Please review.

**Comment by docterd** [comment]
Tested it yesterday. So far so good. Thanks!

**Comment by JGSolutions** [comment]
can i delete certain tracks from playlist using this:
DELTE /playlists/{playlist_id}

**Comment by rahul-sc** [comment]
Please refer to 
https://developers.soundcloud.com/docs/api/explorer/open-api#/
