### ISSUE TITLE
Redirect URI w/o http/https not working - redirects to Soundcloud 404 page

### ISSUE THREAD

**Issue by thesubdelta** [soundcloud/api#250]
## Title: Redirect URI w/o http/https not working, redirects to Soundcloud 404 page
Issue found of: July 18th, 2023

### Endpoint(s):
* `GET /connect`

### Scope(s):
* Authorization Code Flow

### Steps to reproduce:
```bash
curl --request GET \
  --url 'https://api.soundcloud.com/connect?client_id=<client id>&redirect_uri=<redirect uri (w/o http or https specified)>&response_type=code&display=popup'
```

### Expected behaviour:
After clicking `Connect and Continue`, redirect to app with specified redirect uri route

### Actual behaviour:
Get redirected to `https://secure.soundcloud.com/<redirect uri (w/o http or https specified)>?code=<access code>`
![image](https://github.com/soundcloud/api/assets/61033725/086e4056-66dc-422a-af95-43f2194caedf)

I've already submitted a support ticket to update my redirect URI to include `https`

**Comment by thesubdelta** [comment]
Adding http or https to the redirect uri in the `/connect` requests results in redirect URI mismatch error:
![image](https://github.com/soundcloud/api/assets/61033725/0dc167ba-c6b5-40a9-9643-d3e0ce1dfb0c)

**Comment by MariaVWSoundCloud** [comment]
Hey there, does the problem still persist? We saw a couple of login issues in the past weeks, maybe was it just temporary?

**Comment by ivan-015** [comment]
We are also experiencing this issue. Our redirect on soundcloud does not have http/https

**Comment by thesubdelta** [comment]
@ivan-015 SoundCloud responded to my ticket and updated the redirect uri with https - everything is working as expected now.
