### ISSUE TITLE
Not able to regiter new app from last 2 year 

### ISSUE THREAD

**Issue by tusharhatwar1997** [soundcloud/api#251]
Due to the high amount of requests recently received, we will no longer be processing API application requests at this time. We are working to re-evaluate our process to make it more efficient.

**Comment by tusharhatwar1997** [comment]
Unfortunately, when I followed the link provided earlier (https://help.soundcloud.com/hc/en-us/requests/new), I encountered the following error message: "We're currently experiencing errors with insights. Engineers are working on a fix. More info here." Due to this, I am unable to proceed with the registration process.                                                            
                                                                                                                                                                                                             To facilitate the registration process, we kindly request your assistance in generating the necessary API credentials for our app                                                                                                                                                                                                                     
                                                                                                                                                                                                      
Thank you for your understanding and assistance. We look forward to your response and the opportunity to integrate SoundCloud's API into our app.

**Comment by MariaVWSoundCloud** [comment]
Hi, you can still submit the request - you can use the chat bot and just say "No this didn't help" twice and you will see the form for a new request.

**Comment by tusharhatwar1997** [comment]
Hi, I submitted request approximately three weeks ago and i received the ticket ID upon submission, I have not received any updates or responses regarding the progress of my request. Could you kindly provide me with an update on the status of my ticket and any progress made toward resolving? Your assistance in this matter is greatly appreciated.

**Comment by MariaVWSoundCloud** [comment]
Hi there, sorry for the delay - vacations were very demanding. :) I just worked on all open tickets - did you receive a reply? (I cannot associate your GitHub username with any of the requester names in the tickets)

**Comment by tusharhatwar1997** [comment]
No, I did not receive any mail after this. For your reference, this is my ticket number: 2490947, and my email is [tusharhatwar1997@gmail.com](mailto:tusharhatwar1997@gmail.com).

**Comment by MariaVWSoundCloud** [comment]
Thanks for providing the ID - you may delete it now (as well as your email address) - the ticket was labeled wrongly accidentally, that's why it never ended up on my desk. Thank you for your patience! You should have received my reply now :)

**Comment by kniferider** [comment]
thank you for your link, I could ask and request over the chatbot from Soundcloud.
