### ISSUE TITLE
iTunes does not syndicate changes in SoundCloud podcast logos.

### ISSUE THREAD

**Issue by csmaccath** [soundcloud/api#252]
I am not a developer, but I have some technology skill and manage my own wiki and website, so I hope the SoundCloud engineering team will excuse any breaches in protocol here. 

I've tried several times to change my podcast logo, but while Amazon, Google, Spotify, and other syndicators honour the change, iTunes doesn't. I've done some digging, and I think I know the reason why, but the fix will need to be implemented by one of the SoundCloud software engineers.

iTunes needs for the new logo to have a different file name than the old logo does. However, when SoundCloud formats the iTunes markup for iTunes syndication, it assigns a filename to the logo that never changes even if the user uploads a new image. This means that SoundCloud podcasters can never change their podcast logos with iTunes. This is actually a known problem on Apple support boards. I was trying to find out why I couldn't change my podcast logo yesterday and stumbled upon several conversations about it.

Anyway, all your software engineer needs to do is code the markup to change if the image changes so iTunes recognizes it as a different image.

I hope I was able to help here, and I hope the issue is resolved so I can change my podcast logo. Thanks very much for your time.

This is my current image markup as listed in your RSS feed:
https://il.sndcdn.com/avatars-KG86bE8XAoT81ziJ-vDDOAO-original.ipq

I think you just need to make a change in the code that allows "KG86bE8XAoT81ziJ-vDDOAO-original" to change if the user uploads a new image.

![Screenshot 2023-07-29 at 8 59 00 AM](https://github.com/soundcloud/api/assets/132299607/a5c58b13-d1ce-43a9-9748-1e1d4c172a9a)

**Comment by MariaVWSoundCloud** [comment]
Hi @csmaccath - thanks for this detailed report! I will take a look at it with the team internally and come back to you! Cheers!

**Comment by MariaVWSoundCloud** [comment]
@csmaccath : Just to confirm: Did you try to completely delete the pic and upload a new one as a second step and it still gets the same name?

**Comment by csmaccath** [comment]
@MariaVWSoundCloud - I hadn't performed that specific test until you suggested it, but now I have, and I've created screenshots for you. In Image 1, the original logo is in place. In Image 2, there is no logo because I have removed it. In Image 3, I have uploaded the same logo, but with a new filename. As you can see, in Image 1 and Image 3, the filenames SoundCloud assigns are the same, while in Image 2, there appears to be a default image assigned because I don't have one in place. Does this help?

![Image 1](https://github.com/soundcloud/api/assets/132299607/2ce52683-b8e4-4d09-be04-e5f8f4e4e0b7)
![Image 2](https://github.com/soundcloud/api/assets/132299607/1700f795-bac8-4c43-88b1-2678f0f7d0ae)
![Image 3](https://github.com/soundcloud/api/assets/132299607/0dbd5ca5-6200-4c82-9475-e06fb8292bc5)

**Comment by MariaVWSoundCloud** [comment]
Hey again! A colleague of mine had a look at it and appears that the logo you are using is actually your avatar image.
If you uploaded the same image, it is possible that the same name will be generated. 
Can you try to use a different image?

**Comment by csmaccath** [comment]
> Hey again! A colleague of mine had a look at it and appears that the logo you are using is actually your avatar image. 

I'm not sure what you mean by "the logo you are using is actually your avatar image." Can you run that by me again with different phraseology? Meanwhile, I'll try to answer as best I can.

The image in the screenshot below is indeed the same image I previously used, but it has a different filename than the one I previously used because I changed it while troubleshooting for you yesterday. This is the image that currently gets syndicated to iTunes.

![Screenshot 2023-08-02 at 10 05 28 AM](https://github.com/soundcloud/api/assets/132299607/7189d258-f10b-4463-9949-4bc01ad8df3e)

Weirdly though, if I upload a completely different image, which I have just done, the filename changes. See the screenshot below and compare it with the previous screenshots.

![Screenshot 2023-08-02 at 10 24 28 AM](https://github.com/soundcloud/api/assets/132299607/c63d545d-7c5f-470d-b3d3-b5c1487d5d62)

![Screenshot 2023-08-02 at 10 17 55 AM](https://github.com/soundcloud/api/assets/132299607/7c809494-03fe-4be3-bb5a-4968e639aedc)

This would _seem_ to indicate that the SoundCloud system is using information other than the filename to identify the image, since it did _not_ change when I uploaded a the same image with a new filename but _did_ change when I uploaded a different image altogether (unless you've changed something recently in troubleshooting that I'm not aware of).  In fact, when I was changing the image just now, I accidentally uploaded one that was under 1400 x 1400, which iTunes requires, so I uploaded the same image at a higher resolution with a different filename, and SoundCloud gave it the same name on the back end again.

![Screenshot 2023-08-02 at 10 30 21 AM](https://github.com/soundcloud/api/assets/132299607/d092e3e7-c01b-40ea-b45e-022250128b41)

I've also uploaded different images in the past, and they've failed to syndicate to iTunes. I'm hesitant to blame iTunes for this issue because of that and because several people have reported this specific problem on Apple troubleshooting boards.

I'm also uploading the old and new logos so you have them to work with.

Old:
![Soundcloud FF RSS Image 2022](https://github.com/soundcloud/api/assets/132299607/01540685-5855-4807-91de-0cc119933d0d)

New:
![FFLogo2023](https://github.com/soundcloud/api/assets/132299607/c703ec08-9aac-4bea-81eb-ed30e3d8248f)

One last thing. I figured out I had the wrong image resolution when I ran the rss feed through Podbase. But even though I've increased the resolution of the image (not scaled it up, but increased the resolution) Podbase still thinks it's the old image too, likely because the filename hasn't changed in the rss feed. 

At this point, I wonder if the new image I just uploaded (which is my new logo) has always been less than 1400 x 1400, which would be my fault if so. However, if SoundCloud gives it the same filename on the back end even when I've increased the resolution and given the image a new filename, I'll have to recreate it from scratch. That's no big deal, but it also doesn't solve the problem at hand for everybody. It merely bypasses it for me. (Maybe.)

Okay, I think I've given you all the info I can. Please let me know if it helps, and thanks so much.

**Comment by MariaVWSoundCloud** [comment]
Hi again - I believe this issue is based on a file name created based on the **content** of your picture, so even independent of the size the file name will be generated on that. I know it may not be ideal, but if you could alter your picture's appearance, you should be able to upload it and get a new file name. I hope it solves your issue.

**Comment by csmaccath** [comment]
How different will the image need to be, do you think? The second image is my actual logo, and I don't want to put something up that isn't. If I recreate the same image from scratch, will that be sufficient?

**Comment by MariaVWSoundCloud** [comment]
@csmaccath This is understood, thanks - please don't forget that SoundCloud is not a 10.000 people company like others and we have to pick carefully where we invest our capacity.
Having said that, we hope, you will be able to use the described workaround and make it work. We wish you success with your podcast!

**Comment by csmaccath** [comment]
@MariaVWSoundCloud - It doesn't take 10,000 people to change an MD5 hash in a line of code to make certain these image names change every time. It takes one programmer analyst who knows where that line of code is and how to change it. If you don't know, that's fine, but please don't insinuate that I've asked for something unreasonable or been impolite, because I haven't. And respectfully, you haven't answered my question. **How different does my new image need to be for your naming system to recognize it as different? If I recreate the image from scratch, will this be enough?** If I'm left with no other option but using this workaround, please at least explain its parameters.

**Comment by MariaVWSoundCloud** [comment]
Hi, please just try it out. Since you are also in contact with our support, I am going to close this thread here to avoid redundant communications. Have a great day.
