### ISSUE TITLE
Is there a time limit for the resolved stream location URL?

### ISSUE THREAD

**Issue by alexweinstein** [soundcloud/api#254]
[API Guide](https://developers.soundcloud.com/docs/api/guide#playing) tells us that in order to get the streaming file location of a track, we should:
> Send a GET request to `stream_url` and you will get a set of links with available transcodings which you can choose from. 

This returns: 
```
{
    "status": "302 - Found",
    "location": "https:\/\/cf-media.sndcdn.com..."
}
```

However, it seems that the `location` url expires after a few minutes, generating a 403. 

My questions:

- What is the official length of time that the location url will last? 
- Is there a way to extend it?
- Is there another way I should be getting the stream file url that doesn't expire?

**Comment by youssefhassan** [comment]
302 has to be followed immediately within the same request, follow redirects option in most of the programming languages and frameworks should exist
