### ISSUE TITLE
Liked tracks not updating in real time

### ISSUE THREAD

**Issue by superturboryan** [soundcloud/api#255]
### I've noticed that when I like a track using the API, the track is added to my liked tracks playlist on soundcloud.com but not the liked tracks returned from the  `/me/likes/tracks` API endpoint. 
Issue found of: September 19th, 2023

### Endpoint(s):
* `GET /me/likes/tracks`

### Steps to reproduce:
1) Like a track using the endpoint `/likes/tracks/{track_id}`
2) Confirm track is liked, added to liked tracks for account on soundcloud.com web app
3) Request liked tracks from API endpoint `/me/likes/tracks` 

### ✅ Expected behaviour:
Track from step 2 is added to tracks returned in step 3

### ❌ Actual behaviour:
Liked tracks returned in step 3 are not updated with track from step 2

**Comment by pyxelr** [comment]
I've got the same issue in my mobile app. It cannot sync all the latest likes from my web app, and the workaround is to clean SoundCloud app data.

**Comment by youssefhassan** [comment]
Does the issue still persist? Please bear in mind, it might need a couple of minutes to propagate

**Comment by pyxelr** [comment]
@youssefhassan I’m still facing issues with the latest SoundCloud Android app (`2024.09.20-release`) on my Galaxy S24 Ultra. When I try to resync my “Liked tracks” by pulling down the screen, the new tracks don’t appear.

Additionally, the app crashes often when I’m playing a track and navigating through others, like using the "Search" menu. It's frustrating, especially since no other app on my phone is this buggy.

**Comment by superturboryan** [comment]
> Does the issue still persist? Please bear in mind, it might need a couple of minutes to propagate

@youssefhassan I noticed that the official SoundCloud iOS does seem to update in real time, but I can understand if changes made via the public API take a few minutes to propagate. 

I'll go ahead and close this issue now that it seems to be expected 🤝

**Comment by arian-k84** [comment]
i'm still having this issue and neither my web liked tracks nor my app liked tracks are being synced correctly and seem to be stored separately
