### ISSUE TITLE
Access GO+ content

### ISSUE THREAD

**Issue by Superjo149** [soundcloud/api#26]
### Endpoint(s):
* All track/playlist endpoints

This issue extends on the discussion in #1, and follows up on the communication via email between me and @rahul-sc. Both GO+ music and music which is just disabled for third party access (#1) should still be able to show up in the API. In our usage, we should be able to determine if we can play this or not, by using the `streamable` property or something similar to determine if it is GO+ content.

**Comment by anikarni** [comment]
Hey @Superjo149 , as with #1, this should now be possible with the newly added `access` param. Check out yesterday's blog post for how to use it. I'm closing this for now, but feel free to submit another ticket if you find that this solution is lacking ;)
