### ISSUE TITLE
Subscriptions for User

### ISSUE THREAD

**Issue by superturboryan** [soundcloud/api#271]
### Endpoint(s):
* `GET /me`

I would like to understand what subscriptions will show up in the "plan" and "subscriptions" properties returned for a user by the /me endpoint.

I'm receiving:

```
"plan": "Free",
...
"subscriptions": [
   {
      "product": {
         "id": "free",
         "name": "Free"
      }
   }
],
```

Despite my user having a **SoundCloud Go subscription.**  

I *suspect* that only the "creator" type subscriptions like "Pro (Unlimited)" are being returned from the API, can someone at SoundCloud kindly confirm this? 

Is there any way to know if the authenticated user has a Go subscription using the public API?

Cheers 🤙

**Comment by youssefhassan** [comment]
No Go subscription and Go+ content are not accessible from public api. There's a partners API that have access to Go+ content and can access the Go subscription

**Comment by superturboryan** [comment]
Where we can find out more about the partners API?
