### ISSUE TITLE
App registration/API key deleted (again)

### ISSUE THREAD

**Issue by thesubdelta** [soundcloud/api#272]
## App registration/API key deleted (again)
Issue started: October 12, 2023 ~9:30 PM UTC

### Endpoint(s):
All

### Expected behaviour:
API calls return data

### Actual behaviour:
401 Unauthorized (consistently)

### More Info:
Looks like my app registration was deleted again, this happened before and I raised issue #78 to get it restored.

Client ID: b60442f32f3a****************9aaa

This project is still in active development and is planned for a production release soon.

I have also raised a support request - ticket number is 2589221.

![image](https://github.com/soundcloud/api/assets/61033725/c028927b-c4ae-40a1-b542-2e28685edc61)

**Comment by thesubdelta** [comment]
This issue was also addressed earlier this year in support ticket 2437734.

Has anything changed that has caused me to lose my app registration?

Let me know if there's anything you need from me.

Thank you.

**Comment by MariaVWSoundCloud** [comment]
Hi,

a few months ago we revoked all inactive client credentials. We can undo that, but please open a service ticket for that, so the right people can take care of it. 

Best regards,
Maria

**Comment by MariaVWSoundCloud** [comment]
Hi again, I just reinstated it and it should work again. No ticket needed.

**Comment by thesubdelta** [comment]
Thank you @MariaVWSoundCloud for the quick response on this!
