### ISSUE TITLE
POST /tracks return always 401 Unathorized, without any error

### ISSUE THREAD

**Issue by tyctor** [soundcloud/api#273]
Hi 

i am trying to upload new track via soundcloud api

but i am still getting 

```
{"code":401,"message":"","link":"https://developers.soundcloud.com/docs/api/explorer/open-api","status":"401 - Unauthorized","errors":[],"error":null}'
```

i obtained code from **GET connect** 
response from **POST oauth2/token** is 200, and contains access token
but **POST /tracks** is 401, even if i include correct Authorization header (taken from api examples)
and without any error message

this is from python console:

```
from django_punctum.radio.sc_api import SoundcloudAPI
raf = PunctumRadioRadioAudioFile.objects.get(pk=1576)

code = "xxxxx"

> api = SoundcloudAPI(code)
> token = api.oauth2_token()
> token
<Response [200]>
> token.json()
{'access_token': 'yyyy', 'expires_in': 3599, 'refresh_token': 'zzzz', 'scope': '', 'token_type': 'bearer'}
> resp, preq = api.tracks(raf)
> resp
<Response [401]>
> resp.json()
{'code': 401, 'message': '', 'link': 'https://developers.soundcloud.com/docs/api/explorer/open-api', 'status': '401 - Unauthorized', 'errors': [], 'error': None}
> preq.headers
{'Accept': 'application/json; charset=utf-8', 'Authorization': 'xxxx', 'Content-Length': '23101958', 'Content-Type': 'multipart/form-data; boundary=e8df0490ed7d4d4b8f7fdb35f53a7602'}
```

where can be problem?

**Comment by mgoodfellow** [comment]
Hi, 

I would quickly remove your access_token and refresh_token from these examples!

**Comment by mgoodfellow** [comment]
Is this the package you are using? https://github.com/soundcloud/soundcloud-python

If so it is deprecated, and might not be sending the tokens in the headers in the correct format, the authorization flow was changed a few years ago - before the token was passed differently (body I believe), now it is in the header as a bearer token - this library might not support that new approach.

**Comment by mgoodfellow** [comment]
Looks to me like it's sending the `oauth_token` in the body of the request which was deprecated a few years ago: https://github.com/soundcloud/soundcloud-python/blob/master/soundcloud/request.py

**Comment by mgoodfellow** [comment]
Sorry:

```
> preq.headers
{'Accept': 'application/json; charset=utf-8', 'Authorization': '2-XXXXXX-XXXXXXX-XXXXXXXX', 'Content-Length': '23101958', 'Content-Type': 'multipart/form-data; boundary=e8df0490ed7d4d4b8f7fdb35f53a7602'}
```

Header should be:

```
Authorization: OAuth 2-XXXXXXX-XXXXXXX
```

You aren't sending the header correctly (missing OAuth prefix)

**Comment by tyctor** [comment]
thanks for reply, i will try
but i followed examples on api doc, so probably example is also wrong

**Comment by mgoodfellow** [comment]
The response snippet you shared shows the authorization header is not being sent in the correct format. I'm not sure what other attempts you have tried or tools used, but that specific example you have shared does not match the API docs.

I'm also not sure what library you are using or the approach you have taken, I'm just working from the output in your examples as this is the information I have to work with.

I strongly urge you edit your initial post and omit the access_token and refresh_token. This is private information and must not be posted on public forums. This will provide anyone who comes across this post with access to the linked account.

**Comment by tyctor** [comment]
ok, so i added OAuth prefix to headers

get token:
```
curl -X POST "https://api.soundcloud.com/oauth2/token" \
      -H  "accept: application/json; charset=utf-8" \
      -H  "Content-Type: application/x-www-form-urlencoded"  \
      --data-urlencode "grant_type=client_credentials"   \
      --data-urlencode "client_id=xxxxxxx"   \
      --data-urlencode "client_secret=yyyyyyy"
```

response:
```
{"access_token":"2-xxxxxx--xxxxxxxxxxxxx","expires_in":3599,"refresh_token":"xxNxxxxxxxxxxxxxxx","scope":"","token_type":"bearer"}
```

use token:
```
curl -X 'POST'   'https://api.soundcloud.com/tracks' \
  -H 'accept: application/json; charset=utf-8' \
  -H 'Authorization: OAuth 2-xxxxxx--xxxxxxxxxxxxx' \
  -H 'Content-Type: multipart/form-data' \
  -F 'track[permalink]=https://soundcloud.com/radiopunctum/test'  \
 -F 'track[release]='   -F 'track[release_date]='   -F 'track[tag_list]=' \
  -F 'track[genre]='   -F 'track[downloadable]=false'   -F 'track[license]='  \
 -F 'track[description]='   -F 'track[sharing]=private'   -F 'track[isrc]=' \
  -F 'track[streamable]=false'  \
 -F 'track[asset_data]=@20200125_Trauma_short.mp3;type=audio/mpeg' \
  -F 'track[commentable]=true'  \
 -F 'track[title]=test'   -F 'track[label_name]=' \
  -F 'track[artwork_data]='   -F 'track[embeddable_by]=none' \
  -F 'track[purchase_url]='
```

response:
```
{"code":401,"message":"","link":"https://developers.soundcloud.com/docs/api/explorer/open-api","status":"401 - Unauthorized","errors":[],"error":null}
```

**Comment by mgoodfellow** [comment]
Hi,

So I was under the impression from your initial post that you were using the authorization code flow where a particular user goes through the SoundCloud connect webpage and connects with your app. This would allow your app to use the SoundCloud API in a user context (calling /me for example, or uploading to a users page)

The latest example you have shown is the client credentials flow - this gives your app SoundCloud API access but with no user context - you can do things like calling /users/12345 and getting hack data, but you are calling the API as an app, not as a user, so you cannot call /me (you would get a 401) and you cannot upload/edit tracks, create/edit playlists etc.

I hope this helps

**Comment by tyctor** [comment]
ok, undersand, I misread the documentation
now it is working
