### ISSUE TITLE
Stats are all off... 

### ISSUE THREAD

**Issue by KlungoS** [soundcloud/api#275]
## Title: Cannot retrieve all tracks for a user
Issue found of: September 20th, 2020

### Endpoint(s):
* `GET /users/{id}/tracks`

### Scope(s):
* None (application is not using authentication i.e., implicit flow)

### Steps to reproduce:
```bash
curl --request GET \
  --url 'https://api.soundcloud.com/users/12345/tracks?limit=1&linked_partitioning=true&client_id=DONT_SHARE_CLIENT_ID'
```

### Expected behaviour:
A list of tracks as described at `https://developers.soundcloud.com/docs/api/reference#users`.

### Actual behaviour:
500 Server Error (consistently)

**Comment by youssefhassan** [comment]
Hey @KlungoS, it seems that you don't have access to APIs. Please apply for API access if you have a valid use case.
