### ISSUE TITLE
Feature Request: Be able to search albums & get albums of user

### ISSUE THREAD

**Issue by polvallverdu** [soundcloud/api#276]
There's methods to get playlists (sets) of users and for searching them, but they are not filtered as albums (like in-app or in the browser). Also, would be great if data like upc of the album is provided.

**Comment by MariaVWSoundCloud** [comment]
Thank you for your input - we do have album search but only on the partner API. I will take it with the team to see, if it could be extended for users/albums and be added to public API, but no promise. :)

**Comment by polvallverdu** [comment]
Thank you for the response @MariaVWSoundCloud . I've checked and I need more stuff that's inside the Partners API. I think my application can be beneficial for Soundcloud, and vice-versa. Can you redirect me to the email or phone I should get in contact with?

**Comment by MariaVWSoundCloud** [comment]
Unfortunately I cannot disclose email addresses here, but if you could contact us through a support ticket, I will look out for it and we can connect.

**Comment by polvallverdu** [comment]
No problem 😄 . I just submitted a ticket. Thank you!
