### ISSUE TITLE
artists.soundcloud.com

### ISSUE THREAD

**Issue by pma-90** [soundcloud/api#277]
https://secure.soundcloud.com/web-auth?redirect_uri=https%3A%2F%2Fartists.soundcloud.com&response_type=code&code_challenge=PmmLtVuLDNQ8s-yb9505GzUCOZOP65bO3C1nBiJB8LI&code_challenge_method=S256&state=eyJub25jZSI6IkJZc1VoejdFZ29qY0VDOHBXYnd0dUx0bGozajJHbVdvRFN2dVF5fmMzUldBb1ZSenIzaDRGQkI1RU1SWWl4MG8iLCJjbGllbnRfaWQiOiIzUTM0S0tjM0dMZWFMY0p1OFlKZjdtUmpURlVPNjJiMSIsInJlZGlyZWN0QWZ0ZXJMb2dpbiI6Ii8ifQ%3D%3D&client_id=3Q34KKc3GLeaLcJu8YJf7mRjTFUO62b1&device_id=&origin=artists.soundcloud.com&theme=prefers-color-scheme&ui_evo=true&app_id=314153&tracking=local

**Comment by pma-90** [comment]
> https://secure.soundcloud.com/web-auth?redirect_uri=https%3A%2F%2Fartists.soundcloud.com&response_type=code&code_challenge=PmmLtVuLDNQ8s-yb9505GzUCOZOP65bO3C1nBiJB8LI&code_challenge_method=S256&state=eyJub25jZSI6IkJZc1VoejdFZ29qY0VDOHBXYnd0dUx0bGozajJHbVdvRFN2dVF5fmMzUldBb1ZSenIzaDRGQkI1RU1SWWl4MG8iLCJjbGllbnRfaWQiOiIzUTM0S0tjM0dMZWFMY0p1OFlKZjdtUmpURlVPNjJiMSIsInJlZGlyZWN0QWZ0ZXJMb2dpbiI6Ii8ifQ%3D%3D&client_id=3Q34KKc3GLeaLcJu8YJf7mRjTFUO62b1&device_id=&origin=artists.soundcloud.com&theme=prefers-color-scheme&ui_evo=true&app_id=314153&tracking=local

**Comment by fabianbernhart** [comment]
HINT: Please dont show Client ID @pma-90 

Please close issue: @dasha-kobzeva, @rahulrumalla, @anrock-sc, @remover, @dziemba

**Comment by fabianbernhart** [comment]
@MariaVWSoundCloud
