### ISSUE TITLE
Can we pay for a rate limit increase?

### ISSUE THREAD

**Issue by antoinerousseau** [soundcloud/api#284]
Hi 👋🏼 

We're using your API and it's great! It allows our users to play the most popular song of an artist in our app, which is great for people browsing events and wanting to have an idea of the music style and mood before going.

Thing is, our player is getting popular and we now reached 20k+ stream requests per day, which means only the first 15k work, and the rest get rejected by the `429 Too Many Requests`. Fair enough.

Now, I was wondering if there was any way we could get a bigger quota?
I'm also considering caching the stream on our side but it seems tricky (and I'm not sure it's even allowed).

Thanks for your help and for the awesome API!

Antoine at [shotgun.live](https://shotgun.live/)

**Comment by obrhoff** [comment]
Caching is not allowed by the ToC of the api.

**Comment by tinyscratch** [comment]
@antoinerousseau  Did you get any updates on paid api ?

**Comment by MariaVWSoundCloud** [comment]
Hi there - we do offer paid API access with our extended partner API - please reach out to our support and they will redirect you to start the conversation with our Business Development team.

**Comment by tinyscratch** [comment]
> Hi there - we do offer paid API access with our extended partner API - please reach out to our support and they will redirect you to start the conversation with our Business Development team.

I raised a ticket with the support team but haven't received any reply for a long time

**Comment by antoinerousseau** [comment]
Fyi, I received this two weeks ago:

> Hey there,
> We’d like to let you know that it will still take us a little longer to get back to you because we’re currently dealing with a high number of requests regarding payments and billing - we apologize for keeping you waiting.
> Please know that we’re working hard to answer you as soon as possible. Don’t worry, your request will be reviewed so you don’t have to resubmit it.
> In the meantime, please check out our [Help Center](https://help.soundcloud.com/hc/categories/360004057534), you might be able to find what you’re looking for.
> Thank you for your patience.
> Best,
> The SoundCloud Support Team

**Comment by antoinerousseau** [comment]
2 months later: absolutely no answer to my emails, wtf?

**Comment by MariaVWSoundCloud** [comment]
Hi, I searched our ticket system, but couldn't find the ticket - would you mind just providing the ticket ID? Nobody can use it outside of our system, so should be safe...

**Comment by antoinerousseau** [comment]
Hi @MariaVWSoundCloud, my ticket number is 2799664

<img width="1090" alt="Screenshot 2024-05-24 à 10 59 38" src="https://github.com/soundcloud/api/assets/160279/e27869af-1b30-41a5-8ff2-2bf9c75bae28">

Feel free to start a discussion with me at antoine.rousseau@shotgun.live

Thanks!
