### ISSUE TITLE
Adding a secondary redirect_uri or another app for our staging envionment

### ISSUE THREAD

**Issue by ponny** [soundcloud/api#287]
Hi Soundcloud team!

We've got a couple of apps.  One's for production and one's for our dev/local environment:
<img width="630" alt="image" src="https://github.com/soundcloud/api/assets/134539/f640a2a5-ff3b-41bb-b49c-0e8e11c7415a">

Unfortunately, we've also got a staging environment but the url (https://staging.gleam.io/) is different so our current redirect_uris don't work.  Would it be possible to add another redirect uri (staging.gleam.io/auth/soundcloud/callback) or add another app that has that has that redirect_uri?  As it stands, we can't test SoundCloud login in our staging env.  We've already got the app going app and this extra environment would create very little traffic (probably a few requests every month) so I hope this wouldn't be a problem.

**Comment by fabianbernhart** [comment]
Isn't it possible to create another account.

**Comment by ponny** [comment]
> Isn't it possible to create another account.

Yep, thinking that might be the case.  Another app possible?

**Comment by ponny** [comment]
> Hi, this is a perfect question for the SoundCloud support team :) Please open a ticket and we can take a look

Sure.  I thought this was the place.  Where should I go?

**Comment by sabato-galasso** [comment]
@MariaVWSoundCloud
I have opened some tickets regarding the redirect url to change? can you help me please I would be very grateful. thanks in advance
Ticket: 3074107
Ticket: 3074098

**Comment by MariaVWSoundCloud** [comment]
This is done ✅
