### ISSUE TITLE
Cannot retrieve access_token and refresh_token from new OAuth 2.1 /oauth/token endpoint

### ISSUE THREAD

**Issue by azimpradhan** [soundcloud/api#293]
## Title: Cannot retrieve access_token and refresh_token from new OAuth 2.1 /oauth/token endpoint
Issue found on: May 22nd, 2024

### Endpoint(s):
* `POST https://secure.soundcloud.com/oauth/token`

### Scope(s):
* Authorization Code Flow

### Steps to reproduce:
```bash
curl -X POST "https://secure.soundcloud.com/oauth/token" \
     -H  "accept: application/json; charset=utf-8" \
     -H  "Content-Type: application/x-www-form-urlencoded" \
     --data-urlencode "grant_type=authorization_code" \
     --data-urlencode "client_id=YOUR_CLIENT_ID" \
     --data-urlencode "client_secret=YOUR_CLIENT_SECRET" \
     --data-urlencode "redirect_uri=YOUR_REDIRECT_URI" \
     --data-urlencode "code_verifier=YOUR_PKCE_GENERATED_CODE_VERIFIER" \
     --data-urlencode "code=YOUR_CODE"
```

### Expected behaviour:
The returned object has an access_token property and a refresh_token property as well as expires_in and scope.

### Actual behaviour:
400 Server Error (consistently)
Response body is
```
{
    "error": "invalid_request"
}
```

### Additional notes
* The call to authorize succeeds and I am redirected back to my app after connecting my SoundCloud account and the `code` and `state` are present in the query_params as expected. The part that is failing is the call to https://secure.soundcloud.com/oauth/token

* In order to generate my code_verifier and code_challenge, I followed the exact steps outlined here:
https://auth0.com/docs/get-started/authentication-and-authorization-flow/authorization-code-flow-with-pkce/add-login-using-the-authorization-code-flow-with-pkce

Specifically. this is how I am generating my code_verifier and code_challenge:

```
let crypto;
try {
  crypto = require("crypto");
} catch (err) {
  console.log('Run $npm install first!');
}

function base64URLEncode(str) {
  return str.toString('base64')
      .replace(/\+/g, '-')
      .replace(/\//g, '_')
      .replace(/=/g, '');
}
const verifier = base64URLEncode(crypto.randomBytes(32));
console.log("Code verifier: ", verifier);

function sha256(buffer) {
  return crypto.createHash('sha256').update(buffer).digest();
}
const challenge = base64URLEncode(sha256(verifier));
console.log("Code challenge: ", challenge);
```

If there are other requirements around the code_verifier and challenge please share so that we can get this resolved before the October deadline.

**Comment by azimpradhan** [comment]
It turns out that I was not properly encoding the data as url params. I am going to close this since it is not a bug/issue.

**Comment by eddpot** [comment]
> It turns out that I was not properly encoding the data as url params. I am going to close this since it is not a bug/issue.

I'm stuck here too. Any chance you'd be willing to share how you handled the encoding? Thanks :-)
