### ISSUE TITLE
Registered apps have been automatically deleted

### ISSUE THREAD

**Issue by icreatestuff** [soundcloud/api#294]
Hello, 

As of a week or so ago the registered apps in a couple of different accounts we manage have been deleted, but not by anyone within our team, so we can no longer authorize with the API.

I have opened tickets within each of the affected accounts but have heard nothing in over a week. The relevant ticket ID numbers are #2920730 and #2920784

We would appreciate a prompt response.
Many thanks

**Comment by o8e** [comment]
Mine have also randomly disappeared. Did you have any luck?

**Comment by icreatestuff** [comment]
@o8e They eventually got back to me through the tickets I'd opened. Probably took them about a week to respond, but the apps were eventually added back.

**Comment by icreatestuff** [comment]
Hello, we've had another app mysteriously disappear. 

I've opened a new support ticket but have not heard anything for nearly 2 weeks. Ticket number is #3239479

Would be grateful if someone from Soundcloud could take a look. Thanks
