### ISSUE TITLE
Authorize "display=popup" not working

### ISSUE THREAD

**Issue by blackarcanis** [soundcloud/api#298]
Hi!
We noticed while opening the new "Authorize" login URL, that the parameter "display=popup" is not working well.
The design is not well made for a popup (missing some padding at least): 
![SoundCloudAuthorize](https://github.com/soundcloud/api/assets/12633490/4b0a6220-b9e8-4733-930f-9ef8b775bf81)

Any fix to come or maybe the name of the parameter/value is not the correct one?
Thank you!

**Comment by youssefhassan** [comment]
A fix was deployed recently to fix the issue, please let us know if the problem is solved @blackarcanis
