### ISSUE TITLE
Feature Request: Ability to see what users have reposted a track

### ISSUE THREAD

**Issue by mgoodfellow** [soundcloud/api#3]
## Feature Request: Ability to see what users have reposted a track

Currently the reposters of a track can be retrieved via the v2 endpoint:

* `GET https://api-v2.soundcloud.com/tracks/{trackId}/reposters`
* `GET https://api-v2.soundcloud.com/playlists/{trackId}/reposters`

It would be great to able to access this information via the v1 public API.

**Comment by dasha-kobzeva** [comment]
Hello @mgoodfellow,

regarding your request about `tracks/playlist reporters` would receiving user ids be sufficient for your use case? 
Something like `/reposters/ids` ?

Thank you

**Comment by mgoodfellow** [comment]
Hi @dasha-kobzeva 

Yes, that would work perfectly for us. 

Thanks!

**Comment by dasha-kobzeva** [comment]
great! Thank you for a quick reply, I will keep you posted when the feature goes live.

**Comment by dasha-kobzeva** [comment]
Hello @mgoodfellow,

please find 2 new endpoints to fetch reposters:
* track: https://developers.soundcloud.com/docs/api/explorer/open-api#/tracks/get_tracks__track_id__reposters
* playlist: https://developers.soundcloud.com/docs/api/explorer/open-api#/playlists/get_playlists__playlist_id__reposters
