### ISSUE TITLE
Soundcloud upload a new Track api doesn't work

### ISSUE THREAD

**Issue by kejul-vyas-mck** [soundcloud/api#300]
## Title: Cannot upload audio on Soundcloud via /tracks api
Issue found of: 28th June, 2024

### Endpoint(s):
* `POST /tracks`

### Scope(s):
we are using Client Credentials Token Exchange Flow where we refresh token and get new access token on each request

### Steps to reproduce:
curl -X 'POST' \
  'https://api.soundcloud.com/tracks' \
  -H 'accept: application/json; charset=utf-8' \
  -H 'Authorization: OAuth *' \
  -H 'Content-Type: multipart/form-data' \
  -F 'track[sharing]=public' \
  -F 'track[asset_data]=@The-state-of-US-womens-heart-health-A-path-to-improved-health-and-financial-outcomes.mp3;type=audio/mpeg' \
  -F 'track[title]=test'

### Expected behaviour:
Should upload audio file to our Soundcloud account

### Actual behaviour:
503  Server Error (consistently)
<img width="862" alt="api-error" src="https://github.com/soundcloud/api/assets/91284757/ef7263ec-b20a-40e5-b604-47232b43b812">

**Comment by youssefhassan** [comment]
@kejul-vyas-mck does the issue still persist?

**Comment by kejul-vyas-mck** [comment]
nope all good now, thanks!
