### ISSUE TITLE
Universal links to open exact app screens in iOS app

### ISSUE THREAD

**Issue by lmurtazaev** [soundcloud/api#303]
Hi there,

I was wondering if the SoundCloud iOS app supports deeplinking. We would like to use a universal link that opens the SoundCloud app directly on the **Library** > **Your Uploads** screen. 
The idea is to let users share content from my app to SoundCloud and after a successful share, it would be great to redirect a user to SoundCloud to the exact screen where their shared music appears.

**Comment by youssefhassan** [comment]
The permalink of a track should deep link into the SoundCloud app or mobile web
