### ISSUE TITLE
Request for Paid API Access

### ISSUE THREAD

**Issue by tusharhatwar1997** [soundcloud/api#305]
I am writing to inquire about obtaining access to the paid version of the SoundCloud API. I am eager to integrate your services into my project and would like to explore the options available for paid access.

I have previously submitted a support ticket but have not yet received a response. I am willing to proceed with the payment and any necessary steps to get started as soon as possible.

Could you please provide me with the relevant details on how to access the paid API, including any pricing information, terms, and conditions? 

Thank you for your assistance. I look forward to your prompt response.

**Comment by MariaVWSoundCloud** [comment]
Hi @tusharhatwar1997 - can you please open a support ticket and post the ID here? I will take care of it.

**Comment by sabato-galasso** [comment]
Hi @MariaVWSoundCloud , I have the same problem, I have a paid Next Pro plan and I would like to use the API for my project that already has many active users, I have already opened a ticket many months ago but I have not had an answer, can you help me, I would be grateful. thanks
Ticket: 2984619

**Comment by MariaVWSoundCloud** [comment]
@sabato-galasso Done! ✅
