### ISSUE TITLE
/me endpoint retuning 404 page not found for user context

### ISSUE THREAD

**Issue by mgoodfellow** [soundcloud/api#307]
As of 14:39 UTC, all calls to /me are returning 404 not found.

RAW:

```
404 page not found
```

With 404 HTTP status code.

It seems this endpoint is being answered by a new server, `envoy` which isn't behaving correctly.

Example call to /users/1719302:

![image](https://github.com/user-attachments/assets/35425f06-8250-4cf1-a465-25d47cdd425f)

Whereas, the /me endpoint now gets answered by a new server:

![image](https://github.com/user-attachments/assets/4f58691c-807e-4d12-92d0-50d4d8b5e08b)

Might be related to the issues seen across the API earlier: https://github.com/soundcloud/api/issues/306

**Comment by mgoodfellow** [comment]
This endpoint is now returning:

```
{
    "code": 200,
    "message": "unable to decode response",
    "link": "https://developers.soundcloud.com/docs/api/explorer/open-api",
    "status": "200 - unable to decode response",
    "errors": [],
    "error": null
}
```

It appears something is going wrong with a rollout of a new component.

**Comment by youssefhassan** [comment]
Hello, we were deploying a change yesterday and we had a couple of minutes of disruption. Are you still having problems with the requests?

**Comment by mgoodfellow** [comment]
Hi @youssefhassan,

The problems are resolved. The latter failure mode was unfortunate because the response started returning 200 codes, but with unexpected JSON payloads.

We use the /me endpoint during login to get the user context and to test a token for validity so it caused issues with logins and refresh flows yesterday.

Appreciate the response!

Mike
