### ISSUE TITLE
Seeing lots of 504 'Gateway Timeout' on users/{user_id}/likes/tracks API

### ISSUE THREAD

**Issue by azimpradhan** [soundcloud/api#308]
## Title: Cannot retrieve liked tracks of a user
Issue found of: August 20th, 2024

### Endpoint(s):
* `GET users/{id}/likes/tracks`

### Scope(s):
* OAuth (application is not using oauth 2.1 pkce flow)

### Steps to reproduce:
```bash
curl --request GET \
  --url 'https://api.soundcloud.com/users/21395965/likes/tracks?limit=200&linked_partitioning=1'
```

### Expected behaviour:
A list of tracks as described at `https://developers.soundcloud.com/docs/api/explorer/open-api#/users/get_users__user_id__likes_tracks`.

### Actual behaviour:

504 Server Error (more than 90% of the time)

response body is text
`upstream request timeout`

**Comment by youssefhassan** [comment]
Hey @azimpradhan,  thank for reporting. There was an issue and it's resolved now. Can you try again and confirm that all is clear?

**Comment by youssefhassan** [comment]
Can you please share which application or user owns the soundcloud application to be able to debug the issue?

**Comment by azimpradhan** [comment]
> Hey @azimpradhan, thank for reporting. There was an issue and it's resolved now. Can you try again and confirm that all is clear?

seems to be fixed. thank you!

**Comment by azimpradhan** [comment]
Sure, the app id is `b2a4ebae4c9502b1aba2d9a0119d5ac6`
