### ISSUE TITLE
The /users/{user_id}/tracks API is returning an invalid next_href

### ISSUE THREAD

**Issue by azimpradhan** [soundcloud/api#309]
## Title: The /users/{user_id}/tracks API is returning an invalid next_href
Issue found of: August 20th, 2024

### Endpoint(s):
* `GET /users/{id}/tracks`

### Scope(s):
* OAuth 2.1 (pkce flow)

### Steps to reproduce:
```bash
curl --request GET \
  --url 'https://api.soundcloud.com/users/1098233644/tracks?linked_partitioning=1&limit=50'
```

### Expected behaviour:
The next_href response from the URL should contain a valid link to the next page of data as described in the documentation here:
https://developers.soundcloud.com/docs/api/guide#pagination
and I should be able to fetch the next page of data by making a GET request to the url provided in NEXT_HREF

### Actual behaviour:
The next_href in the response has a different domain:
`https://http.api.prod.api-public.srv.db.s-cloud.net`
The entire next_href looks like this:
`https://http.api.prod.api-public.srv.db.s-cloud.net/users/1098233644/tracks?cursor=2024-01-09T21%3A10%3A04.000Z%2Ctracks%2C01712964786&linked_partitioning=1&page_size=50`

When attempting to fetch the data by using the link above, I am getting a DNS error:

Error: getaddrinfo ENOTFOUND http.api.prod.api-public.srv.db.s-cloud.net

**Comment by youssefhassan** [comment]
Hey @azimpradhan,  thank for reporting. There was an issue and it's resolved now. Can you try again and confirm that all is clear?

**Comment by azimpradhan** [comment]
Yes, this seems to be fixed. thank you!
