### ISSUE TITLE
Increase in error rate last 24 hours - 503s upstream errors

### ISSUE THREAD

**Issue by mgoodfellow** [soundcloud/api#311]
Hi,

We have seen an increase in 503s in the last 24 hours, seeing quite a lot of sporadic 503s with the folllowing content:

```upstream connect error or disconnect/reset before headers. reset reason: remote connection failure, transport failure reason: delayed connect error: 113```

Often retries succeed with these.

We have also seen some spikes of the following:

```upstream connect error or disconnect/reset before headers. reset reason: connection termination```

These seem to align with short outages and retries don't succeed.

I notice the baseline of 503s and timeouts have increased since the 20th August - I'm not sure if this aligns with any internal changes?

Last 30 days, 1d buckets

<img width="1018" alt="image" src="https://github.com/user-attachments/assets/5cf538a1-2429-4a7d-8576-3146bcff4fe3">

Last 24 hours, 30m buckets

<img width="1023" alt="image" src="https://github.com/user-attachments/assets/78ec768d-61d4-4e71-b95c-e8831fb8c323">

Cheers!

**Comment by mgoodfellow** [comment]
As of the 30th August, we are now seeing significant increase in 504s (gateway timeout), 502s (bad gateway) as well as the continued elevated 503s.

The average response time of the API has deteriorated since 30th August at around 5pm UTC time.

Last 48hrs, 1h buckets:

![image](https://github.com/user-attachments/assets/778aaac6-3e7e-4b75-a2d3-fd9e90373a8c)


API response times in the same period:

![image](https://github.com/user-attachments/assets/abb7f8df-c135-4e91-bff2-8c850964f4a8)


A lot of these actions fail even after retries.

**Comment by youssefhassan** [comment]
Hey, thanks for reporting. I reverted some of the changes that were done on the 30th of August and we will investigate further next week. Please let us know if possible if it was specific to some endpoints or for all endpoints used. Cheers

**Comment by mgoodfellow** [comment]
Hi @youssefhassan 

That rollback resolved the spiking error rate experienced on the 30th August, and we are back to the baseline increased 503 error rate I initially mentioned when I opened this ticket with that sporadic error: `upstream connect error or disconnect/reset before headers. reset reason: remote connection failure, transport failure reason: delayed connect error: 111`

I've had a look at the failure rate across the API endpoints, and it seems that nearly all endpoints we use were affected (tracks, profiles, reposts, likes, comments etc), and across all methods (GET/POST/etc). Unaffected endpoints were authentication endpoints for users and server tokens.

Please let me know if you require any additional information!

**Comment by youssefhassan** [comment]
Hey @mgoodfellow, thanks for all the info, we identified the issue and we won't deploy the change again until we resolve the problem with the 500s responses
