### ISSUE TITLE
Is /oauth2/token deprecated ahead of schedule

### ISSUE THREAD

**Issue by superturboryan** [soundcloud/api#312]
# Users reporting they can no longer log in

### Example screenshot from user report:
<img width="617" alt="Screenshot 2024-09-03 at 23 41 14" src="https://github.com/user-attachments/assets/78c99307-efad-4d8c-92bd-776b8f55682d">

## Issue found of: 1 September 2024

I saw the post on the developer blog by Jordan about the migration to OAuth 2.1. It mentions we should plan to accommodate this new version of the protocol by 1 October, but perhaps that has changed?

https://developers.soundcloud.com/blog/oauth-migration

Endpoint(s):
### Scope(s):
* Users can no longer log in - this is critical for my app ‼️

**Comment by alexweinstein** [comment]
Same for me.

**Comment by superturboryan** [comment]
cc @MariaVWSoundCloud

**Comment by youssefhassan** [comment]
Hey @superturboryan, first sorry for the inconvenience, it's not related to deprecation. We were deploying changes to our infrastructure that might have affected the authentication in this case, can you confirm the problem is resolved now? And if you have more details of the errors that were happening, we would appreciate that in order to debug the issue. Thanks

**Comment by superturboryan** [comment]
Thanks for looking into this so quickly @youssefhassan ! 🤝
All systems green 🟢
<img width="859" alt="Screenshot 2024-09-05 at 05 06 08" src="https://github.com/user-attachments/assets/d459dda7-9ee8-427b-95ce-7ad239cdee9a">

**Comment by youssefhassan** [comment]
Hey @superturboryan and @alexweinstein , can you please share the soundcloud account with the application or the applciation name that had the errors in order to be able to debug the issue further, thanks.

**Comment by alexweinstein** [comment]
> Hey @superturboryan and @alexweinstein , can you please share the soundcloud account with the application or the applciation name that had the errors in order to be able to debug the issue further, thanks.

Thanks @youssefhassan. After this issue report, I took the opportunity to migrate to OAuth 2.1. So I’m good now.

**Comment by youssefhassan** [comment]
Resolved

**Comment by superturboryan** [comment]
@youssefhassan it's linked to this issue
