### ISSUE TITLE
Baseline error rate of 503 errors still above previous baseline pre-August 20th

### ISSUE THREAD

**Issue by mgoodfellow** [soundcloud/api#314]
Hi, 

Related to: https://github.com/soundcloud/api/issues/311

We are still seeing an increased error rate on the API:

![image](https://github.com/user-attachments/assets/7cfea1af-d334-4b1f-8ec8-edb7ab019caf)

These started around the 20th August and have been ongoing.

The errors are in one of 2 forms:

`upstream connect error or disconnect/reset before headers. reset reason: remote connection failure, transport failure reason: delayed connect error: 113`

OR

`upstream connect error or disconnect/reset before headers. reset reason: remote connection failure, transport failure reason: delayed connect error: 111`

Retries often work, and they are sporadic and spikey - so we generally see the errors clustered:

![image](https://github.com/user-attachments/assets/fcee59db-eea9-402d-9f89-a43c46187bff)

We are seeing these errors on Tracks, Reposts, Profiles primarily. It affects both read-only (GET) and mutation endpoints (PUT / POST etc).

Would be good to understand these as we don't retry mutations, only idempotent reads.

**Comment by mgoodfellow** [comment]
Hi @youssefhassan 

Seeing a spike again in error rates of 503s, with the delayed connect error 113:

![image](https://github.com/user-attachments/assets/f4adc385-7226-41d3-a977-dc0676f5dc54)

Also seeing spikes in response times across most endpoints.

**Comment by mgoodfellow** [comment]
Seems to be recovering again, the spike was from 16:48 -> 17:26 UTC time. Response times are now recovering as well.

**Comment by mgoodfellow** [comment]
Hi @youssefhassan 

We are seeing massively elevated error rates and timeouts starting at around 16:00 UTC on the 1st Oct:

![image](https://github.com/user-attachments/assets/b36db485-550c-43c0-8bf1-b51c5605c124)

This issue is currently ongoing.

In addition, starting at around 20 minutes ago (around 8am UTC), we are seeing a high rate of 404s on track and playlist endpoints. When I check the resources by hand they all exist on SoundCloud, so I'm not sure why the API is reporting 404s - it might be due to an internal service locator issue.

The problem here is that it is corrupting our caches as we record that track as missing to avoid re-requesting it constantly from the API. Could this be investigated ASAP please?

**Comment by youssefhassan** [comment]
Hey @mgoodfellow, apologies for the inconvenience. Can you please let us know how's the status now? Are the high error rates and 404s still happening?

**Comment by mgoodfellow** [comment]
Hi @youssefhassan 

Another cascading failure of 404s happening now, again with these page content of "404 page not found" which makes it seem like more of routing failure than API responses.

In addition we seem to be suffering caching bugs when looking at reposters of tracks where we are seeing massively old stale data that isn't being updated.

**Comment by youssefhassan** [comment]
Hey @mgoodfellow, let me know what is your experience now? 
These two separate issues should be fixed now

**Comment by mgoodfellow** [comment]
Hi @youssefhassan 

We saw a spike yesterday afternoon in the 404 not found bug, and we have also seen a large scale outage starting at 3am UTC today, and still ongoing with loads of endpoints returning 404 not found with the page content set as before (rather than being a pure API status code response) - also leading me to believe it is a service mesh/routing layer issue again.

Thanks

**Comment by mgoodfellow** [comment]
Hi,

Issue resolved around 2pm UTC yesterday.

![image](https://github.com/user-attachments/assets/36727b0e-5bc4-4447-8df5-3fa75900d011)

![image](https://github.com/user-attachments/assets/0f3346f1-91d2-43dd-ac16-c93e84d1b711)

It affects all resources:

/tracks/{id} and subresources (likes, comments, reposters etc.)
/playlists/{id} and subresources (likes, comments, reposters etc.)
/me (this is "AuthChecks" in the above graph)
/users/{id} and subresources

As for scale:

![image](https://github.com/user-attachments/assets/5552e0c2-c688-4640-868c-39b0bcd8507b)

**Comment by youssefhassan** [comment]
Thanks for the detailed report, we are still not able to identify the issue but there was an outage in some datacenter that might have caused the issue. Do you think we still need to keep this ticket opened or we can close it?

**Comment by mgoodfellow** [comment]
Hi @youssefhassan 

Another outage yesterday, 26th Oct, from 14:20 to 22:00 UTC with high failure rates of 404s again. Same issue as before.

<img width="1013" alt="image" src="https://github.com/user-attachments/assets/27f7a590-f5c8-49b0-8587-881ecd1f7b8f">

Again it seems to be internal service mesh routing issue, as the content returned from the API calls is plain text:

```
404 page not found
```

With a status code of 404. 

When we request a resource that doesn't exist normally such as /tracks/999999999 we will receive a 404 with no body content.

**Comment by mgoodfellow** [comment]
Hi @youssefhassan 

Seems there was another outage again last night (early hours this morning) - 29th Oct, 02:00 -> 03:30 UTC time, same issue again with 404s.

<img width="880" alt="image" src="https://github.com/user-attachments/assets/2886a431-ce80-4ddf-afd3-ae2af980c23a">

It would be incredibly useful for us to have advance notice of scheduled maintenance. You might consider using status page io or similar to post work in advance, but even just an email would be appreciated.

However, with regards to these outages, we are getting 404s for resources that exist. This leads to confusion for our users - "Our tracks have disappeared?" etc.

If the API is being taken down for maintenance, it should be returning a 5xx status code letting us know there is a server side issue and we can then handle this disruption with circuit breakers and backoffs, and also let users know there seems to be some disruption at the moment.

With these cascading errors of 404s, as a consumer of the API we have no way of knowing if they are due to a resource not being present, or if this is due to a server outage/maintenance etc. We therefore cannot relay this information to the user and have to assume that all the data we are looking for on SoundCloud, has in fact, been removed.

**Comment by youssefhassan** [comment]
The outage would result in a 404 of page not found i.e unreachable address not a resource not found which definitely confusing. We will look into the status page, it's a good idea.

**Comment by youssefhassan** [comment]
Hey @mgoodfellow, hope you are well. If this seems fine now, can we close the issue?

**Comment by mgoodfellow** [comment]
Hi @youssefhassan, 

Very well thanks, I hope you are too! 

Apologies for not closing this sooner, but yes we haven't seen a recurrence of this issue in a few weeks now. 

Thanks for all your help! 

Mike
