### ISSUE TITLE
POST /tracks endpoint returning 401 consistently

### ISSUE THREAD

**Issue by frank-nankivell** [soundcloud/api#317]
## Title: POST /tracks consistently returns 401
Issue found of: September 12th, 2024

### Endpoint(s):
* `POST /tracks`

Hi Soundcloud. I reached out to your support team on this and they suggested writing an issue here.  We are currently using the API successfully to read data. However when making a POST request to upload a new track we consistently receive a 401. I have been told there are no extra scopes or permissions so wanted to raise this as to why we receive an unauthorised.

See example curl response which always ends in a 401
```bash
curl --location 'https://api.soundcloud.com/tracks' \
--header 'Authorization: ••••••' \
--form 'track[title]="test"' \
--form 'track[asset_data]=@"/Users/example/Music/example/VOCALS/example.wav"'
```

Here is some example node js of it also not working
```
      const response = await axios.post(
        "https://api.soundcloud.com/tracks",
        formData,
        {
          headers: {
            Authorization: `OAuth ${accessToken}`, // Replace with your OAuth token
            "Content-Type": "multipart/form-data",
          },
        }
      );
```

However, with the same token if we call this it works succesfully - so the token and API are confirmed to be working.
```
const data = await axios.get(
        "https://api.soundcloud.com/users/{id}/tracks?limit=1",
        {
          headers: {
            Authorization: `OAuth ${accessToken}`,
          },
        }
      );
```

Can you confirm whether this is an error in how we are using the endpoint, or whether this has some permission issues with it?

Thanks for all your help

**Comment by frank-nankivell** [comment]
Please ignore, thanks

**Comment by sebbean** [comment]
@frank-nankivell i'm having this same issue - any clues?

**Comment by sebbean** [comment]
I believe the answer is we need the user authentication route via oauth if anyone else is lookin

https://github.com/soundcloud/api/issues/339#issuecomment-2439429471
