### ISSUE TITLE
Problem with boolean params for POST tracks

### ISSUE THREAD

**Issue by pierrocknroll** [soundcloud/api#32]
Hi, 
According to this doc https://developers.soundcloud.com/docs/api/explorer/open-api#/tracks/post_tracks
There are some problems with boolean params :
- `commentable` doesn't seem to work. Even if I send `commentable=0`, the API answers with `commentable:True` and the track is commentable.
- `streamable` has a little problem. Even if I send `streamable=0`, the API answers with `streamable:True` (but the track is not streamable).
- `feedable` doesn't work anymore, even if it's not in the documentation, it worked before. How can I activate this option now?

Here are the curl exemple and the answer :
`curl --request POST  --url 'https://api.soundcloud.com/tracks' --header 'Authorization: OAuth X' --header 'Content-Type: multipart/form-data' --form "track[title]=Test" --form "track[asset_data]=@test.mp3" --form "track[commentable]=0" --form "track[streamable]=0"`

->

```{"artwork_url":null,"bpm":null,"comment_count":0,"commentable":true,"created_at":"2021/02/09 09:58:02 +0000","description":null,"download_count":0,"download_url":"https://api.soundcloud.com/tracks/981955642/download","downloadable":false,"duration":0,"embeddable_by":"all","favoritings_count":0,"genre":null,"id":981955642,"isrc":null,"key_signature":null,"kind":"track","label_id":null,"label_name":null,"last_modified":"2021/02/09 09:58:02 +0000","license":"all-rights-reserved","original_content_size":null,"original_format":null,"permalink_url":"https://soundcloud.com/user-831841732/test","permalink":"test","playback_count":0,"purchase_title":null,"purchase_url":null,"release":null,"release_day":null,"release_month":null,"release_year":null,"secret_token":null,"secret_uri":null,"sharing":"public","state":"storing","stream_url":"https://api.soundcloud.com/tracks/981955642/stream","streamable":true,"tag_list":"","title":"Test","track_type":null,"uri":"https://api.soundcloud.com/tracks/981955642","user":{"id":671845643,"kind":"user","permalink":"user-831841732","username":"pierrock","last_modified":"2019/08/21 13:02:30 +0000","uri":"https://api.soundcloud.com/users/671845643","permalink_url":"https://soundcloud.com/user-831841732","avatar_url":"https://a1.sndcdn.com/images/default_avatar_large.png"},"user_favorite":false,"user_id":671845643,"user_playback_count":1,"video_url":null,"waveform_url":"https://wis.sndcdn.com/images/player-waveform-medium.png?1612442102"}'```

Thanks a lot

**Comment by rahul-sc** [comment]
We pushed out a fix for "streamable". Thanks for reporting this. Please verify. 

Although, commentable is part of "quiet mode" i.e., for Pro U subscribers only. 
Feedable is something we don't support via API.

**Comment by pierrocknroll** [comment]
It's OK for `streamable`, thank you.
