### ISSUE TITLE
403 - Forbidden (Auth is valid)

### ISSUE THREAD

**Issue by StefCoders** [soundcloud/api#320]
### Endpoint(s):
* `GET /me/playlists`

### Scope(s):
* None (application is not using authentication i.e., implicit flow)

### Steps to reproduce:
```bash
curl -X GET "https://api.soundcloud.com/me/playlists?show_tracks=false&linked_partitioning=true&limit=25" \
       -H  "accept: application/json; charset=utf-8" \
       -H "Authorization: xxxxxxxxxx"'
```

### Expected behaviour:
A list of tracks as described at `https://developers.soundcloud.com/docs/api/reference#users`.
```
{
  "collection": {
    "$ref": "#/components/examples/Playlist/value"
  },
  "next_href": "https://api.soundcloud.com/collection?page_size=10&cursor=1234567"
}
```

### Actual behaviour:
{"code":403,"message":"","link":"https://developers.soundcloud.com/docs/api/explorer/open-api","status":"403 - Forbidden","errors":[],"error":null}r

**Comment by youssefhassan** [comment]
What is this date of Sept. 20, 2020?

**Comment by StefCoders** [comment]
This is what disturbed you? I need answers please not unnecessary comments.

**Comment by youssefhassan** [comment]
I was trying to debug, it could be something with timestamps or an older trace by mistake.
Can you share your soundcloud username or app id? to try to reproduce.

**Comment by StefCoders** [comment]
There is no app id as SoundCloud stopped making app id applications over 3 years ago.  Not sure about my username.

**Comment by youssefhassan** [comment]
Public APIs has to be accessed with external applications. You can apply for an application and it will be granted if there's a use case. Which token are you using and expecting it to work?
