### ISSUE TITLE
How can I get SoundCloud API Access

### ISSUE THREAD

**Issue by bhathiyaudara** [soundcloud/api#323]
Dear SoundCloud Support Team,

I hope this message finds you well.

I am writing to request access to the SoundCloud API for a new application I am developing called GrooveSound Integrator. Below are the details of the application:
App Description: this app designed to help artists better manage and engage with their SoundCloud content. The app will provide tools for organizing music libraries, analyzing track performance, and facilitating deeper interaction with their audience. By using this app, artists can streamline their workflow and make more informed decisions based on detailed insights.Intended Use of the API: The API will be used to retrieve track statistics, manage playlists, and integrate SoundCloud content into a unified dashboard for easier access and analysis by artists.

I would greatly appreciate your assistance in registering this app and providing the necessary “Client ID” and “Client Secret” codes.

Thank you for your time and consideration. I look forward to your response.

**Comment by MariaVWSoundCloud** [comment]
Hi - please open a support ticket through our website and we will be able to help you. Best, Maria
