### ISSUE TITLE
Rate limits on "muting" users

### ISSUE THREAD

**Issue by RuinedYourLife** [soundcloud/api#327]
## Title: Rate limits on "muting" users
Issue found of: September 30th, 2024

### Endpoint(s):
* `PUT /me/mutings/soundcloud:users:{id}`

### Scope(s):
* User auth

### Steps to reproduce:
```bash
curl --request GET \
curl "https://api-v2.soundcloud.com/me/mutings/soundcloud:users:{id}?reported=true&remove_activities=true&client_id=client_id&app_version=1727431820&app_locale=en" ^
  -X "PUT" ^
  -H "Accept: application/json, text/javascript, */*; q=0.1" ^
  ...
  -H "Authorization: OAuth token" ^
  ...
```

### Expected behaviour:
Blocks the user.

### Actual behaviour:
429

Hey there,

I know this is not the right place for this, but it appears to be the only place that people are replying.
I have tried to contact the support the past month to no avail.

I have a bunch of bots streaming/following/liking/reposting my tracks, and since the support is not replying, I tried blocking them myself.
Ofc, I am not blocking 4k accounts by hand, so I wrote something to do this for me.
Except now I get rate limited.
- How many of these requests can I send before getting rate limited?
- Isn't there a way around it?
- Can I get someone to help me with this (it might have messed up my "algorithm" or whatever)?

If needed, I can share my code / the list of accounts I collected that do not look legit (based on follower count and profile picture only) that I gathered.

Good day

**Comment by RuinedYourLife** [comment]
Limit appears to be 1000? Do correct me if I'm wrong ^^'

**Comment by youssefhassan** [comment]
Hey @RuinedYourLife, thanks for reporting
we take abuse and bots very seriously and I'm interested in how did you manage to identify the bots activity as 4K sounds like a big numbers. Can you share your account and which tracks get this abusive behaviour?

**Comment by RuinedYourLife** [comment]
Hey!
Pretty much I'm looking at all the accounts that either follow me, like my songs, repost them, cross-reference the data and block the accounts based on certain criterias (number of followers, if they have a default pfp).
I just finished blocking 135 more accounts that liked one of my tracks.
Can we communicate over an other channel if we want to exchange accounts/data/code etc...?
How does discord sound?

**Comment by RuinedYourLife** [comment]
Hey there,
No updates over here?
I managed to clean up a bit but I still have my questions unanswered + we did not get in contact.

**Comment by youssefhassan** [comment]
Hey @RuinedYourLife, accessing directly api-v2 is not allowed publicly. It's not meant to be accessible from users and used only by web. I will share your request with the respective teams otherwise we do not support this endpoint of muting publicly

**Comment by RuinedYourLife** [comment]
I know it isn't. But what was I supposed to do?
The support has been unresponsive for 3-4 months, and it's not like I'm manually blocking thousands of accounts.
