### ISSUE TITLE
Cannot update redirect_uri and website of your app

### ISSUE THREAD

**Issue by liquidchrome** [soundcloud/api#329]
## Title: Cannot update redirect_uri and website of your app
Issue found of: September 30th, 2024

### Endpoint(s):
Registered app API details
https://soundcloud.com/you/apps

### Scope(s):
* Connect/Authorization flow

### Steps to reproduce:
https://secure.soundcloud.com/connect?client_id=[client_id]&response_type=code&redirect_uri=???

### Expected behaviour:
Be able to edit api details like website of your app and redirect_uri

### Actual behaviour:
no option to update

**Comment by youssefhassan** [comment]
It's a known issue and it's on our radar. Thanks for reporting.

**Comment by liquidchrome** [comment]
Can I request to have these fields manually updated by your team?
I'm unable to make proper authenticated calls because those fields are empty in my api setting.
