### ISSUE TITLE
404 error on sdk-3.3.2.js.map

### ISSUE THREAD

**Issue by alexweinstein** [soundcloud/api#33]
## 404 error on sdk-3.3.2.js.map
Issue found of: February 15, 2021

### Steps to reproduce:

Just a basic setup using the [recommended js sdk](https://developers.soundcloud.com/docs/api/sdks#basic). 

```<script src="https://connect.soundcloud.com/sdk/sdk-3.3.2.js"></script>
<script>
  SC.initialize({
    client_id: 'YOUR_CLIENT_ID',
    redirect_uri: 'https://example.com/callback'
  });
</script>
```

### Error message in console:

`Failed to load resource: the server responded with a status of 404 ()`
`https://connect.soundcloud.com/sdk/sdk-3.3.2.js.map`

**Comment by rahul-sc** [comment]
Hello. Yes, we're aware of this one. 
But these error logs in console shouldn't affect the integration.

**Comment by tdietert** [comment]
@rahul-sc I'm still seeing this error when running the example. I am using a valid client id, but get this response:
```
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>connect/sdk/sdk-3.3.2.js.map</Key>
<RequestId>5R2T20CXJD6P68G7</RequestId>
<HostId>8/bZlhANgDh4OOJs5aDxu7Bwp1BlZ1okGYPM37GjPy/B20rQ7L+aC41XJQYAUbM5kV9OJjgXLwY=</HostId>
</Error>
```

**Comment by rahul-sc** [comment]
@tdietert please see my answer above. This shouldn't affect your integration
