### ISSUE TITLE
Tracks search appears to be returning cached results

### ISSUE THREAD

**Issue by dewhaskins** [soundcloud/api#330]
## Title: Tracks search appears to be returning cached results
Issue found of: October 04th, 2024

### Endpoint(s):
* `GET /tracks?q=[query]`

### Scope(s):
* Using OAuth 2.1

### Steps to reproduce:
```bash
curl --request GET \
  --url 'https://api.soundcloud.com/tracks?q=hello'
```

### Expected behaviour:
You would expect a list of tracks related to the search params you set

### Actual behaviour:
A list of tracks unrelated that appears to change every 60 seconds. I could be wrong but I think the first request after the 60 seconds is up, is then the results that appear for the following 60 seconds.

**Comment by SogenOvitch** [comment]
Same here indeed, tracks search indeed broken or wrongly influenced by a caching system (easily noticeable switching between two different research), was previously working fine tho :'(

**Comment by youssefhassan** [comment]
@dewhaskins @SogenOvitch We had an issue with caching and it's fixed now, can you please check?

**Comment by dewhaskins** [comment]
> @dewhaskins @SogenOvitch We had an issue with caching and it's fixed now, can you please check?

@youssefhassan Yes all working as expected now. Thanks for fixing.
