### ISSUE TITLE
401 on /me after retrieving auth token

### ISSUE THREAD

**Issue by cvringer** [soundcloud/api#331]
Hi! I'm trying to access SC API using the CLI
I keep getting 401. See reproduction below. Also tried this using a Java client. Same results. Probably missing something here?
TIA, Cyriel

## Title: 401 on /me after retrieving auth token
Issue found of: Oct 8th, 2024

### Endpoint(s):
* `GET /me`

### Scope(s):
* None (application is not using authentication i.e., implicit flow)

### Steps to reproduce:
1) Get Token using Base64 Encoded credentials
cvringer@Mackbook-M2-Pro ~ % curl -X POST "https://secure.soundcloud.com/oauth/token" \
     -H  "accept: application/json; charset=utf-8" \
     -H  "Content-Type: application/x-www-form-urlencoded" \
     -H  "Authorization: Basic XXXXXXXX=" \
     --data-urlencode "grant_type=client_credentials"
{"access_token":"NEVER_SHARE_TOKEN","token_type":"Bearer","expires_in":3599,"refresh_token":"XXXXXXXXXXXXX","scope":""}%                                                                                                                                     

2) Use token in /me 
cvringer@Mackbook-M2-Pro ~ % curl "https://api.soundcloud.com/me" \
       -H "accept: application/json; charset=utf-8" \
       -H "Authorization: OAuth NEVER SHARE TOKEN"

3) I get 401
{"code":401,"message":"","link":"https://developers.soundcloud.com/docs/api/explorer/open-api","status":"401 - Unauthorized","errors":[],"error":null}%                                                                                                                                         cvringer@Mackbook-M2-Pro ~ % 

### Expected behaviour:
Would expect a status other than 401

### Actual behaviour:
401 Server Error (consistently)

**Comment by mgoodfellow** [comment]
Hi @cvringer ,

2 things:

1. You have just leaked your client_id and client_secret to everyone. These will need to be reset now, I would contact SoundCloud ASAP to request this.

2. This is a server context token (using the Client Credentials flow), not a user context token, and it cannot be used to access user-centric resources such as `/me/` as it is not associated to a user. It can be used for read-only access to endpoints like `/tracks` for example, but cannot perform any mutations.

**Comment by youssefhassan** [comment]
Thanks @mgoodfellow, I will edit their message and revoke the access. Please contact us @cvringer for reinstating the account

**Comment by youssefhassan** [comment]
Question answered

**Comment by cvringer** [comment]
Request for invalidation send. Thanks for noticing.
