### ISSUE TITLE
Stale data received from API for reposters

### ISSUE THREAD

**Issue by mgoodfellow** [soundcloud/api#332]
Hi,

As of the 11th October, it seems we are receiving stale cached data from /tracks/{track_id}/reposters endpoints (and playlist equivalents).

The data has no indication it is stale or old cached data, but when we check the results against visiting the actual SoundCloud website, we have realised this data isn't an accurate representation of the current system state.

This appeared to have started happening during the outages on the 11th where tracks were disappearing and data was inconsistent across the platform - although that seems resolved, we now have inconsistent data being returned from the API.

Thanks,

Mike

**Comment by mgoodfellow** [comment]
Any chance this is related to this previous issue: https://github.com/soundcloud/api/issues/330

**Comment by youssefhassan** [comment]
Hey @mgoodfellow, it shouldn't be the case. Does the issue still there?

**Comment by mgoodfellow** [comment]
Hi @youssefhassan 

Yes, we are still actively seeing inconsistent data with the API.

More interestingly, while trying to get you specific examples (in this one, the API returned 0 reposts, but the website seems to vary) - I can see the issues occurring on the main website - take this track for example:

https://soundcloud.com/radder-repost-mainpage/open-doors/reposts

Load 1:

![image](https://github.com/user-attachments/assets/7ab5fecb-d46e-43a3-81d5-6a1b9a9d50b9)

From dev console:

https://api-v2.soundcloud.com/tracks/1933431047/reposters?client_id=6ZQ2Vr6GmERVhpEmkZmcNAuDQ3l9qaZe&limit=6&offset=0&linked_partitioning=1&app_version=1728896408&app_locale=en

```{"collection":[],"next_href":null,"query_urn":null}```

Refresh a few times:

![image](https://github.com/user-attachments/assets/f535b958-b4e2-4ddc-871a-174e6a369dfc)

https://api-v2.soundcloud.com/tracks/1933431047/reposters?client_id=6ZQ2Vr6GmERVhpEmkZmcNAuDQ3l9qaZe&limit=6&offset=0&linked_partitioning=1&app_version=1728896408&app_locale=en

![image](https://github.com/user-attachments/assets/c9bab71f-889b-44fe-af2c-0f34b5cde0fe)

https://api-v2.soundcloud.com/tracks/1933431047/reposters?offset=1728828661000&limit=6&client_id=6ZQ2Vr6GmERVhpEmkZmcNAuDQ3l9qaZe&app_version=1728896408&app_locale=en

![image](https://github.com/user-attachments/assets/47427bdf-6650-4ec3-a004-8fcf8612e7bc)

Data starts actively loading, then stops again.

I also have noticed that on the `track` object we are getting back null values for repost_count on some tracks, and other aggregated statistics return as 0 which they weren't before.

**Comment by mgoodfellow** [comment]
Going on from above capturing from the dev console directly from the website (which is using the v2 API I know, but I wonder if there is something more fundamentally wrong which is why we are seeing strange data from the API we use?)

https://api-v2.soundcloud.com/tracks/1933431047/reposters?client_id=6ZQ2Vr6GmERVhpEmkZmcNAuDQ3l9qaZe&limit=6&offset=0&linked_partitioning=1&app_version=1728896408&app_locale=en

via: 1.1 d1065aa7163db3a0368b157f398a77ec.cloudfront.net (CloudFront)
x-amz-cf-id: r2Nfs-LK54eLkEoRAekp93-gKxekOENQN2aVECKkkRx5q2oh4LWaEQ==
x-amz-cf-pop: MAN51-P1

^^ The above request returned data

https://api-v2.soundcloud.com/tracks/1933431047/reposters?client_id=6ZQ2Vr6GmERVhpEmkZmcNAuDQ3l9qaZe&limit=6&offset=0&linked_partitioning=1&app_version=1728896408&app_locale=en

via: 1.1 d1065aa7163db3a0368b157f398a77ec.cloudfront.net (CloudFront)
x-amz-cf-id: BxqRAHtAkauErUxqIIJeWQMTYHMEmbyHwyXg6lZlUKe3MGObV5cSBQ==
x-amz-cf-pop: MAN51-P1

^^ This request returned empty collections

Not sure if you can use the request IDs down the logging stack to correlate exactly what differs between these 2 identical requests, where 1 returns a dataset, and the other returns an empty dataset.

Refreshing the above link I shared does reproduce this effect randomly. I also notice for tracks where this effect occurs, there is no aggregated information (play count / comment count / repost count etc) and they aren't shown on the web player.

**Comment by youssefhassan** [comment]
Hey @mgoodfellow, there was an issue we found and fixed. Can you please double check and let us know?
Thanks for the patience

**Comment by mgoodfellow** [comment]
Hi @youssefhassan 

Thanks for the fix, this issue has now been resolved!
