### ISSUE TITLE
SoundCloud Application Registration

### ISSUE THREAD

**Issue by PolyCrusher** [soundcloud/api#338]
We want to use Soundcloud with your API for an upcoming project.
When will the registration be back?

**Comment by MariaVWSoundCloud** [comment]
@PolyCrusher please get in touch with the SoundCloud support, we can grant API access if you provide: app name, description, how you are going to use the API and (optional) a redirectURI.

**Comment by ruthen1um** [comment]
> @PolyCrusher, пожалуйста, свяжитесь со службой поддержки SoundCloud. Мы можем предоставить доступ к API, если вы предоставите: название приложения, описание, информацию о том, как вы собираетесь использовать API, и (при необходимости) URL-адрес перенаправления.

Hello! Can you please review my ticket 3213232

**Comment by MariaVWSoundCloud** [comment]
@PolyCrusher Done! Happy coding!
