### ISSUE TITLE
Access_token generated from the new API URL - https://secure.soundcloud.com/oauth/token doesn't work

### ISSUE THREAD

**Issue by kejul-vyas-mck** [soundcloud/api#343]
## Title: Cannot upload audio track using API
Issue found of: Nov 11th, 2024

### Endpoint(s):
* `POST https://api.soundcloud.com/tracks`

### Scope(s):
* None (application is not using authentication i.e., implicit flow)

### Steps to reproduce:
1. I am generating access_token using the client credential workflow - https://secure.soundcloud.com/oauth/token 
2. Access_token is generated successfully.
3. upload the track using below curl url and Authorization header.
curl -X 'POST' \
  'https://api.soundcloud.com/tracks' \
  -H 'accept: application/json; charset=utf-8' \
  -H 'Content-Type: multipart/form-data' \
  -F 'track[sharing]=private' \
  -F 'track[asset_data]=@A-hard-row-to-hoe—whats-in-store-for-agricultural-input-suppliers-this-year.mp3;type=audio/mpeg' \
  -F 'track[title]=test'
![image](https://github.com/user-attachments/assets/6c10a522-486f-4150-b260-67a846374851)

### Expected behaviour:
Track should be uploaded to this app - https://soundcloud.com/mckinsey

### Actual behaviour:
Getting 401 Unauthorized error.

**Comment by kejul-vyas-mck** [comment]
is this true? @youssefhassan if so then why I don't see anywhere here to mention that we can not use client credential workflow for POST api -  https://developers.soundcloud.com/docs/api/guide#authentication

**Comment by mgoodfellow** [comment]
![image](https://github.com/user-attachments/assets/a27bddd7-08be-4af6-bf15-5ac0975f6740)

**Comment by kejul-vyas-mck** [comment]
Currently with old upload track api - https://api.soundcloud.com/oauth2/token, the client credential workflow is working fine though

**Comment by youssefhassan** [comment]
Hey @kejul-vyas-mck, as @mgoodfellow mentioned the POST, PUT and /me have to be used with user token as these actions have to be made by a user. What is the use case to upload a track without a user token? Which user should this track be uploaded to?

**Comment by kejul-vyas-mck** [comment]
@youssefhassan, We have registered our app to SoundCloud using this email id - Charmaine_Rice@mckinsey.com and have received the ClientId and Client Secret. The audio track should be uploaded here - https://soundcloud.com/mckinsey. 

We have a backend application that uploads the track to the mckinsey account. We can not use Authorization Code flow since we don't have a UI and reading on the website looks like it requires user interaction
<img width="524" alt="image" src="https://github.com/user-attachments/assets/c6924f8b-5aff-4762-ae69-9e777a4c801f">

Hence, we use client credential workflow to generate the token and later use that token to upload the track. **The issue is with the new token generation api URL - https://secure.soundcloud.com/oauth/token, WE CAN NOT UPLOAD THE TRACK** 

My question is the same client credential workflow works with the old token generation api URL - https://api.soundcloud.com/oauth2/token, SO WHY THE ISSUE IS HAPPENING NOW?

**Comment by kejul-vyas-mck** [comment]
Let me know if coming on a call will help to resolve this issue. Also, I'm curious when SoundCloud is planning to depreciate this API to generate the token: https://api.soundcloud.com/oauth2/token.

**Comment by youssefhassan** [comment]
Uploading a track needs an authenticated user, you cannot upload a track with client credentials as client credentials identify an app not a user or an artist. If it worked before, then it was wrong and not expected. 
A user has to go through authentication to be able to upload or otherwise any app can upload on behalf of users.
To be able to upload to mckinsey account, mckinsey has to authenticate using the client credentials of the app (in this case mckinsey app owns that app but this is an edge case), then using the token the upload shall work.
