### ISSUE TITLE
High error rates, and slow response times over the last 48 hours

### ISSUE THREAD

**Issue by mgoodfellow** [soundcloud/api#346]
Hi,

The API has been suffering from the "404 page not found" error I have mentioned in previous issues again the last 2 days - https://github.com/soundcloud/api/issues/314#issuecomment-2443962069

![image](https://github.com/user-attachments/assets/eff5d332-b46f-4eb3-acce-56a7d2bcbf84)

When this happens, we receive a flood of 404s (where the resource does exist, but it seems the service mesh is saying the microservice doesn't exist). We also see huge spikes in response times across the endpoints.

Most affected are tracks, playlists and profiles.

Authentication (token grant, refresh etc.) seem to be largely unaffected.

This issue is affecting the stability of our app and experience for our users. Do you know what might be causing this?

Cheers!

**Comment by youssefhassan** [comment]
Hey @mgoodfellow, we were experiencing higher loads than expected the previous week, we did some fixes to our infrastructure to avoid this kind of outages. The fix was deployed last night, please let us know if you can see the relief in the errors. Apologies for the inconvenience

**Comment by mgoodfellow** [comment]
Hi @youssefhassan 

Yes everything seems to have stabilised from what we can see.

Many thanks!
