### ISSUE TITLE
Request - 'login with SoundCloud' feature

### ISSUE THREAD

**Issue by Bazzy-B** [soundcloud/api#37]
I run an internet radio station and we are entering the next stage of development and want users to have accounts with us. We were wondering if users with SoundCloud accounts can use these to log into our site - this would allow for a higher degree of integration with our site whereby users can repost & like SoundCloud content from our site. 

I think this would be a good move for SoundCloud as it would encourage internet radio stations to use your platform as an archive for their stations. :)

**Comment by rahul-sc** [comment]
Hmm .. not sure if I understood you correctly, but we already support Logging in With Soundcloud i.e., via OAauth
https://developers.soundcloud.com/docs/api/guide#authentication

**Comment by Bazzy-B** [comment]
Brilliant, in that case ignore me! I found another example online just as you replied too, thank you for the prompt response :)
