### ISSUE TITLE
Track update via API generating 405 error

### ISSUE THREAD

**Issue by alexweinstein** [soundcloud/api#39]
## Title: Cannot update me/track metadata
Issue found of: March 9, 2021

### Endpoint(s):
* `PUT me/tracks`

### Steps to reproduce:
```
$client = new Services_Soundcloud($sc_clientid, $sc_clientsecret);
$client->setAccessToken($access_token);
$client->put('https://api.soundcloud.com/me/tracks/123456789', array(
		'track[title]' => "TEST TITLE"));

```

### Expected behaviour:
Track title is updated to _TEST TITLE_

### Actual behaviour:
405 error (consistently)

**Comment by mgoodfellow** [comment]
That's a deprecated endpoint judging by https://developers.soundcloud.com/docs/api/explorer/open-api

Maybe try a PUT to /tracks/{id} ?

**Comment by alexweinstein** [comment]
Ah amazing. That did it. Thank you so much.
