### ISSUE TITLE
Feature Request: Ability to make/remove a repost

### ISSUE THREAD

**Issue by mgoodfellow** [soundcloud/api#4]
## Feature Request: Ability to make/remove a repost

Currently a repost can be made/removed via the v2 endpoint:

* `PUT|DELETE https://api-v2.soundcloud.com/me/track_reposts/{trackId}`
* `PUT|DELETE https://api-v2.soundcloud.com/me/playlist_reposts/{trackId}`

It would be great to have this functionality added to the v1 public API.

**Comment by rahul-sc** [comment]
Hey @mgoodfellow 

We pushed out support for these on the api
https://developers.soundcloud.com/docs/api/explorer/open-api

Can you confirm & close this?

**Comment by mgoodfellow** [comment]
Thanks for the update, we will make these updates ASAP and update/close this issue

**Comment by mgoodfellow** [comment]
Hi @rahul-sc 

We have moved over to the new endpoints and everything is working as expected. Thanks for the updates!
