### ISSUE TITLE
Not able to register  new app for API. getting same message from 8months "Due to the high amount of requests recently received, we will no longer be processing API application requests at this time. We are working to re-evaluate our process to make it more efficient."

### ISSUE THREAD

**Issue by tusharhatwar1997** [soundcloud/api#47]
## Title: Cannot retrieve all tracks for a user
Issue found of: September 20th, 2020

### Endpoint(s):
* `GET /users/{id}/tracks`

### Scope(s):
* None (application is not using authentication i.e., implicit flow)

### Steps to reproduce:
```bash
curl --request GET \
  --url 'https://api.soundcloud.com/users/12345/tracks?limit=1&linked_partitioning=true&client_id=DONT_SHARE_CLIENT_ID'
```

### Expected behaviour:
A list of tracks as described at `https://developers.soundcloud.com/docs/api/reference#users`.

### Actual behaviour:
500 Server Error (consistently)

**Comment by anikarni** [comment]
Hi, @tusharhatwar1997. As your issue mentions, unfortunately, we are currently not accepting applications for new API keys. We hope to re-enable API key generation for our users in the future. To stay informed of any changes here, keep an eye on our blog or follow us on Twitter (@SoundCloudDev).

**Comment by JLabadorf** [comment]
it's been a year since this originally was asked. Still looks like we don't have access to register an app. Is there any update? Has SoundCloud closed its developer API program?

**Comment by JLabadorf** [comment]
> it's been a year since this originally was asked. Still looks like we don't have access to register an app. Is there any update? Has SoundCloud closed its developer API program?



> Hi, @tusharhatwar1997. As your issue mentions, unfortunately, we are currently not accepting applications for new API keys. We hope to re-enable API key generation for our users in the future. To stay informed of any changes here, keep an eye on our blog or follow us on Twitter (@SoundCloudDev).

it's been a year since this originally was asked. Still looks like we don't have access to register an app. Is there any update? Has SoundCloud closed its developer API program?

**Comment by obrhoff** [comment]
Unfortunately it seems that most stake holder of the API left the company. Not sure if there ever will be progress regarding the api.

**Comment by pabloscloud** [comment]
just too bad

**Comment by MariaVWSoundCloud** [comment]
You can ask for new API credentials by opening a ticket in our support system. Just mention the SC account you want the credentials under, the name of the app and a description (how are you going to use the API) and (optional) a redirect URI.
