### ISSUE TITLE
Use of the MediaSession API in the Browser

### ISSUE THREAD

**Issue by Nerixyz** [soundcloud/api#48]
## Feature Request

I'm not sure if this is the place to request this. It's not about the API, it's about the website itself.

I'm a developer of an extension that shows the media that's playing in the browser. To achieve this, I'm tracking the use of the [MediaSession API](https://developer.mozilla.org/en-US/docs/Web/API/Media_Session_API) to watch for changes. However on SoundCloud, this doesn't work as there's no metadata declared. I'm requesting the web-player to use the MediaSession API. This would not only benefit the extension but also other integration. For example Chrome uses this api to display the media in the top right. Also most Browsers expose the metadata to a system service so it can be shown in system-ui.

**Comment by rahul-sc** [comment]
Thanks for bringing this to our attention. We're looking into this

**Comment by rahul-sc** [comment]
Hey @Nerixyz 
This should be live now :) 

Curious to see what you would be building from this. Do share if you can :D

Closing this for now.
