### ISSUE TITLE
how to create new app for using api

### ISSUE THREAD

**Issue by ameinabdi** [soundcloud/api#49]
hi SoundCloud devs

I bought a new pro account. I need to use on top of my app using the new HTTP API you created unfortunately I can't because of authorization of API and I can't create new app please could help me

**Comment by anikarni** [comment]
Hi @ameinabdi . Unfortunately, we are currently not accepting applications for new API keys. We hope to re-enable API key generation for our users in the future. To stay informed of any changes here, keep an eye on our [blog](https://developers.soundcloud.com/) or follow us on Twitter ([@SoundCloudDev](https://twitter.com/SoundCloudDev)).

**Comment by devinross** [comment]
Please reenable new apps to use api!
