### ISSUE TITLE
Feature Request: Ability to like a playlist

### ISSUE THREAD

**Issue by mgoodfellow** [soundcloud/api#5]
## Feature Request: Ability to like a playlist

Currently the v1 public API does not have support for liking/favouriting playlists, as it does for tracks.

It can be done via the v2 API:

* `PUT https://api-v2.soundcloud.com/users/{userId}/playlist_likes/{playlistId}`

It would be great to have this functionality added to the v1 public API.

**Comment by rahul-sc** [comment]
Hey @mgoodfellow 

We pushed out support for these on the api
https://developers.soundcloud.com/docs/api/explorer/open-api

Can you confirm & close this?

**Comment by mgoodfellow** [comment]
Thanks for the update, we will make these updates ASAP and update/close this issue

**Comment by mgoodfellow** [comment]
Hi @rahul-sc 

We have updated the endpoints we use, thanks for adding this.

As an aside, we also moved our track likes over to the new endpoint `/likes/tracks/{trackId}` as we noticed the old favorites endpoint we were using was not documented in the new API.
