### ISSUE TITLE
BUG: Posting comment on track not working

### ISSUE THREAD

**Issue by OskarEichler** [soundcloud/api#50]
Posting comment on track not working
Issue found of: April 8th, 2021

Endpoint(s):
* `POST /tracks/{id}/comments`

Scope(s):
* User Authentication

Steps to reproduce:
```bash
curl --request POST \
  --url 'https://api.soundcloud.com/tracks/302492774/comments?comment[body]=Sick!'
```

Expected behaviour:
Comment should be posted to the track

Actual behaviour:
422 Unprocessable Entity (consistently)
{
    "code": 422,
    "message": "Parameter comment is missing."
}

The comment param is not being specified in the API Explorer. This format was working for us until early 2021 but is now broken. Please advise on the correct syntax to be used when posting comments or have a look into why the old format is not working anymore!

**Comment by dasha-kobzeva** [comment]
Hello @OskarEichler,

Thank you for reporting the issue. We have noticed that the documentation doesn't provide details about the request body as you have mentioned. We have updated the doc.

Please refer [here](https://developers.soundcloud.com/docs/api/explorer/open-api#/tracks/post_tracks__track_id__comments) for the right way to post a comment.

Let us know if you have any questions or encounter any further issues.
