### ISSUE TITLE
Incomplete responses being returned via the SC API

### ISSUE THREAD

**Issue by mgoodfellow** [soundcloud/api#51]
Hi,

There seems to be a re-occurrence of the issue here: https://github.com/soundcloud/api/issues/13

We are investigating to confirm its the same issue from our side, but a huge spike in API errors as of about 10 mins ago all failing to deserialize due to incomplete responses.

**Comment by rahul-sc** [comment]
Thanks for reporting. We saw the blip.

**Comment by mgoodfellow** [comment]
Hi Rahul,

No, if anything the issue seems to be growing our side?

Thanks

**Comment by mgoodfellow** [comment]
Seems to only be affecting `/me` and `/users/{id}` - we are getting truncated responses as reported on the previous issue. Other endpoints don't seem to be affected

**Comment by mgoodfellow** [comment]
Hi @rahul-sc ,

Looks like it has stabilised from our side now! Thanks for the lightning speed response. Normal API issues aren't such an issue (5xx's etc), but the really strange effect of this error is that the API returns 200, with a truncated response and that makes everything explode, including our login flow. 

Really appreciate the quick reply and resolution.

Mike

**Comment by dasha-kobzeva** [comment]
Hi @mgoodfellow,

let us know if you start seeing the same issue again.
