### ISSUE TITLE
Allow Searching by ISRCs

### ISSUE THREAD

**Issue by OskarEichler** [soundcloud/api#53]
## Title: Allow Searching Tracks by ISRCs
Issue found of: May 2nd, 2021

### Endpoint(s):
* `GET /tracks`

Currently the SoundCloud API is returning ISRCs when fetching an individual track object, but it is unfortunately not possible to search by ISRC.

That's a big deal breaker for platforms like 1001Tracklists and Songstats, as we automatically pull in uploads across all the different DSPs by cross-searching for their ISRC, and only SoundCloud doesn't support that yet.

I would highly recommend and appreciate if that's something that could be added, as it's immensely helpful to link and collect data on more SoundCloud uploads and embed them automatically on 1001Tracklists - which in turn will drive more traffic back to SoundCloud.

Thanks a lot for the consideration!

All the best,
Oskar

**Comment by rahul-sc** [comment]
Hey @OskarEichler while we do want to extend this functionality into our Public API, we actually support this but on a different API meant for our Partners. Happy to share that info with you & your team. 

I've asked a colleague of to mine to connect us with someone at 1001Tracklists. If there's a better way to connect, lmk.

**Comment by OskarEichler** [comment]
Hey Rahul,
Thanks a lot - that sounds great! Please reach out to me directly via oskar@1001tracklists.com

Looking forward to connecting that way, and please delete this ticket after reaching out so that my email address doesn't get scraped a million times ;)

All the best,
Oskar

**Comment by dasha-kobzeva** [comment]
I will close the ticket as the issue was resolved

**Comment by BolajiOlajide** [comment]
Hello,

I'm in need of this particular feature. I am a founder of an app that curates links to a single track on several streaming platforms like soundcloud. Can you send more details to my email hello[at]logicalley.africa?

**Comment by export-mike** [comment]
@rahul-sc is this still the case today? search by ISRC is only accessible by partner api access?

**Comment by MariaVWSoundCloud** [comment]
Hi @export-mike - yes, the ISRC search is still part of the partner API access and we have no plans to offer it on public API atm. If you are interested in signing up for partner API, please reach out us and we can chat about it.
