### ISSUE TITLE
Is playlist representation=compact deprecated?

### ISSUE THREAD

**Issue by alexweinstein** [soundcloud/api#57]
I don't see `representation` in the API explorer, so I would assume it's not available for use... but just thought I'd ask here:
**Is there is a way to get a user's playlists without tracks?**

It was announced in this blog post:
https://developers.soundcloud.com/blog/new_playlist_representations

and updated:
https://developers.soundcloud.com/blog/compact-playlist-search

**Comment by dasha-kobzeva** [comment]
Hi @alexweinstein,
the blog posts you refer to are quite old and seem to be invalid. Currently, only 2 endpoints can return playlists w/o tracks:

https://developers.soundcloud.com/docs/api/explorer/open-api#/me/get_me_activities
https://developers.soundcloud.com/docs/api/explorer/open-api#/me/get_me_activities_all_own

Would you mind providing your use case so we can validate how we can support you?
Thank you

**Comment by dasha-kobzeva** [comment]
Hi @alexweinstein,
we have added a boolean flag `show_tracks` that allows requesting playlists w/o tracks. 

You can find the details about usage here: 
https://developers.soundcloud.com/docs/api/explorer/open-api#/search/get_playlists

**Comment by alexweinstein** [comment]
> Hi @alexweinstein,
> we have added a boolean flag `show_tracks` that allows requesting playlists w/o tracks.
> 
> You can find the details about usage here:
> https://developers.soundcloud.com/docs/api/explorer/open-api#/search/get_playlists

awesome! thank you!
