### ISSUE TITLE
Pagination for playlist missing tracks

### ISSUE THREAD

**Issue by jbelford** [soundcloud/api#58]
## linked_partitioning does not fetch full list for playlist
Issue found of: May 29, 2020

### Endpoint(s):
* `GET /playlists/{id}/tracks`

### Scope(s):
* None (application is not using authentication i.e., implicit flow)

### Steps to reproduce:
The calls were made to these URLs - with the last 2 being what was supplied by `next_href`

https://api.soundcloud.com/playlists/1169399431/tracks?access=playable%2Cblocked%2Cpreview&linked_partitioning=true&limit=200
https://api.soundcloud.com/playlists/1169399431/tracks?limit=200&linked_partitioning=true&offset=200
https://api.soundcloud.com/playlists/1169399431/tracks?limit=200&linked_partitioning=true&offset=400

### Expected behaviour:
The full list of tracks should have been provided

### Actual behaviour:
Missing several tracks

Two things that strike me:
* The hrefs provided by the API do not include `access=playable%2Cblocked%2Cpreview`
* They do not have `cursor` and are using `limit` and `offset`

**Comment by dasha-kobzeva** [comment]
HI @jbelford,

not every endpoint is using CursorBasedPagination, we are still in the process of updating it.
Regarding hrefs not including parts of the query, we have updated them to match the original ones.

Also, in general, there are a number of reasons we don't have control of at this time, why the full list of tracks is not being returned. The `access` filter should be able to provide you a list of everything you are allowed to see.
