### ISSUE TITLE
Inconsistent number of likes

### ISSUE THREAD

**Issue by tly000** [soundcloud/api#59]
## Title: The number of likes/favorites is inconsistent
Issue found of: 01.06.2021

### Endpoint(s):
* `GET /users/{id}/`
* `GET /users/{id}/likes/tracks`

### Expected behaviour:
- `public_favorites_count` in the User object should be the same as the actual number of tracks in the list of likes retrieved by `GET /users/{id}/likes/tracks`

### Actual behaviour:
Example: My soundcloud page reports that i have 3020 likes. The `public_favorites_count` is 3031 and the summed number of elements in the `collection` objects in the  `/users/{id}/likes/tracks` pages is 2556.

**Comment by dasha-kobzeva** [comment]
Hi @tly000,

thank you for contacting us.

`public_favorites_count` shows a correct number of everything you have liked that is public. It's a sum of tracks/playlists/albums.

`GET /users/{id}/likes/tracks` shows only the tracks you liked, so albums/playlists are excluded.

The same way your SC page shows the count for tracks only.

Let me know if you have any more issues/questions regarding it.

**Comment by tly000** [comment]
Thank you for the response. This still does not explain the discrepancy between the "3020 likes" displayed on the soundcloud page and the 2556 tracks in `GET /users/{id}/likes/tracks`.

**Comment by dasha-kobzeva** [comment]
could you please give me your SoundCloud user?

**Comment by tly000** [comment]
i just took the bitbird account as an example. The webpage says "163 likes", the API says `"public_favorites_count": 180` (which is of course a higher number due to the playlists), this is the result of the `GET /users/{id}/likes/tracks` request:
```typescript
const result = await fetch("https://api.soundcloud.com/users/102435699/likes/tracks?client_id=XXX&linked_partitioning=1&access=playable,preview,blocked&limit=200").then(result => result.json())
-> Object { collection: (149) […], next_href: null }
```
