### ISSUE TITLE
Feature Request: Profile creation time added to v1 user object

### ISSUE THREAD

**Issue by mgoodfellow** [soundcloud/api#6]
## Feature Request: Profile creation time added to v1 user object

When a user is requested from the v2 API endpoint it has a `created_at` property, that indicates when the profile was created on SoundCloud.

* `GET https://api-v2.soundcloud.com/users/{userId}`

It would be useful to have this information added to the v1 user object returned from the users endpoints. Some use cases of this information:

* Protecting against spam/bot accounts
* Protecting against users accidentally using an account created silently via the Social Login flow (Google/Facebook etc) - if a user does not have an account associated with that Google/Facebook account, it seems that a brand new user is created for them, and this creates user confusion. Being able to inform them about the age of the account would help relay possible causes to the user.

**Comment by anikarni** [comment]
hey @mgoodfellow , we're slowly working through this request as we migrate some of our user management endpoints off of our legacy systems. In the meantime, this is already available in endpoints such as user search: https://developers.soundcloud.com/docs/api/explorer/open-api#/search/get_users. I hope it helps. 

We'll update you here and close the ticket once we make it available in the `/users/:id` and `/me` endpoints.

**Comment by mgoodfellow** [comment]
Hi @anikarni ,

That's awesome news, thank you!

I just checked and it is returned on the payload received from the API (🥳)- but it doesn't show in the schema on https://developers.soundcloud.com/docs/api/explorer/open-api#/search/get_users - I guess that just needs to be synced up!

Many thanks

**Comment by anikarni** [comment]
Ah, it's on the schema (above the example, there's a more complete and reliable, but hidden, "schema" tab), but not on the example. I'll update the example, thanks for letting me know.

**Comment by dasha-kobzeva** [comment]
Hi @mgoodfellow,
the latest release contains a creation time in the User object. 
You can follow the release notes here: https://github.com/soundcloud/api/releases

**Comment by mgoodfellow** [comment]
This is awesome, thank you very much!

**Comment by mgoodfellow** [comment]
Hi @dasha-kobzeva 

I thought I would just check this new functionality:

The schema doesn't report these new fields:

```
description:	
SoundCloud Legacy Logged In User object

avatar_url	string
URL to a JPEG image.

city	string
city.

country	string
country.

description	string
description.

discogs_name	string
discogs name.

first_name	string
first name.

followers_count	integer
number of followers.

followings_count	integer
number of followed users.

full_name	string
first and last name.

id	integer
unique identifier

kind	string
kind of resource.

last_modified	string
last modified timestamp.

last_name	string
last name.

locale	string
locale.

myspace_name	string
deprecated: true
myspace name

permalink	string
permalink of the resource.

permalink_url	string
URL to the SoundCloud.com page.

plan	string
subscription plan of the user.

playlist_count	integer
number of public playlists.

primary_email_confirmed	boolean
boolean if email is confirmed.

private_playlists_count	integer
number of private playlists.

private_tracks_count	integer
number of private tracks.

public_favorites_count	integer
number of favorited public tracks

quota	{...}
reposts_count	integer
number of reposts from user

subscriptions	{...}
track_count	integer
number of public tracks.

uri	string
API resource URL.

username	string
username

website	string
a URL to the website.

website_title	string
a custom title for the website.
}
```

And trying an example request:

GET https://api.soundcloud.com/users/1719302?client_id=XXX

```
{
    "id": 1719302,
    "kind": "user",
    "permalink": "mike-goodfellow",
    "username": "Mike Goodfellow",
    "last_modified": "2020/11/26 09:26:22 +0000",
    "uri": "https://api.soundcloud.com/users/1719302",
    "permalink_url": "https://soundcloud.com/mike-goodfellow",
    "avatar_url": "https://i1.sndcdn.com/avatars-000171898806-4as0sa-large.jpg",
    "country": null,
    "first_name": "Mike",
    "last_name": "Goodfellow",
    "full_name": "Mike Goodfellow",
    "description": "DJ / Producer from London\n\nDrummer in @the-black-roses-1",
    "city": "London",
    "discogs_name": null,
    "myspace_name": null,
    "website": null,
    "website_title": null,
    "track_count": 13,
    "playlist_count": 0,
    "online": false,
    "plan": "Pro Plus",
    "public_favorites_count": 707,
    "followers_count": 2877,
    "followings_count": 722,
    "subscriptions": [
        {
            "product": {
                "id": "creator-pro-unlimited",
                "name": "Pro Unlimited"
            }
        }
    ],
    "reposts_count": 679
}
```

**Comment by dasha-kobzeva** [comment]
Hi @mgoodfellow,
Unfortunately, the change was rolled back a while after I have closed the issue. 
I will let you know when it's active again. 

`/me` endpoint should already provide the required field.

**Comment by dasha-kobzeva** [comment]
Hi @mgoodfellow,
just want to let you know that the issue was resolved for every endpoint.
