### ISSUE TITLE
POST /likes/tracks/[track_id] .... Error 405 

### ISSUE THREAD

**Issue by ioue** [soundcloud/api#60]
## Title: Liking a track ... Method not allowed error
Issue found of: June 2, 2021

### Endpoint(s):
* `POST /likes/tracks/{id}`

### Steps to reproduce:
```bash
curl --request POST \
  --url 'https://api.soundcloud.com/likes/tracks/1234'
```

### Expected behaviour:
200 Ok

### Actual behaviour:
405 Method Not Allowed   / This response is not even described in https://developers.soundcloud.com/docs/api/explorer/open-api#/likes/post_likes_tracks__track_id_

**Comment by masterbajt** [comment]
i have same issue, issue date same, 405 on all endpoints while post/put, maybe only comments works, but i'm not sure

**Comment by masterbajt** [comment]
(+)
i have exactly same issue, issue date since June 02, 2021 -> 405 on all endpoints while post/put, maybe only comments works, but i'm not sure, different API keys doesn't help, change IP of my server doesn't work also (in a case of some internal SC block)..

**Comment by dasha-kobzeva** [comment]
Hi, @ioue and @masterbajt,

thank you for reporting the issue. 

Could you please provide an exact example of a call you are making? With headers and so on, so I can try to reproduce it.

**Comment by masterbajt** [comment]
Hello @dasha-kobzeva

Response Body: **unknown route**

`a:14:{s:12:"Content-Type";s:25:"text/plain; charset=utf-8";s:14:"Content-Length";s:2:"13";s:10:"Connection";s:10:"keep-alive";s:4:"Date";s:29:"Tue, 01 Jun 2021 11:19:30 GMT";s:4:"vary";s:6:"Origin";s:12:"x-robots-tag";s:7:"noindex";s:15:"referrer-policy";s:11:"no-referrer";s:15:"x-frame-options";s:4:"DENY";s:22:"x-content-type-options";s:7:"nosniff";s:6:"server";s:4:"am/2";s:7:"X-Cache";s:21:"Error from cloudfront";s:3:"Via";s:64:"1.1 fec87288bd626f32b2e1177a1ee70226.cloudfront.net (CloudFront)";s:12:"X-Amz-Cf-Pop";s:8:"MNL50-C1";s:11:"X-Amz-Cf-Id";s:56:"9Sm3DqOGkNqyTq2RxGJ8NEZhEj16tOFetH2q24KyK_3EjIIQMs3tZw==";}`

Basic Request: ```
curl --location --request PUT 'https://api.soundcloud.com/me/favorites/**123456**' \
--header 'Content-Type: application/json' \
--header 'Authorization: OAuth **************************************' \
--header 'Accept: application/json'
```

anyway i use different endpoint, but it doesn't matter all make the error, i did not change code for 2 years at least, before was all working..

only one endpoint works: /tracks/**123456**/comments.....reposts, likes and etc doesn't work..

maybe wait @ioue for reply, i can't provide better info..

**Comment by ioue** [comment]
@masterbajt `/me/favorites/track_id` endpoint was gone by the way.  POST/DELETE `/likes/tracks/track_id` is probably the new to control your like-ness.

**Comment by masterbajt** [comment]
@ioue i see, but even the new endpoint cause same error

**Comment by masterbajt** [comment]
@ioue ok, it's works for me POST + new endpoint...i was looking on dev blog when this problem started, but did not find any info then i did not have idea that these endpoints are done..

**Comment by ioue** [comment]
@dasha-kobzeva 
I was wrong... as I told to @masterbajt , the end point only accepts POST/DELETE, but I was sending data via PUT. This is the reason why I got 405.

Agreed with @masterbajt , the API was silently updated and recently it seems that the API changed the behavior.

Anyway this was not a bug. I was calling the API wrongly.

**Comment by masterbajt** [comment]
@ioue yes, it's resolved our problems, but now my problem that's passed only one request for LIKE and after when i try again then i got 401 HTTP error, after X minutes it's works again..can't understand why..will understand if some error about limit reached, but not 401..this not happend me on old endpoint..

**Comment by dasha-kobzeva** [comment]
Thank you for providing the details.  I'm glad the issue was resolved.

Yes, we have recently removed the deprecated endpoints. There was no blog update regarding the change as our spec had all the related information and the endpoints were deprecated for quite a while.

**Comment by dasha-kobzeva** [comment]
Our spec is up to date so in case you run into any more problems, you could also verify the correct calls there as well as know about other deprecations. 
https://developers.soundcloud.com/docs/api/explorer/open-api

**Comment by anikarni** [comment]
Hey @masterbajt , I'm closing this ticket as the 405 issue is resolved. Feel free to create a new one for the 401s you're seeing, if the issue is still persisting. You're right that it shouldn't be a 401 unless authentication is failing for some reason.
