### ISSUE TITLE
Trying to Contact any human working at SoundCloud Dev

### ISSUE THREAD

**Issue by GGTLS** [soundcloud/api#61]
Hello.
The Soundcloud blog says the SoundCloud team is answering technical Questions Via GitHub.
https://developers.soundcloud.com/support

I have a question i would like to ask someone at Soundcloud and am wondering where / how i can do that.

thank you.

**Comment by anikarni** [comment]
Hey @GGTLS , you can ask us here! We're pretty active in this repo. If this is related to the API, happy to answer. If it's related to the app, please reach out through the [help center](https://help.soundcloud.com/hc/en-us/requests/new?ticket_form_id=581048).

**Comment by GGTLS** [comment]
Hello.
Thanks. 
So I have a SoundCloud App via my project GigaTools. The soundcloud app was buit maybe 7 years ago..  and does a very basic thign of updating users Soundcloud bio text remotely via the API, after they've authorised our app via an oAuth process.
This app has been working fine for years but ive just recently noticed its now not working. the attempted updates just fail. I've not been paying attention to changes or updates at soundcloud so am just wondering if something has changed on the API back end or some other thing that has changed / disabled the permissions that my app was using..   

We have not changed anything on our end so im wondering if you have. 
thank you

**Comment by anikarni** [comment]
Hey. Yes, we have made a few changes to the API. We currently announce any breaking changes through our blog, which you should be able to follow on twitter or RSS feed, for now: https://developers.soundcloud.com/blog/category/api. 

If you can create a detailed issue with the error you're seeing, we can help you define what's wrong. Meanwhile, feel free to check our up to date documentation too: https://developers.soundcloud.com/docs/api/explorer/open-api

**Comment by GGTLS** [comment]
Thank you.
Are you able to tell me, if you do know of any change that did effect the updating of user profiles by 3rd party apps? as i cant find any information about any changes that would have disabled the previously functional features i was using.
thanks again

**Comment by anikarni** [comment]
Please open an issue with the detailed error messages and errors you're seeing (and endpoints you're calling). We have provided a template for these issues so that we can better help you. When you create an issue, use the template as a guide and fill out the information on each part.
