### ISSUE TITLE
soundcloud_client.put - No longer working

### ISSUE THREAD

**Issue by GGTLS** [soundcloud/api#63]
Hello.
This line of code, supplied by Soundcloud for Ruby on Rails 5+ years ago that connects with the Soundcloud GEM is no longer working

res = client.soundcloud_client.put("/me", :user => {:description => new_profile})

specifically the PUT call.

Im wondering if it has been disabled.
Thank you

**Comment by GGTLS** [comment]
IS anyone reading this? thank you

**Comment by rahul-sc** [comment]
This is not a supported endpoint from the API anymore.
We're in progress to remove/update this reference from docs.

**Comment by rahul-sc** [comment]
The docs are updated now. POST should work for the above.
