### ISSUE TITLE
Changing the domain of registered app

### ISSUE THREAD

**Issue by syndicast** [soundcloud/api#64]
Is there any way to modify the domain and the Redirect URI of our registered app?

**Comment by dasha-kobzeva** [comment]
HI @syndicast,

Currently, we do not give users the ability to edit the information of their app. But you can send us the necessary information and we might do it on your behalf.

Thank you

**Comment by syndicast** [comment]
That would be awesome. Where can I send the information to? Thanks

**Comment by dasha-kobzeva** [comment]
Can do it right here, if it works for you.

**Comment by syndicast** [comment]
Depends on the info I have to provide. Also, since the app is live, we should arrange a suitable time that is convenient for both of us for the change. Or the other option is to register a new app.

**Comment by dasha-kobzeva** [comment]
We need to know your user id, or app id, and a new redirect_uri. At this point, we do not register new apps.

**Comment by rahul-sc** [comment]
Hey @syndicast as it was mentioned above, we'd need your soundcloud account url and the intended redirect. We can set up a new credential for your existing app.

**Comment by syndicast** [comment]
Thanks, we will send the required info next week once we have completed the modifications within our system.

**Comment by dasha-kobzeva** [comment]
Dear @syndicast,
 The redirect URI was updated.

**Comment by javaskript** [comment]
@dasha-kobzeva @rahul-sc  Could one of you please also help with updating my existing app? I put in a request months ago after our domain had changed but it hadn't been resolved. Thanks in advance!

Client ID: zOHlLuAliit5YjxxNLbRd7Hl7VA8dY3T

### Old Info: ❌
Website of your app: <img src="https://i.imgur.com/YMur7Fd.png">

### **New** Info: ✔
Website of your app: <img src="https://i.imgur.com/awBypnH.png">
Redirect URI: https://trak.fm/auth/soundcloud
