### ISSUE TITLE
State property of the track causes attribute error on track object

### ISSUE THREAD

**Issue by Lunga001** [soundcloud/api#67]
## Title: Attribute error state on track after track has been posted
Issue found of: May 11th, 2021

### Endpoint(s):
* `POST /tracks/{track_id}`

### Scope(s):
* None (application is not using authentication i.e., implicit flow)

### Steps to reproduce:
```python
from soundcloud import Client
client = Client(
                client_id=SOUNDCLOUD_APP_KEY_ID,
                client_secret=SOUNDCLOUD_APP_KEY_SECRET,
                username=SOUNDCLOUD_USERNAME,
                password=SOUNDCLOUD_PASSWORD,
            )
 
track = client.post(
                    "/tracks",
                    track={
                        "title": title,
                        "description": "description",
                        "sharing": "public",
                        "asset_data": file_handle,
                        "license": "cc-by",
                        "artwork_data": open(SOUNDCLOUD_ARTWORK_PATH, "rb"),
                        "genre": "Genre",
                        "tag_list": "event type",
                        "downloadable": "true",
                        "streamable": "true",
                        "feedable": "true",
                    },
                )
track.state
```
### Expected behaviour:
A track state: https://developers.soundcloud.com/docs#uploading
If successful, your track will immediately be queued up for encoding. You check the state property of the track resource to check its progress. Once the state is finished it is ready to be embedded or streamed.

track.state

### Actual behaviour:
track.state
AttributeError soundcloud.resource in __getattr__
![AttributeError](https://user-images.githubusercontent.com/10023210/123863713-3a021180-d92a-11eb-8e7d-5f01ed25ac3e.png)

**Comment by dasha-kobzeva** [comment]
Hello @Lunga001,

A while ago we have introduced a new model for the `Track` object. You can find details in [this](https://developers.soundcloud.com/blog/soundclouds-new-api-track-object) blog post. 

`State` field was deprecated and that's why you are receiving an error. 
We are in the middle of updating our documentation, but in the meanwhile, you can always refer to our [API Explorer ](https://developers.soundcloud.com/docs/api/explorer/open-api)for the current status of the API.

Thank you

**Comment by Lunga001** [comment]
Thank you for your clear response.
Kind regards.

**Comment by Lunga001** [comment]
Is there perhaps a replacement for the state property?

**Comment by jbothma** [comment]
@dasha-kobzeva we used the state attribute to tell whether our automated uploads are ready to embed on our site. If we tried to embed them immediately after uploading, it didn't work because you were still processing it.

How can we tell whether tracks are ready to embed with the new API?
