### ISSUE TITLE
Security Blog - 1st July - Deprecation of only requiring a client_id in the URL’s query parameter

### ISSUE THREAD

**Issue by mgoodfellow** [soundcloud/api#70]
Hi,

Thanks for the security update blog published on the 1st July. 

Regarding "Use Client Credentials Grant for Server-Side Integrations" - Currently our mobile app streams content via `https://api.soundcloud.com/tracks/{id}/stream?client_id=XXX`

Will this be affected by these changes? 

It is my understanding that we shouldn't be sending OAuth tokens to client devices generated from "client_credentials" grant, as these are explicitly for server-to-server communications, so I'm unsure of the intended flows here?

Additionally, getting a mobile app updated, through review, and then getting users to update requires (unfortunately) quite some lead time, so an idea of the timescale is critical in order for us provide a quality, uninterrupted user experience.

Do you have an idea of when this particular change will go live?

Thanks!

**Comment by rahul-sc** [comment]
Yes, this would be affected. I'm not sure if I followed your questions correctly but will attempt to answer. 

As you touched on above, this is meant for server-side integrations. For client-side integrations, we have the auhorization_code. 

Regarding timeline, we're pacing the security changes out through the month of July. But expect the changes for stopping issuance of non-expiring tokens by end of month. And the changes for expiring the old non-expiring tokens to be in effect early to mid August.

**Comment by mgoodfellow** [comment]
Thanks for the answer. Yes, that timeframe is workable.
