### ISSUE TITLE
Captcha is broken under watchOS

### ISSUE THREAD

**Issue by obrhoff** [soundcloud/api#71]
### Steps to reproduce:
Call the /connect endpoint through Apple's provided ASWebAuthenticationSession. Enter your credentials. The captcha is not displayed.

![IMG_2360](https://user-images.githubusercontent.com/199578/124457735-6be10100-dd8c-11eb-877f-234a9af2048c.PNG)

**Comment by rahul-sc** [comment]
Hey @obrhoff this is not a use case we tested for in order to support. Can you share a bit more about how you're using SC connect on watch? Are you currently relying on users entering password on watch OS?

**Comment by obrhoff** [comment]
Yes indeed. The process to enter user/password unter watchOS is a little bit convoluted. It uses the Keychain on your phone to prefill your username/password. If nothing it stored you're able to enter those fields yourself on your watch (which is really hard)

**Comment by rahul-sc** [comment]
Would this functionality be more useful to you?
https://developers.soundcloud.com/blog/remote-device-sign-in

This is currently gated.

**Comment by obrhoff** [comment]
It would be amazing to get it.

**Comment by rahul-sc** [comment]
Can you close this ticket and refile another issue here requesting for device pairing endpoints on API, please? That would help us track this feature request better
