### ISSUE TITLE
Security Blog - 1st July - Expiring Tokens Are Issued by Default

### ISSUE THREAD

**Issue by mgoodfellow** [soundcloud/api#72]
Hi,

From the security blog - https://developers.soundcloud.com/blog/security-updates-api

Just to confirm, no new tokens will be allowed with the scope=non-expiring - but all previously granted non-expiring tokens will continue to function? i.e. this only affects new token grants going forward.

I just want to confirm this won't cause a mass logout of our users.

Thanks!

**Comment by rahul-sc** [comment]
@mgoodfellow have you already explored implementing a refresh token flow for a graceful transition? The goal for us is to not support non-expiring tokens at all. Would love to hear your thoughts/ideas/concerns on this?

**Comment by mgoodfellow** [comment]
Hi @rahul-sc 

We are in the process of rolling out the refresh token flow imminently - we are just testing it as we speak. Obviously in larger deployments, care has to be taken with distributed locking taking place around the refresh flow, as a refresh token can only be used once.

My question was more about the previously issued non-expiring tokens - will these continue to function, or are they being forcibly expired? If the latter, this will provide a bad user experience on our services as it would lead to a mass logout event.

Thanks!

**Comment by rahul-sc** [comment]
Great to hear that you're upgrading! Feel free to post ideas to improve the auth integration. 

True about the refresh tokens only being able to be used once. However, with client_credentials and refresh_token, your server can generate a new pair of tokens adhoc. Hope that gives some additional options if you haven't considered that already. 

Regarding timeline, we're pacing the security changes out through the month of July. But expect the changes for stopping issuance of non-expiring tokens by end of month. And the changes for expiring the old non-expiring tokens to be in effect early to mid August.

**Comment by mgoodfellow** [comment]
Hi @rahul-sc 

Thanks for the info. As of this morning we are now requesting expiring access tokens and handling the refresh ourselves.

Hopefully over the next month, many of our active users will log in again via SoundCloud, and that will mitigate the revoking of the old non-expiring tokens causing logouts.

Thanks!

**Comment by rahul-sc** [comment]
Amazing stuff. Happy to hear this!

**Comment by fascinated** [comment]
Can you clarify the process of exchanging the old non-expiring tokens for the new expiring ones? 

In a typical refresh scenario, the refresh token is used for this purpose, but I don't think we even have that stored (or it was never provided? not sure).

We currently use these non-expiring tokens to sync our users' favorites their respective SoundCloud playlists. This happens server-side, and the user has to enable it just once.

Obviously we'll be updating to the new tokens going forward as users activate this feature, but I'd like to avoid having to require every user to re-authenticate (there are many of them!).

Is this kind of "upgrade" possible?
