### ISSUE TITLE
OAuth flow for apps without a redirect URI? (client_credentials deprecation)

### ISSUE THREAD

**Issue by yfyf** [soundcloud/api#75]
## Title: OAuth flow for apps without a redirect URI? (client_credentials deprecation)
Issue found of: July 8th, 2020

### Description

This is a rather odd case: we have a very old Soundcloud app/client that doesn't have a redirect URI registered and up to now was using the `client_credentials` flow for authorization. Since this has been deprecated, it obviously no longer works, however we also cannot switch to the `authorization_code` flow, because there is no redirect URI to use.

I can manually authorize the application via the browser and obtain the auth code with an absent `redirect_uri` param, however subsequent `/oauth2/token` requests fail with 400, presumably because of the `redirect_uri` 'mismatch'.

How would you suggest to deal with this situation? Is it possible somehow to update the registered Soundcloud app and create a redirect URI for it? If yes, who should be contacted for this?

Thank you for any advice!

**Comment by dasha-kobzeva** [comment]
HI @yfyf,
thank you for filing a request.

 If you provide us with:
  * your application id 
  * or username (the application owner)
  * redirect uri
  
  
 we can add it for you.

**Comment by yfyf** [comment]
Hi @dasha-kobzeva,

Thank you for the quick reply!

Here are the app details:
Client ID: AAy9HJE4OtIhLoICtebQ
Username: yfyf
(wanted) Redirect URI: https://palanga.live/sc-oauth

**Comment by dasha-kobzeva** [comment]
@yfyf you are all set. Redirect URI was updated!

**Comment by yfyf** [comment]
@dasha-kobzeva thank you so much!

**Comment by bipedal103** [comment]
Hi @dasha-kobzeva 
We are facing the exact same issue, and we cannot change our redirect_uri. 
Could you please change it for us?

Client ID: 0b26692829174e89b8c12870cbdc77aa
Redirect_uri: https://excitr.io/callback.html

Thank you
