### ISSUE TITLE
Question: How can I authorize after the new security changes

### ISSUE THREAD

**Issue by Winspear** [soundcloud/api#76]
Hello,
We are using a python server-side application that authorizes without the soundcloud connect screen, eg:

```
soundcloud.Client(
        client_id=settings.SOUNDCLOUD_CLIENT_ID,
        client_secret=settings.SOUNDCLOUD_CLIENT_SECRET,
        username=settings.SOUNDCLOUD_ACCOUNT_USERNAME,
        password=settings.SOUNDCLOUD_ACCOUNT_PASSWORD)
```

This is the method of authentication that you document for our use case, under 'Authenticating without the SoundCloud Connect Screen' in your documentation:
https://developers.soundcloud.com/docs/api/guide#authentication

Our application uses only a single user account (that associated with our company).

Since the beginning of July our application has been unable to authorize using Oauth2. We are using the python soundcloud sdk here: https://github.com/soundcloud/soundcloud-python

In your security blog update here: https://developers.soundcloud.com/blog/security-updates-api
you state that the password grant_type has been deprecated and that users should use the client_credentials grant type for their requests. I have been tinkering with authentication without the python sdk (as the existing version hardcodes 'grant_type': 'password' - this is a seperate issue and I am working on a patch) and while I am able to obtain an access token and refresh token with, eg:
```
response = requests.post(
    'https://api.soundcloud.com/oauth2/token',
    data={
        'client_id': settings.SOUNDCLOUD_CLIENT_ID,
        'client_secret': settings.SOUNDCLOUD_CLIENT_SECRET,
        'grant_type': 'client_credentials'
        }
    )
response.text
'{"access_token":"<SOME TOKEN>","expires_in":3599,"refresh_token":"<ANOTHER TOKEN>","scope":""}'
```
I am unable to use this access_token to access the /me endpoint, as I receive a 401 error.
For example, this curl request returns 401, with my most recently generated access token:

```
curl --request GET \
> --url 'https://api.soundcloud.com/me/tracks?limit=1' \
> --header 'Authorization: OAuth <ACCESS TOKEN>'
```

I am able to use this access token to access public endpoints, such as /tracks. 

My question is, how can I best authenticate server side in order to access private endpoints, now that the old method is deprecated

**Comment by dasha-kobzeva** [comment]
Hi @Winspear,

thank you for reaching out.

As stated in the blog post `password` grant type was deprecated and that's why the old way of authentication is not working anymore. We will update the SDK/documentation in a timely manner. 

The `client_credentials` auth flow is meant only for server-side integration and allows access to public endpoints only. Meaning that for endpoint `/me` or any other user-related endpoint you have to use the `Authorization Code` flow which provides the client-side integration.

To generate the auth_code please refer to the following endpoint: 
https://developers.soundcloud.com/docs/api/explorer/open-api#/oauth/get_connect

Let me know if you have more questions.

**Comment by Winspear** [comment]
Hi Dasha,
Using client-side integration does not mirror the old functionality. Our python code is run off a heroku worker dyno, with no user input. 
What I could do is manually run the code once, save a token in the database and periodically refresh the token, which might work (please confirm?). However, I cannot currently obtain the token because our application is old, and does not have a redirect URI associated with it (similar to   #https://github.com/soundcloud/api/issues/75).
I can create an authorization URL with empty string as redirect_uri, which takes me to here:
<img width="622" alt="Screenshot 2021-07-12 at 15 04 52" src="https://user-images.githubusercontent.com/7970702/125301183-9e59a380-e322-11eb-8996-fab2bcfa3a99.png">

(so far so good)

When I click through however, I get the following

<img width="732" alt="Screenshot 2021-07-12 at 15 06 03" src="https://user-images.githubusercontent.com/7970702/125301282-bf21f900-e322-11eb-8454-3e55d2c95332.png">


Perhaps this will be resolved when the application has a redirect_url associated with it? 

If this is what you recommend, do you have a developer email address at soundcloud I could send our details to?

**Comment by dasha-kobzeva** [comment]
Hey, 
yes, `redirect_uri` is a required parameter and has to be assigned to the application you are trying to connect to. 

You can provide the `application id` and `redirect URI` right here. And I will add it.

**Comment by dasha-kobzeva** [comment]
regarding your question about `refresh_token`, you can run a `refresh token` oauth flow to keep an access_token updated after the expiration.

**Comment by Winspear** [comment]
Hi Dasha,
Client ID: q5LtlutH4ydG2WWgVDyzEBZcFterzChq
redirect URI: https://archive.boilerroom.tv/admin/

**Comment by dasha-kobzeva** [comment]
all set. Let me know if it works now

**Comment by Winspear** [comment]
All working Dasha, thanks so much

**Comment by dasha-kobzeva** [comment]
👍
