### ISSUE TITLE
App registration/API key deleted

### ISSUE THREAD

**Issue by thesubdelta** [soundcloud/api#78]
Hi Team,

I was looking into the new [auth flows](https://developers.soundcloud.com/blog/security-updates-api) that are required now after I was getting 401s with my usual requests.

I checked my app registrations and found that my entire app registration has been deleted. 

![image](https://user-images.githubusercontent.com/61033725/126245666-5cbf0ed7-1853-4a71-86e3-eb5d50157e2a.png)

The app was registered through my personal soundcloud: https://soundcloud.com/brevkingbread 

Client ID:  b60442f32f3a****************9aaa

This side project of mine has been a huge creative outlet for me and I've been working on it for several years.

I'm hoping this is just a mistake / UI issue and that my app isn't really gone.

Please advise.

**Comment by rahul-sc** [comment]
Hi @thesubdelta we've been disabling unused keys and this might have been an oversight. 

Can you please share with me some details about your app, please? Is there a website? Has your app been actively using the API? If so, how frequently?

**Comment by thesubdelta** [comment]
Thank you @rahul-sc for the quick response and for reinstating my key.

The app is not in production yet so there is not an official website but I do have a [test site](https://tsd-site20200408225335.azurewebsites.net/c/new) with minimal functionality. Essentially what I'm trying to do with this app is to use the metadata from the api to create a very specific recommendation engine for new and upcoming tracks/artists based on what I feed it initially.

The app key has been using the API as recently as last week while I have been developing the back-end for the app. My work has been on and off but the use of the app key is roughly correlated with commits to my private repo over the past year:
![image](https://user-images.githubusercontent.com/61033725/126279980-fa301f9f-ee92-46a1-8f5f-896af79e5ebd.png)

Once I go into production, I anticipate the usage will be daily and I'm designing it to stay within the 15,000 rate limit per day.

Thanks again for the quick response and let me know if you have any other questions.

**Comment by rahul-sc** [comment]
This is interesting. Thanks for sharing the info. I think yours was an exceptional oversight - based on your usage data above. 
All good. Closing this now.
