### ISSUE TITLE
Unable to update redirect_uri

### ISSUE THREAD

**Issue by ponny** [soundcloud/api#79]
## Title: Unable to update redirect_uri
Issue found of: A few years ago now...

I'm not able to change the redirect_uri of our Soundcloud oauth app. There doesn't seem to be any option in the UI now so perhaps someone can change it for us?

**Comment by rahul-sc** [comment]
Hey, sure thing. 

Please share with us your SC account under which your app is and the new redirect uri

**Comment by brucevdkooij** [comment]
@rahul-sc Same issue here. 

Could you update the redirect URI for the app in my account (brucevdk@gmail.com) to https://parsed.nl/sc

Client ID = 0ccff4c6bd150ccaab3ff01e8959acf6

Thank you.

**Comment by dasha-kobzeva** [comment]
HI @brucevdkooij,
the redirect _uri for your app was updated.

If you have any other requests/issues please create a new ticket next time. 
Cheers

**Comment by ponny** [comment]
Awesome!  The account username is `gleamio`

We need the website changed from `http://gleam.dev:3000` to `https://gleamdev.io:3000` and the redirect_url changed from 	`http://gleam.dev:3000/auth/soundcloud/callback` to `https://gleamdev.io:3000/auth/soundcloud/callback` (we use https now).

**Comment by dasha-kobzeva** [comment]
@ponny,
I see you have two sets of keys registered. Which one do you want to be updated? Please provide the client_id.

**Comment by rahul-sc** [comment]
I've gone ahead and updated this. Please check.

**Comment by ponny** [comment]
Thank you so much for this! We've been trying to get this fixed for literally YEARS!  Our first support ticket for this was in 2017 😆
