### ISSUE TITLE
App Login Issue - Age not recorded, no "Not me" option, and "Cancel" does not log out

### ISSUE THREAD

**Issue by mgoodfellow** [soundcloud/api#8]
## App Login Issue - Age not recorded, no "Not me / Sign out" option, and "Cancel" does not log out

Issue found as of 29/10/2020

We have noticed an issue where the App Login flow has changed for certain accounts, are there is no "Not me" setting to allow the user to gracefully logout.

It seems when information is provided, the answer to "What's your age?" is not persisted, and therefore, each time this login flow appears, you are stuck with the same questions.

This causes a critical login bug on mobile, as there is no way to logout and choose a different account. On web it causes a poor user experience, as a user has to open a different tab to go to SoundCloud and logout themselves, before then going back through the login flow to choose the correct account.

An example is here:

![image](https://user-images.githubusercontent.com/6501186/97555106-9abe0080-19cf-11eb-8732-33dbc5579e0c.png)

This is what we would expect - a "Not me / Sign Out" option:

![image](https://user-images.githubusercontent.com/6501186/97555294-dbb61500-19cf-11eb-87bc-413332789001.png)

**Comment by rahul-sc** [comment]
Hey @mgoodfellow. Could you shed a bit more light on this, please?

I can't quite understand how a user would end up in with a "logged in" state but at the same time be part of a "sign-up flow". Please share steps to reproduce this.

**Comment by mgoodfellow** [comment]
Hi @rahul-sc,

The only affected account I have seen myself is the one in the first picture, lektron.

This is an account created on SoundCloud many years ago. 

Steps to reproduce:

1. Login via 3rd party website (or login on SoundCloud directly in the same browser session)
2. Log out of that 3rd party website
3. Go back through the 3rd party website login flow 

For example:

1. Am already logged into SoundCloud:

![image](https://user-images.githubusercontent.com/6501186/97690962-a1af4680-1a95-11eb-8e6f-af36879f2de1.png)

2. Go to Repost By Soundcloud login (or any 3rd party app) and choose "Sign in with SoundCloud"

![image](https://user-images.githubusercontent.com/6501186/97691028-b8ee3400-1a95-11eb-8439-1111ac5fc700.png)

3. It asks for age, and there is no option to sign out of this account via this page.

![image](https://user-images.githubusercontent.com/6501186/97691076-c6a3b980-1a95-11eb-91e7-381a2358bf9a.png)

Normally a user could obviously open another tab and navigate to SoundCloud to logout there if they wanted to change account - however, this causes a problem via mobile logins as I cannot log out of this account to swap accounts, and I'm effectively stuck as I cannot open another tab in an embedded browser.

Maybe it's just this account that is affected? I have only seen it affect "lektron" - but setting Gender/Age and continuing does not help, and every time the same window is shown during 3rd party app logins (and not via the main SoundCloud login flow)

**Comment by theophani** [comment]
Hey @mgoodfellow, thanks for your detailed reproduction steps. It helped us understand the issue clearly.

We have made a change that address this issue in all the cases we have tested. Are you able to confirm that this behaviour now what you expect as well i.e. that you are shown the "Not me" prompt instead of being asked to provide missing demographic data?

**Comment by mgoodfellow** [comment]
Hi @theophani, thanks for the update!

With regards to lektron - I had provided demographic data previously (which I guess was actually being persisted), and when using this account, I can see the normal login now.

Unfortunately I don't have another edge case to hand so I cannot definitively confirm it is resolved from my side. However I'm happy for this to be closed, and if we receive any reports or issues for this issue we can relay them back to you?

Many thanks for your time!

**Comment by rahul-sc** [comment]
Excellent! Closing this
