### ISSUE TITLE
App registration/API key deleted

### ISSUE THREAD

**Issue by Vivien60** [soundcloud/api#81]
Hello,
I was looking into the new auth flows that are required now after I was getting 401s with my usual requests.
I checked my app registrations and found that an entire app registration has been deleted.
The app was registered through our soundcloud account used for devs : https://soundcloud.com/user327884478

That's true it's not very used, but it's normal because it is used for developement and maintenance.

So, can you reactive it ? And how avoid this to happen again ? 

Thanks for your reading, and have a good day.

**Comment by dasha-kobzeva** [comment]
Hi @Vivien60,
we have currently revoked the credentials that were not used in a while. It was a one-time job, so it should not happen again.
I have revoked your credentials.

**Comment by Vivien60** [comment]
Thank you ! That's nice to know it was exceptional :)
Have a good day !

**Comment by anne-a** [comment]
@dasha-kobzeva I have the same issue - I had 2 apps under account https://soundcloud.com/user333032999, both have been in use for years although 1 less frequently as it's used in the test environment, but it has now been deleted and has broken the application. Can it please be restored? I can send the client ID if that would be helpful.

**Comment by dasha-kobzeva** [comment]
Hi @anne-a, the credentials were revoked.

**Comment by anne-a** [comment]
@dasha-kobzeva Thank you I can see it's back now!

**Comment by raduandw** [comment]
Hello @dasha-kobzeva ,
We have two registered apps
The one with "-Dev" suffix works, we get access-tokens for it, but the other one returns "401 - Unauthorized" when attempting to get access-token.
Can you please help us solve this problem?
User is https://soundcloud.com/radio-trinitas
Thank you very much.
