### ISSUE TITLE
[QUESTION] redirect URI behind VPN

### ISSUE THREAD

**Issue by Vivien60** [soundcloud/api#82]
Hello, 
we have a project wich is a website accessible only trough a VPN. The customer has access to the VPN, so to the website also.
The question is :
Is it possible to use a redirect URI located in this website, or the redirect URI has to be acessible from "outside" web (  from Soundcloud to be precise )  ?
I think it's possible because it's not Soundcloud which contact the redirect URI, it's the browser, but as we have to ask you the change of the redirect URI, I prefer check with you before !

Thanks for reading !
Vivien60

**Comment by dasha-kobzeva** [comment]
Hi @Vivien60, 
I believe Soundcloud doesn't care about what the redirect is. The only thing we check via /connect is that your registered redirect_uri is matching the requesting one.

**Comment by Vivien60** [comment]
Hi @dasha-kobzeva ,
OK, cool, one less thing to worry about. 
I come back later to give you a redirect URI, and the app concerned. The 2 apps in fact : one for dev, one for prod.

**Comment by Vivien60** [comment]
Back. I checked with the customer for the change, and it's OK.
So, to keep secret the apps IDs, I put it on a link **readable only once** : 
https://privnote.com/XTisHKZt#uyVB6oGx9
App IDs, and redirects URI are inside.
Let me know if the use of this link is a problem  for you.

Thanks !

**Comment by dasha-kobzeva** [comment]
Hey @Vivien60,
you are all set.
