### ISSUE TITLE
Cannot retrieve track download URL with an API header reqest

### ISSUE THREAD

**Issue by starfrosch** [soundcloud/api#83]
## Title: Cannot retrieve track download URL with an API header reqest
Issue found of: July 26th, 2021

### Endpoint(s):
* `GET /tracks/{track_id}/download`

### Steps to reproduce:
```bash
curl --request GET \
--url 'https://api.soundcloud.com/tracks/767842108/download' \
--header 'Authorization: OAuth ACCESS_TOKEN'
```

I'd expect a behaviour like the stream endpoint

```bash
curl --request GET \
--url 'https://api.soundcloud.com/tracks/767842108/streams' \
--header 'Authorization: OAuth ACCESS_TOKEN'
```

with the CLIENT_ID URL token, it works like expected.

https://api.soundcloud.com/tracks/767842108/download?client_id=CLIENT_ID

### Expected behaviour:
An URL that allows to download a downloadable track

### Actual behaviour:
No output

**Comment by dasha-kobzeva** [comment]
Hi @starfrosch,

thank you for reaching out. 

When you are calling `https://api.soundcloud.com/tracks/767842108/download?client_id=CLIENT_ID` your request goes through the browser. The browser knows how to treat a response, so it automatically downloads the audio file.
But with curl it's different, and you might need to add additional params to your call in order to store the audio.

You could also try `wget` as curl is not very good with audio files.

**Comment by starfrosch** [comment]
Hi @dasha-kobzeva 

Thanks for that hint. With

```bash
wget -d --header="Authorization: OAuth ACCESS_TOKEN" --content-disposition https://api.soundcloud.com/tracks/767842108/download
```
it downloads the track on the server. So that works, but it's not the same behaviour like the old api.

Any idea how I can redirect the download to the client and have the same behaviour like before?

**Comment by dasha-kobzeva** [comment]
what do you mean by "the same behaviour like the old API"?
The only difference is that before you were sending a client_id, and now you send an oath header.

The logic of that endpoint did not change, only authorization.

**Comment by starfrosch** [comment]
Maybe you can help me to understand. Thanks for your time.

From a browser executing a PHP script I'm sending

            header('Authorization: OAuth ACCESS_TOKEN');
            header('Location: https://api.soundcloud.com/tracks/767842108/download');

I'm kinda stuck with ideas.

**Comment by dasha-kobzeva** [comment]
I'm not 100% familiar with PHP, but maybe this article is useful?
https://thisinterestsme.com/php-curl-custom-headers/

Seems like there is a special way to send headers.

Let me know if it helps.

**Comment by starfrosch** [comment]
This works but only server-side. The file is download to the server and not by the client. Any hints? What am I missing?

**Comment by dasha-kobzeva** [comment]
Ok, I'm not sure what your program is doing and what your code does, but I believe there is a number of resources online regarding file downloads. 
For example: https://www.tutorialrepublic.com/php-tutorial/php-file-download.php
As it is not related to SC anymore, I am closing this thread.
