### ISSUE TITLE
Cannot exchange authorization code for access token after successful web authorization (400 invalid_grant)

### ISSUE THREAD

**Issue by allebedew** [soundcloud/api#88]
## Title: Cannot exchange authorization code for access token after successful web authorization.
Issue found of: July 31th, 2021

### Endpoint(s):
* `POST /oauth2/token`

### Scope(s):
* Authorization

### Steps to reproduce:
Get authorization code from web using this URL
```
https://api.soundcloud.com/connect?client_id=XXX&redirect_uri&response_type=code
```

Exchange authorization code for a token
```bash
curl -X "POST" "https://api.soundcloud.com/oauth2/token" \
     -H 'Content-Type: application/x-www-form-urlencoded' \
     -H 'Accept: application/json' \
     --data-urlencode "grant_type=authorization_code" \
     --data-urlencode "client_id=XXX" \
     --data-urlencode "client_secret=YYY" \
     --data-urlencode "redirect_uri=" \
     --data-urlencode "code=3-252137-749859919-XXX"
```

### Expected behaviour:
Successful response containing authorization token

### Actual behaviour:
```json
{
  "code": 400,
  "message": "invalid_grant",
  "link": "https://developers.soundcloud.com/docs/api/explorer/open-api",
  "status": "400 - Bad Request",
  "errors": [
    {
      "error_message": "invalid_grant"
    }
  ],
  "error": null,
  "error_code": "invalid_grant"
}
```

**Comment by dasha-kobzeva** [comment]
HI @allebedew,
you are receiving `invalid_grant` error because you do not provide `redirect_uri` which is required. Your app should have been registered with one, and your request to /oauth2/token should match it.

**Comment by allebedew** [comment]
Hi, thanks for reply. `redirect_uri` is empty in my app, and there is no way to change it on [](https://soundcloud.com/you/apps). Auth request worked well with empty `redirect_uri` before latest API release. 
What can I do to make it work?

**Comment by dasha-kobzeva** [comment]
@allebedew could you please provide the user id the app is registered to? as well as the redirect uri. I will update it for you.

**Comment by allebedew** [comment]
User: `vrodakyiv`
App: `modular`
Set Redirect URL to: `ionica://soundcloud-callback`

**Comment by dasha-kobzeva** [comment]
@allebedew,
it should be working now. 

Let us know if you have further questions

**Comment by allebedew** [comment]
Thanks, now everything is working
