### ISSUE TITLE
Registering new apps

### ISSUE THREAD

**Issue by pixelicous** [soundcloud/api#90]
Hi,

Not sure how come i see people asking questions and opening issues here, for the past year and a half i've been trying to sign a new app on the developer program, but there is no such option.

Is the API open for working with it or not? Is it EVER going to be open to the public???

**Comment by dasha-kobzeva** [comment]
Hi @pixelicous,

 the registration of new apps is closed for now, but we are working towards opening it up. When  - is TBA.
At this point, we are working with existing users to improve the API.

**Comment by pixelicous** [comment]
@dasha-kobzeva yea.. i dont think it will ever be open.. as said for over a year and a half you are looking into it? problem with product or r&d as i see it, will never be open or it will be too late.

anyhow good luck with that.

**Comment by rahul-sc** [comment]
Hi @pixelicous - I appreciate you have an opinion on this. But I'd appreciate even more if you could be more polite towards my team. I'd be happy to provide a "code of conduct" on this repo, if that would be more useful. 

Cheers.

**Comment by pixelicous** [comment]
@rahul-sc I don't see any problem with what I wrote, the other way around, I think you should look internally and I would appreciate if your team provide a more detailed answer or transparency to a paying customer instead of giving me the feeling of being waved off, maybe i want to be one of the helping devs, is that possible? I have no idea.. I got a reply and my issue was closed immediately. So there was no added value at all in his reply.

Telling me that it will be public one day after years it hasn't been and that you are still working on it with developers is a bit funny and disrespectful to my question (especially as the repo is without much traffic and the API is non existent for 2-3 years - might even be more)

Anyhow, as I said, good luck.
Anyways as.

**Comment by rahul-sc** [comment]
Thank you for your feedback. We'll make sure to elaborate a bit more about our plans in the F.A.Q.

**Comment by alexweinstein** [comment]
Jumping in here as an API user. 

I've had a registered app with SC for about 7 years. During that time development was really, really hard. There was no support. Zero. Things would unexpectedly break and you were left to just figure it out on your own.

This effort by @rahul-sc and team to update the API, fix bugs, and communicate with the dev community is like a breath of fresh air. It's amazing. And while I understand your frustration, just know that when they do re-open registration, you will be building on a stronger foundation than the rest of us had.

**Comment by rahul-sc** [comment]
> Jumping in here as an API user.
> 
> I've had a registered app with SC for about 7 years. During that time development was really, really hard. There was no support. Zero. Things would unexpectedly break and you were left to just figure it out on your own.
> 
> This effort by @rahul-sc and team to update the API, fix bugs, and communicate with the dev community is like a breath of fresh air. It's amazing. And while I understand your frustration, just know that when they do re-open registration, you will be building on a stronger foundation than the rest of us had.

Thank you for your kind words @alexweinstein This is what keeps us motivated to help our dev community! We're a rather small team here - I don't think many people realize this. Again, thanks <3

**Comment by pixelicous** [comment]
@alexweinstein thank you for your explanation, this partly explains the situation..

@rahul-sc How Alex briefly gave an overview of the status of the api is a good response. You have to understand that the fact that the api hasn't been worked on is reflected across the web and SC website, so it's hard to get a clear understanding. Then try approaching the DEV team just to get a dismissive and yet another vague response on first try, it is not encouraging or explaining that great things will come.

**Comment by rahul-sc** [comment]
@pixelicous I appreciate your feedback - we're listening. We'll make sure to reflect this in our ways of working and perhaps it's indeed time for a much more detailed community update from our side.
