### ISSUE TITLE
Need to configure redirect_URI on SoundCloud

### ISSUE THREAD

**Issue by benchmarkrules** [soundcloud/api#91]
Hi,

I am now getting an unauthorized message with my PHP SoundCloud App like that is described in: Soundcloud API authentication always throws "401 - Unauthorized"

After much reading, I understand that what my App needs is an authorization code. To get one of those, I need a redirect_url configured in the App settings on SoundCloud. I don't have one. How do I change the redirect_urI?
Thanks

**Comment by dasha-kobzeva** [comment]
Hi @benchmarkrules,
we can update it for you.

Could you please provide your user id (which has the app registered), the email address for that user, and redirect_uri?
In order to not make it public, you can use https://yopass.net/#/ for encryption.

**Comment by benchmarkrules** [comment]
Hi @dasha-kobzeva ,
I am not sure how to use yopass.net. I can generate short links etc and decryption keys but what do I post here? Just the short link?
Thanks

**Comment by dasha-kobzeva** [comment]
For your convenience, please refer to our readme https://github.com/soundcloud/api#how-can-i-update-my-apps-redirect_uri to update the data safely.

Thank you

**Comment by benchmarkrules** [comment]
Hi @dasha-kobzeva ,
Thanks for that. I have done what that link says.
Thanks again
