### ISSUE TITLE
Soundcloud Streaming API

### ISSUE THREAD

**Issue by BJM2000** [soundcloud/api#93]
Hi,

I hope someone can help.

I am concerned that the new changes will break my Soundcloud integration and I don't have much knowledge of coding.
I use Soundcloud to stream Private tracks to my website, which is subscriber-based. The Url structure below is an example of what I use to stream the tracks using a Wordpress MP3 Player plugin. 

What would need to change in the following example of how I use the Soundcloud API as a url, or is it not quite so simple?:

https://api.soundcloud.com/tracks/*********/stream?secret_token=*******&client_id=************************************

Thank you in advance :)

**Comment by dasha-kobzeva** [comment]
Hi @BJM2000, 

in the URL you have provided `client_id=XXX` part will have to go. 
Instead, you should provide a header `Authorization: OAuth <YOUR_TOKEN>` 

To acquire the token you can use this endpoint with your client credentials: https://developers.soundcloud.com/docs/api/explorer/open-api#/oauth/post_oauth2_token
grant_type=client_credentials.

Be aware that the token might expire, in that case, update it with grant_type=`refresh_token`.
You can read more about it in our guide: https://developers.soundcloud.com/docs/api/guide#authentication

**Comment by jasongrishkoff** [comment]
Hi @dasha-kobzeva - do you have any tips for integrating with <audio> tags? We use HTML audio for playback, and from my research it seems that one can't pass Authorization headers this way. I can access the stream endpoint with Authorization server-side, but that ends up downloading the full MP3 before actually returning a response, which doesn't seem right.

**Comment by dasha-kobzeva** [comment]
Hi @jasongrishkoff,
I'm not as familiar with HTML tags, but I found some resources that might be of use (unless you have seen them already)

https://security.stackexchange.com/questions/175695/how-to-pass-authorization-header-in-http-request-when-using-html5-player-audio

**Comment by jasongrishkoff** [comment]
I've been down that rabbit hole, yep. No easy answer.

I know once I make the request with `client_id` in the URL string, SoundCloud redirects me to a .mp3 link.  Is it possible to simply figure out the redirect URL?  Eg, fetching `https://api.soundcloud.com/tracks/1007024134/stream` with the correct Auth Headers returns a fully-signed URL rather than the full MP3?

**Comment by mgoodfellow** [comment]
It does return a fully signed URL.

The response is a 302 which curl (or other libs) will follow automatically.

Just don't follow the redirect - you want to take the Location header from the 302 response.

**Comment by jasongrishkoff** [comment]
Thanks, you're right. Got it working. In case anyone's working in nodejs with audio tags, here's how I get the stream server-side:
```
getSoundCloudStream = function(stream,oauth) {
        const { https } = require('follow-redirects')                                                                                                      
        const url = require('url')
        var options = url.parse(stream)
        options.headers = {'Authorization':'OAuth ' + oauth}
        return new Promise((resolve, reject) => {
            const request = https.request(options,response => {                                                                                                                      
                if (response?.responseUrl) {
                    resolve(response.responseUrl)                                                                                                                                    
                } else {  
                    reject('Error')                                                                                                                                                  
                }                                                                                                                                                                    
            })
            request.end()                                                                                                                                                            
        }) 
}
```
This function returns the MP3, which can then be passed as the `src` for the `<audio>` tags.

**Comment by dasha-kobzeva** [comment]
I will close this ticket for now.

Let me know if there is any other questions/issues we can assist you with.

**Comment by hanoii** [comment]
Do we know if the downloadable URL expires or changes overtime?
