### ISSUE TITLE
My app credentials seem to have been revoked

### ISSUE THREAD

**Issue by jesshmusic** [soundcloud/api#94]
## Title: Cannot retrieve all tracks for a user
Issue found of: August 3, 2021

My client_id is `9bcb79c128cd8dce1d9d3a69a4662d71` and I was told to create a ticket for you all to reinstate it here: https://github.com/soundcloud/api/issues/84#issuecomment-891924682

**Comment by dasha-kobzeva** [comment]
@jesshmusic, your app should be back now.

**Comment by jesshmusic** [comment]
Thanks so much. I'm guessing there is no way to change the URL? My site URL changed a while back and this is giving me a 401 when I try to get my token

**Comment by dasha-kobzeva** [comment]
Hi @jesshmusic,
for URL changes please refer to our readme:  https://github.com/soundcloud/api#how-can-i-update-my-apps-redirect_uri

Thank you
