### ISSUE TITLE
SoundCloud gem breaking soon?

### ISSUE THREAD

**Issue by ponny** [soundcloud/api#95]
## Title: SoundCloud gem breaking soon?
We're currently using the unmaintained [Ruby gem for using the SoundCloud API](https://github.com/soundcloud/soundcloud-ruby).  The [recent blog post by SoundCloud](https://developers.soundcloud.com/blog/security-updates-api) says that going forward we must send an `Authenticaiton` header but the gem is still using the old `client_id` method.  It's still working today but it looks like that will stop "soon (from July 2021)"

I'd raise an issue there but issue tracking is disabled.  We can fork the gem but I wanted to check if it was going to be updated or if you had a suggestion of a different gem first.

**Comment by dasha-kobzeva** [comment]
Hi @ponny,
We have stopped supporting Ruby SDK, and considering either deprecating it completely or making it open source.

May I ask you if it goes open-source, would you be interested in maintaining it?

**Comment by ponny** [comment]
We've made a fork and we'll update it to use the latest API.  Sergei's created a pull with the updates here: https://github.com/soundcloud/soundcloud-ruby/pull/1

Sure, we can maintain the project.  We'll be keeping the gem _working_ for the foreseeable future so we can share that around.  I don't think we'll write changes for endpoints we don't use/new APIs being added but would accept pull requests.

**Comment by ponny** [comment]
Okay, I see the pull has been accepted now.  Ta :-)
