### ISSUE TITLE
Resolve endpoint no longer returning Location header

### ISSUE THREAD

**Issue by mgoodfellow** [soundcloud/api#97]
## Title: Resolve endpoint no longer returning Location header
Issue found of: August 5th, 2021

### Endpoint(s):
* `GET /resolve?url=https://soundcloud.com/esotera`

### Scope(s):
* Server token (client credentials)

### Expected behaviour:
A 302 response with a `Location` header to point to the resource

### Actual behaviour:
It appears the output has changed, and no longer is the `Location` header set. Instead there is a body which contains the information, but receiving a 302 without a `Location` header is a strange HTTP response to receive.

This was an unexpected functional change to the API

**Comment by mgoodfellow** [comment]
Just to confirm, I am aware the body was there previously, but Location header is more of a widely accepted header to use with 302 as opposed to content in the body (3xx don't typically respond with content).

As an aside, it appears other redirect style endpoints such as `/tracks/{id}/stream` still return the `Location` header while also returning a body. This header allows automatic redirect following instead of requiring manually parsing of the body and custom code to "follow" the redirect.

Are other redirect endpoints going to be changed to also remove the `Location` headers?

**Comment by rahul-sc** [comment]
Hey @mgoodfellow our engineers are looking into this. We'll respond here soon.

**Comment by remover** [comment]
@mgoodfellow Thanks for reporting. A fix has been deployed...

**Comment by mgoodfellow** [comment]
Awesome thanks @remover - all looks good from our end! Thanks for the speedy fix :)
