### ISSUE TITLE
Upcoming API Security Updates

### ISSUE THREAD

**Issue by shefaligupta5** [soundcloud/api#98]
Hi team,

We, the Product Development team at the Irish Times have been contact by Soundcloud team recently regarding a potential updates to your API.

Following link was shared with us: https://developers.soundcloud.com/blog/security-updates-api

We use soundcloud APIs to pull audio for the audio content on our website https://www.irishtimes.com. 
Our concern is given the number of changes that you are proposing, it's not easy for us to achieve these in the given amount of time.

Therefore we are reaching out to the Soundcloud team to find an alternative solution for this. What's the minimum change that we are required to do so we comply with Soundcloud security updates.

Thanks & Regards,
Shefali Gupta
Development Lead at the Irish Times

**Comment by rahul-sc** [comment]
Hello. This really depends on your integration and how you use the API. What touchpoints are affected by the upcoming changes? Happy to advise an alternative. 

Also, what is the timeline that would work for you to incorporate all the changes?

**Comment by shefaligupta5** [comment]
Hi team,

We use something similar as below to integrate Soundcloud on our website to pull audios.

[cid:f2d0886a-9299-4e6f-9b58-73cccf197820]

We use -

  *   client_id, client_secret, grant_type, token request url for querying the API
  *   oauth_token as a query parameter
  *   password as grant type
  *   non-expiring tokens

Let me know if you need anything else.

Regards,
Shefali

________________________________

**Comment by rahul-sc** [comment]
Thanks for the information, Shefali. 

It looks to me that your integration is quite outdated and is not secure enough for us to support. Both oauth_token as query param and password grant not supported anymore. 

If you're integration is using user context, please use the authorization_code flow (grant type `code`)
https://developers.soundcloud.com/docs/api/explorer/open-api#/oauth/get_connect

We also recommend using expiring tokens and refreshing them as needed in order to secure your integration. This is something we can give further grace period on but it it necessary in due time.

**Comment by shefaligupta5** [comment]
Thank you for the information.

As per you, how much time do we have to make these changes?

Thanks,
Shefali
________________________________

**Comment by dasha-kobzeva** [comment]
Hi @shefaligupta5,
we expect to fully roll out the changes by the end of September.

Does this timeline work for you?

**Comment by DJUCED** [comment]
Hello, we did make the move to update the security. But we are facing an issue, for our users the free playlists are not available any more without being logged in with at least a basic account. 
Is there a way to still have the free playlist for not logged users?

**Comment by dasha-kobzeva** [comment]
> Hello, we did make the move to update the security. But we are facing an issue, for our users the free playlists are not available any more without being logged in with at least a basic account.
> Is there a way to still have the free playlist for not logged users?

yes, you can use client_credentials flow to authenticate your app and allow users to stream without login.
https://developers.soundcloud.com/docs/api/guide#authentication

**Comment by Subfader** [comment]
killing the API is protecting it very well so far!

**Comment by pluc** [comment]
This is breaking our use of Soundcloud as our integration is purely automated as a CLI app without user interaction. With this change we can no longer upload tracks, and should it be implemented in production will force us to migrate away from Soundcloud.
