### ISSUE TITLE
API access broken due to security changes // app not visible in account anymore

### ISSUE THREAD

**Issue by derwaldgeist** [soundcloud/api#99]
Hi Soundcloud,

we have been happily using the Soundcloud API for some years now, using an API key we got back in 2015. Users are happy with the integration, and it was working fine.

All of the sudden, the integration failed, and I was able to track it down to the recent security update. So far, we had been using GET requests with a client_id. When we now tried to switch to OAUTH2, using the client credentials we had generated back then, these were not accepted. If I go to the app page of my Soundcloud account, it doesn't show any app either. It's just gone. And if I try to apply for a new app, the registration page is shut down as well.

How can we restore access now? We still have the credentials, but they are not accepted anymore... :-/

**Comment by rahul-sc** [comment]
Hey @derwaldgeist what's the SC profile your API key is under? Happy to look into it.

**Comment by derwaldgeist** [comment]
Do you mean my e-mail address?

**Comment by derwaldgeist** [comment]
I am trying to login, but the website says "Our robot thinks you are a robot" now. Maybe, because I tried to log off and on again multiple times, in the hope this would restore my credentials.

**Comment by derwaldgeist** [comment]
Okay, managed to login with a different browser. The URL says "tom-br-ckner". Is this the ID you need?

**Comment by rahul-sc** [comment]
I've reinstated your app. Please go to verify
https://soundcloud.com/you/apps

**Comment by derwaldgeist** [comment]
Hey, thanks a million, it's back!!! Hooray! Any idea why it got removed?

**Comment by rahul-sc** [comment]
Glad to see it worked. This was an accident on our part as we're doing a security clean up.
Please do make sure to apply the other security updates to avoid disruption in the near future :)

**Comment by derwaldgeist** [comment]
Ok, all good, I am already working on the OAuth update. Thanks again for your fast support, highly appreciated!
